import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire((process.env.ACL_TEST_NODE_MODULES||process.cwd()+'/node_modules')+'/../package.json');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{}
const testUi=(name,fn)=>test(name,{skip:!JSDOM},fn);
const policyUrl=new URL('../js/core/appointmentPolicy.js',import.meta.url).href;
let source=await readFile(new URL('../js/modules/appointments.js',import.meta.url),'utf8');source=source.replace(/^import .*;\n/gm,'');source=`import {APPOINTMENT_STATUSES,localDay,appointmentConflicts} from '${policyUrl}';const loadAppointments=()=>globalThis.uiLoad();const saveAppointment=(...args)=>globalThis.uiSave(...args);const permissionAllowed=(a,p)=>a.permissions.includes(p);\n`+source;
const {renderAppointments}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const ctx={tenantId:'a',access:{permissions:['events.read','events.manage']},schools:[{id:'s1',nome:'Escola <Gilza>'},{id:'s2',nome:'Outra'}],classes:[{id:'c1',nome:'2A',idEscola:'s1'},{id:'c2',nome:'Outra turma',idEscola:'s2'}],rows:[]};
const setup=()=>{const dom=new JSDOM('<html><head><link data-appointments></head><body><main></main></body></html>');globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.FormData=dom.window.FormData;dom.window.HTMLElement.prototype.scrollIntoView=function(){};globalThis.uiLoad=async()=>structuredClone(ctx);globalThis.uiSave=async()=>1;return document.querySelector('main');};
const tick=()=>new Promise(r=>setImmediate(r));
testUi('interface: escola filtra turmas, demanda remove vínculos e salvamento exibe sucesso',async()=>{const host=setup();await renderAppointments(host);host.querySelector('#apNewSchool').click();const form=host.querySelector('#apForm');form.elements.idEscola.value='s1';form.elements.idEscola.dispatchEvent(new window.Event('change'));assert.match(host.querySelector('#apClasses').textContent,/2A/);assert.doesNotMatch(host.querySelector('#apClasses').textContent,/Outra turma/);form.elements.origem.value='Demanda espontânea';form.elements.origem.dispatchEvent(new window.Event('change'));assert.equal(form.elements.idEscola.value,'');assert.equal(host.querySelector('#apClasses').textContent,'');form.elements.nome.value='Comunidade';form.elements.solicitante.value='Moradores';let saved;globalThis.uiSave=async data=>{saved=data;return 1;};form.dispatchEvent(new window.Event('submit',{cancelable:true}));await tick();await tick();assert.equal(saved.origem,'Demanda espontânea');assert.equal(saved.previsto,0);assert.deepEqual(saved.idsTurmas,[]);assert.match(host.querySelector('#apMessage').textContent,/salvo online/);});
testUi('interface: falha mantém formulário e mostra erro; consulta não mostra cadastrar',async()=>{const host=setup();globalThis.uiSave=async()=>{throw new Error('Falha de rede');};await renderAppointments(host);host.querySelector('#apNewDemand').click();const form=host.querySelector('#apForm');form.dispatchEvent(new window.Event('submit',{cancelable:true}));await tick();assert.match(host.querySelector('#apFormMessage').textContent,/Falha de rede/);assert.equal(host.querySelector('#apEditor').hidden,false);globalThis.uiLoad=async()=>({...structuredClone(ctx),access:{permissions:['events.read']}});await renderAppointments(host);assert.equal(host.querySelector('#apNewSchool'),null);assert.equal(host.querySelector('#apNewDemand'),null);});
testUi('interface: carregar agenda não substitui módulo aberto durante a espera',async()=>{const host=setup();let finish;globalThis.uiLoad=()=>new Promise(r=>finish=r);const pending=renderAppointments(host);host.innerHTML='<h2>Outro módulo</h2>';finish(structuredClone(ctx));await pending;assert.equal(host.textContent,'Outro módulo');});
testUi('interface: calendário semanal e mensal renderizam e navegam',async()=>{const host=setup();await renderAppointments(host);host.querySelector('[data-view="semana"]').click();assert.equal(host.querySelectorAll('.schedule-day').length,7);host.querySelector('[data-nav="1"]').click();assert.equal(host.querySelectorAll('.schedule-day').length,7);host.querySelector('[data-view="mes"]').click();assert.equal(host.querySelectorAll('.schedule-day').length,42);});
