import {test,after} from 'node:test';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const enabled=!!process.env.FIRESTORE_EMULATOR_HOST;let env,fs,ok,no;
if(enabled){const require=createRequire((process.env.ACL_TEST_NODE_MODULES||process.cwd()+'/node_modules')+'/../package.json'),rules=require('@firebase/rules-unit-testing');fs=require('firebase/firestore');ok=rules.assertSucceeds;no=rules.assertFails;env=await rules.initializeTestEnvironment({projectId:'demo-agenda',firestore:{rules:await readFile(new URL('../firestore.rules',import.meta.url),'utf8')}});await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();const docs={'platformOwners/owner':{active:true},'platformStaff/operator':{active:true,allClients:false,tenantIds:['a'],permissions:['events.read','events.manage']},'platformStaff/reader':{active:true,allClients:false,tenantIds:['a'],permissions:['events.read']},'tenants/a/members/manager':{active:true,role:'GESTOR'},'tenants/a/members/blocked':{active:false,role:'GESTOR'},'tenants/a/schools/s1':{nome:'Escola'},'tenants/a/classes/c1':{nome:'A',idEscola:'s1'},'tenants/a/classes/wrong':{nome:'Outra',idEscola:'s2'},'tenants/a/students/student':{nome:'Ana',idTurma:'c1'}};for(let i=2;i<=6;i++)docs['tenants/a/classes/c'+i]={nome:'Turma '+i,idEscola:'s1'};for(const [path,data]of Object.entries(docs))await fs.setDoc(fs.doc(db,path),data);});after(()=>env.cleanup());}
const dbFor=uid=>env.authenticatedContext(uid).firestore();
const data=()=>({tenantId:'a',nome:'Atendimento',origem:'Escola',tipo:'Palestra',status:'Planejado',idEscola:'s1',idsTurmas:['c1'],solicitante:'',contato:'Maria',telefone:'',email:'',publico:'2º ano',dataInicio:'2026-10-10',dataFim:'2026-10-10',horaInicio:'09:00',horaFim:'10:00',local:'Escola',responsavel:'Equipe',previsto:20,realizado:0,vagas:30,materiais:'Cartilha 20',equipe:'Maria',observacao:'',serieId:'',createdBy:'operator',updatedBy:'operator',createdAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp()});
test('agenda: operador grava escola e demanda; consulta não grava e não lê alunos',{skip:!enabled},async()=>{await ok(fs.setDoc(fs.doc(dbFor('operator'),'tenants/a/appointments/school'),data()));await ok(fs.setDoc(fs.doc(dbFor('operator'),'tenants/a/appointments/demand'),{...data(),origem:'Demanda espontânea',idEscola:'',idsTurmas:[],solicitante:'Comunidade'}));await ok(fs.getDocs(fs.collection(dbFor('reader'),'tenants/a/appointments')));await ok(fs.getDocs(fs.collection(dbFor('reader'),'tenants/a/schools')));await ok(fs.getDocs(fs.collection(dbFor('reader'),'tenants/a/classes')));await no(fs.getDoc(fs.doc(dbFor('reader'),'tenants/a/students/student')));await no(fs.updateDoc(fs.doc(dbFor('reader'),'tenants/a/appointments/school'),{status:'Cancelado',updatedBy:'reader',updatedAt:fs.serverTimestamp()}));});
test('agenda: outro cliente, bloqueado, anônimo e vínculos inválidos são negados',{skip:!enabled},async()=>{await no(fs.setDoc(fs.doc(dbFor('operator'),'tenants/b/appointments/outside'),{...data(),tenantId:'b'}));await no(fs.getDocs(fs.collection(dbFor('blocked'),'tenants/a/appointments')));await no(fs.getDocs(fs.collection(env.unauthenticatedContext().firestore(),'tenants/a/appointments')));for(const [id,patch]of Object.entries({school:{idEscola:'missing'},class:{idsTurmas:['wrong']},hours:{horaFim:'08:00'},capacity:{previsto:31},extra:{publicadoOnline:true},author:{createdBy:'owner'}}))await no(fs.setDoc(fs.doc(dbFor('operator'),'tenants/a/appointments/'+id+'-bad'),{...data(),...patch}));});
test('agenda: cancela preservando histórico, autor e série; gestor também pode excluir',{skip:!enabled},async()=>{const db=dbFor('operator'),ref=fs.doc(db,'tenants/a/appointments/edit');await ok(fs.setDoc(ref,data()));await ok(fs.updateDoc(ref,{status:'Cancelado',updatedBy:'operator',updatedAt:fs.serverTimestamp()}));await no(fs.updateDoc(ref,{createdBy:'owner',updatedAt:fs.serverTimestamp()}));await no(fs.updateDoc(ref,{serieId:'forged',updatedAt:fs.serverTimestamp()}));await ok(fs.deleteDoc(ref));});
test('agenda: lote atômico de 60 ocorrências com cinco turmas funciona',{skip:!enabled},async()=>{const db=dbFor('operator'),batch=fs.writeBatch(db);for(let i=0;i<60;i++)batch.set(fs.doc(db,'tenants/a/appointments/serie-'+i),{...data(),idsTurmas:['c1','c2','c3','c4','c5'],serieId:'batch'});await ok(batch.commit());});

test('agenda: gestor do cliente grava cinco turmas e proprietário consulta todos',{skip:!enabled},async()=>{await ok(fs.setDoc(fs.doc(dbFor('manager'),'tenants/a/appointments/manager-six'),{...data(),idsTurmas:['c1','c2','c3','c4','c5'],createdBy:'manager',updatedBy:'manager'}));await ok(fs.getDocs(fs.collection(dbFor('owner'),'tenants/a/appointments')));});

test('repositório: grava e recarrega do servidor e impede sobrescrita de edição concorrente',{skip:!enabled},async()=>{let source=(await readFile(new URL('../js/core/appointmentRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');globalThis.appDb=dbFor('operator');globalThis.appFs=fs;const policy=new URL('../js/core/appointmentPolicy.js',import.meta.url).href;source=`import {validateAppointment,buildOccurrences,appointmentConflicts} from '${policy}';const requirePermission=async()=>({uid:'operator',active:true,allSchools:true});const accessDb=async()=>({db:globalThis.appDb,fs:globalThis.appFs});const getCloudTenantId=()=>'a';`+source;const repo=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),ctx=await repo.loadAppointments();const d=data();for(const k of ['tenantId','serieId','createdBy','updatedBy','createdAt','updatedAt'])delete d[k];d.nome='Repositório real';d.dataInicio=d.dataFim='2027-01-10';const count=await repo.saveAppointment(d,ctx);if(count!==1)throw new Error('Gravação ausente');const next=await repo.loadAppointments(),saved=next.rows.find(r=>r.nome===d.nome);if(!saved)throw new Error('Não recarregou');await repo.saveAppointment({...d,status:'Confirmado'},next,{id:saved.id,version:{seconds:saved.updatedAt.seconds,nanoseconds:saved.updatedAt.nanoseconds}});const {default:assert}=await import('node:assert/strict');await assert.rejects(repo.saveAppointment({...d,status:'Cancelado'},next,{id:saved.id,version:{seconds:saved.updatedAt.seconds,nanoseconds:saved.updatedAt.nanoseconds}}),/Outro usuário/);});

