import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire((process.env.ACL_TEST_NODE_MODULES||process.cwd()+'/node_modules')+'/../package.json');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{}
const source=await readFile(new URL('../js/modules/admin.js',import.meta.url),'utf8');
const body=source.slice(source.indexOf('function eventForm('),source.indexOf('function attendanceEditor('));
const {eventForm}=await import('data:text/javascript;base64,'+Buffer.from("const uid=()=>'',read=k=>globalThis.legacyRows[k]||[],esc=v=>String(v??''),fmtPhone=v=>String(v??''),today=()=>'2026-10-05',toLines=()=>'',parseLines=()=>[];"+body+'export {eventForm};').toString('base64'));
test('agenda anterior filtra escola inicial, limpa seleção ao trocar e informa escola sem turmas',{skip:!JSDOM},()=>{const dom=new JSDOM('<main></main>');globalThis.FormData=dom.window.FormData;globalThis.legacyRows={escolas:[{id:'s1',nome:'A'},{id:'s2',nome:'B'},{id:'s3',nome:'C'}],turmas:[{id:'c1',nome:'2A',idEscola:'s1'},{id:'c2',nome:'3B',idEscola:'s2'}]};const host=dom.window.document.querySelector('main');eventForm({id:'event',idEscola:'s1',idsTurmas:['c1','c2']},host,()=>{});assert.equal(host.querySelector('#eventClasses').textContent.includes('2A'),true);assert.equal(host.querySelector('#eventClasses').textContent.includes('3B'),false);assert.equal(host.querySelector('[name="turma"]').checked,true);const select=host.querySelector('[name="idEscola"]');select.value='s2';select.dispatchEvent(new dom.window.Event('change'));assert.equal(host.querySelector('[name="turma"]').value,'c2');assert.equal(host.querySelector('[name="turma"]').checked,false);select.value='s3';select.dispatchEvent(new dom.window.Event('change'));assert.match(host.querySelector('#eventClasses').textContent,/não possui turmas/);select.value='';select.dispatchEvent(new dom.window.Event('change'));assert.match(host.querySelector('#eventClasses').textContent,/Selecione uma escola/);});
