import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire((process.env.ACL_TEST_NODE_MODULES||process.cwd()+'/node_modules')+'/../package.json');let JSDOM;try{({JSDOM}=require('jsdom'));}catch{}
const source=await readFile(new URL('../js/modules/admin.js',import.meta.url),'utf8');
const body=source.slice(source.indexOf('function eventForm('),source.indexOf('function attendanceEditor('));
const {eventForm}=await import('data:text/javascript;base64,'+Buffer.from("const uid=()=>'',read=k=>globalThis.legacyRows[k]||[],esc=v=>String(v??''),fmtPhone=v=>String(v??''),today=()=>'2026-10-05',toLines=()=>'',parseLines=()=>[],loadSchoolClasses=async id=>(globalThis.legacyCatalog?.classes||globalThis.legacyRows.turmas||[]).filter(t=>t.idEscola===id);"+body+'export {eventForm};').toString('base64'));
test('agenda anterior filtra escola inicial, limpa seleção ao trocar e informa escola sem turmas',{skip:!JSDOM},async()=>{const dom=new JSDOM('<main></main>');globalThis.FormData=dom.window.FormData;globalThis.legacyRows={escolas:[{id:'s1',nome:'A'},{id:'s2',nome:'B'},{id:'s3',nome:'C'}],turmas:[{id:'c1',nome:'2A',idEscola:'s1'},{id:'c2',nome:'3B',idEscola:'s2'}]};const host=dom.window.document.querySelector('main');eventForm({id:'event',idEscola:'s1',idsTurmas:['c1','c2']},host,()=>{});assert.equal(host.querySelector('#eventClasses').textContent.includes('2A'),true);assert.equal(host.querySelector('#eventClasses').textContent.includes('3B'),false);assert.equal(host.querySelector('[name="turma"]').checked,true);const select=host.querySelector('[name="idEscola"]');select.value='s2';select.dispatchEvent(new dom.window.Event('change'));await new Promise(r=>setImmediate(r));assert.equal(host.querySelector('[name="turma"]').value,'c2');assert.equal(host.querySelector('[name="turma"]').checked,false);select.value='s3';select.dispatchEvent(new dom.window.Event('change'));await new Promise(r=>setImmediate(r));assert.match(host.querySelector('#eventClasses').textContent,/não possui turmas/);select.value='';select.dispatchEvent(new dom.window.Event('change'));await new Promise(r=>setImmediate(r));assert.match(host.querySelector('#eventClasses').textContent,/Selecione uma escola/);});

test('agenda anterior usa catálogo online mesmo sem visitar cadastros antes',{skip:!JSDOM},()=>{const dom=new JSDOM('<main></main>');globalThis.legacyRows={};globalThis.legacyCatalog={tenantId:'a',schools:[{id:'s1',nome:'Escola online'}],classes:[{id:'c1',nome:'Turma online',idEscola:'s1'}]};const host=dom.window.document.querySelector('main');eventForm({id:'ev',idEscola:'s1',idsTurmas:['c1']},host,()=>{},globalThis.legacyCatalog);assert.match(host.querySelector('[name="idEscola"]').textContent,/Escola online/);assert.match(host.querySelector('#eventClasses').textContent,/Turma online/);assert.equal(host.querySelector('[name="turma"]').checked,true);});
