import {test,after} from 'node:test';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const enabled=!!process.env.FIRESTORE_EMULATOR_HOST;let env,fs,ok,no;
if(enabled){const require=createRequire((process.env.ACL_TEST_NODE_MODULES||process.cwd()+'/node_modules')+'/../package.json'),rules=require('@firebase/rules-unit-testing');fs=require('firebase/firestore');ok=rules.assertSucceeds;no=rules.assertFails;env=await rules.initializeTestEnvironment({projectId:'demo-agenda',firestore:{rules:await readFile(new URL('../firestore.rules',import.meta.url),'utf8')}});await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();const docs={'platformOwners/owner':{active:true},'platformStaff/operator':{active:true,allClients:false,tenantIds:['a'],permissions:['events.read','events.manage']},'platformStaff/reader':{active:true,allClients:false,tenantIds:['a'],permissions:['events.read']},'tenants/a/members/manager':{active:true,role:'GESTOR'},'tenants/a/members/blocked':{active:false,role:'GESTOR'},'tenants/a/schools/s1':{nome:'Escola'},'tenants/a/classes/c1':{nome:'A',idEscola:'s1'},'tenants/a/classes/wrong':{nome:'Outra',idEscola:'s2'},'tenants/a/students/student':{nome:'Ana',idTurma:'c1'}};for(let i=2;i<=6;i++)docs['tenants/a/classes/c'+i]={nome:'Turma '+i,idEscola:'s1'};for(const [path,data]of Object.entries(docs))await fs.setDoc(fs.doc(db,path),data);});after(()=>env.cleanup());}
const dbFor=uid=>env.authenticatedContext(uid).firestore();
test('escola Windows: proprietário importa uma vez, mantém cadastro e associa escola existente',{skip:!enabled},async()=>{
 const {default:assert}=await import('node:assert/strict');globalThis.schoolDb=dbFor('owner');globalThis.schoolFs=fs;
 let source=(await readFile(new URL('../js/core/appointmentRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
 const winPolicy=new URL('../js/core/windowsAgendaPolicy.js',import.meta.url).href,policy=new URL('../js/core/appointmentPolicy.js',import.meta.url).href;
 source=`import {windowsSchoolData,normalizeWindows} from '${winPolicy}';import {validateAppointment,buildOccurrences,appointmentConflicts} from '${policy}';const requirePermission=async()=>({uid:'owner',allSchools:true});const accessDb=async()=>({db:globalThis.schoolDb,fs:globalThis.schoolFs});const getCloudTenantId=()=>'a';`+source;
 const repo=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),school={idEscola:47,nome:'Escola Importada',cidade:'Presidente Prudente',telefone:'18 1234',responsavel:'Diretora'},ctx={tenantId:'a'};
 const results=await Promise.all([repo.importWindowsSchool(school,'Windows',ctx),repo.importWindowsSchool(school,'Windows',ctx)]);assert.equal(results.filter(r=>r.created).length,1);const ref=fs.doc(globalThis.schoolDb,'tenants/a/schools/windows-school-Windows-47'),saved=(await fs.getDoc(ref)).data();assert.equal(saved.municipio,school.cidade);assert.equal(saved.contato,school.responsavel);assert.equal(saved.createdBy,'owner');const catalog=await repo.loadWindowsSchoolCatalog();assert.ok(catalog.schools.some(s=>s.id===results[0].id));assert.equal(catalog.rows.length,0);
 await fs.updateDoc(ref,{telefone:'EDITADO',updatedBy:'owner',updatedAt:fs.serverTimestamp()});assert.equal((await repo.importWindowsSchool(school,'Windows',ctx)).created,false);assert.equal((await fs.getDoc(ref)).data().telefone,'EDITADO');
 assert.deepEqual(await repo.importWindowsSchool({idEscola:100,nome:'Escola'},'Windows',ctx),{id:'s1',created:false});await assert.rejects(repo.importWindowsSchool(school,'Windows',{tenantId:'b'}),/Cliente alterado/);
 await no(fs.setDoc(fs.doc(dbFor('operator'),'tenants/a/schools/not-permitted'),{nome:'Nova',tenantId:'a',createdBy:'operator',updatedBy:'operator',createdAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp()}));
});
test('histórico integral: acesso privado, imutável e restrito ao cliente',{skip:!enabled},async()=>{
 const hash='a'.repeat(64),db=dbFor('operator'),manifest={tenantId:'a',banco:'Windows',versao:3,chunks:1,agendamentos:83,createdBy:'operator',createdAt:fs.serverTimestamp()},chunk={tenantId:'a',archiveId:hash,index:0,data:'{"original":true}',createdBy:'operator',createdAt:fs.serverTimestamp()};
 await ok(fs.setDoc(fs.doc(db,'tenants/a/windowsArchiveChunks',hash+'-0'),chunk));await ok(fs.setDoc(fs.doc(db,'tenants/a/windowsArchives',hash),manifest));
 await ok(fs.getDoc(fs.doc(dbFor('reader'),'tenants/a/windowsArchives',hash)));await no(fs.getDoc(fs.doc(dbFor('blocked'),'tenants/a/windowsArchives',hash)));await no(fs.getDoc(fs.doc(dbFor('operator'),'tenants/b/windowsArchives',hash)));await no(fs.getDoc(fs.doc(env.unauthenticatedContext().firestore(),'tenants/a/windowsArchiveChunks',hash+'-0')));
 await no(fs.updateDoc(fs.doc(db,'tenants/a/windowsArchiveChunks',hash+'-0'),{data:'alterado'}));await no(fs.deleteDoc(fs.doc(db,'tenants/a/windowsArchives',hash)));await no(fs.setDoc(fs.doc(dbFor('reader'),'tenants/a/windowsArchives','b'.repeat(64)),{...manifest,createdBy:'reader'}));
 const ref=fs.doc(db,'tenants/a/appointments/integral-status');await ok(fs.setDoc(ref,{...data(),status:'Reagendado',windowsSource:{archiveId:hash,agendaId:1}}));await ok(fs.updateDoc(ref,{status:'Em preparação',updatedAt:fs.serverTimestamp()}));await no(fs.updateDoc(ref,{windowsSource:{archiveId:hash,agendaId:2},updatedAt:fs.serverTimestamp()}));
});
const data=()=>({tenantId:'a',nome:'Atendimento',origem:'Escola',tipo:'Palestra',status:'Planejado',idEscola:'s1',idsTurmas:['c1'],solicitante:'',contato:'Maria',telefone:'',email:'',publico:'2º ano',dataInicio:'2026-10-10',dataFim:'2026-10-10',horaInicio:'09:00',horaFim:'10:00',local:'Escola',responsavel:'Equipe',previsto:20,realizado:0,vagas:30,materiais:'Cartilha 20',equipe:'Maria',observacao:'',serieId:'',createdBy:'operator',updatedBy:'operator',createdAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp()});
test('agenda: operador grava escola e demanda; consulta não grava e não lê alunos',{skip:!enabled},async()=>{await ok(fs.setDoc(fs.doc(dbFor('operator'),'tenants/a/appointments/school'),data()));await ok(fs.setDoc(fs.doc(dbFor('operator'),'tenants/a/appointments/demand'),{...data(),origem:'Demanda espontânea',idEscola:'',idsTurmas:[],solicitante:'Comunidade'}));await ok(fs.getDocs(fs.collection(dbFor('reader'),'tenants/a/appointments')));await ok(fs.getDocs(fs.collection(dbFor('reader'),'tenants/a/schools')));await ok(fs.getDocs(fs.collection(dbFor('reader'),'tenants/a/classes')));await no(fs.getDoc(fs.doc(dbFor('reader'),'tenants/a/students/student')));await no(fs.updateDoc(fs.doc(dbFor('reader'),'tenants/a/appointments/school'),{status:'Cancelado',updatedBy:'reader',updatedAt:fs.serverTimestamp()}));});
test('agenda: outro cliente, bloqueado, anônimo e vínculos inválidos são negados',{skip:!enabled},async()=>{await no(fs.setDoc(fs.doc(dbFor('operator'),'tenants/b/appointments/outside'),{...data(),tenantId:'b'}));await no(fs.getDocs(fs.collection(dbFor('blocked'),'tenants/a/appointments')));await no(fs.getDocs(fs.collection(env.unauthenticatedContext().firestore(),'tenants/a/appointments')));for(const [id,patch]of Object.entries({school:{idEscola:'missing'},class:{idsTurmas:['wrong']},hours:{horaFim:'08:00'},capacity:{previsto:31},extra:{publicadoOnline:true},author:{createdBy:'owner'}}))await no(fs.setDoc(fs.doc(dbFor('operator'),'tenants/a/appointments/'+id+'-bad'),{...data(),...patch}));});
test('agenda: cancela preservando histórico, autor e série; não exclui',{skip:!enabled},async()=>{const db=dbFor('operator'),ref=fs.doc(db,'tenants/a/appointments/edit');await ok(fs.setDoc(ref,data()));await ok(fs.updateDoc(ref,{status:'Cancelado',updatedBy:'operator',updatedAt:fs.serverTimestamp()}));await no(fs.updateDoc(ref,{createdBy:'owner',updatedAt:fs.serverTimestamp()}));await no(fs.updateDoc(ref,{serieId:'forged',updatedAt:fs.serverTimestamp()}));await no(fs.deleteDoc(ref));});
test('agenda: lote atômico de 60 ocorrências com cinco turmas funciona',{skip:!enabled},async()=>{const db=dbFor('operator'),batch=fs.writeBatch(db);for(let i=0;i<60;i++)batch.set(fs.doc(db,'tenants/a/appointments/serie-'+i),{...data(),idsTurmas:['c1','c2','c3','c4','c5'],serieId:'batch'});await ok(batch.commit());});

test('agenda: gestor do cliente grava cinco turmas e proprietário consulta todos',{skip:!enabled},async()=>{await ok(fs.setDoc(fs.doc(dbFor('manager'),'tenants/a/appointments/manager-six'),{...data(),idsTurmas:['c1','c2','c3','c4','c5'],createdBy:'manager',updatedBy:'manager'}));await ok(fs.getDocs(fs.collection(dbFor('owner'),'tenants/a/appointments')));});

test('repositório: grava e recarrega do servidor e impede sobrescrita de edição concorrente',{skip:!enabled},async()=>{let source=(await readFile(new URL('../js/core/appointmentRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');globalThis.appDb=dbFor('operator');globalThis.appFs=fs;const policy=new URL('../js/core/appointmentPolicy.js',import.meta.url).href;source=`import {validateAppointment,buildOccurrences,appointmentConflicts} from '${policy}';const requirePermission=async()=>({uid:'operator',active:true,allSchools:true});const accessDb=async()=>({db:globalThis.appDb,fs:globalThis.appFs});const getCloudTenantId=()=>'a';`+source;const repo=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),ctx=await repo.loadAppointments();const d=data();for(const k of ['tenantId','serieId','createdBy','updatedBy','createdAt','updatedAt'])delete d[k];d.nome='Repositório real';d.dataInicio=d.dataFim='2027-01-10';const count=await repo.saveAppointment(d,ctx);if(count!==1)throw new Error('Gravação ausente');const next=await repo.loadAppointments(),saved=next.rows.find(r=>r.nome===d.nome);if(!saved)throw new Error('Não recarregou');await repo.saveAppointment({...d,status:'Confirmado'},next,{id:saved.id,version:{seconds:saved.updatedAt.seconds,nanoseconds:saved.updatedAt.nanoseconds}});const {default:assert}=await import('node:assert/strict');await assert.rejects(repo.saveAppointment({...d,status:'Cancelado'},next,{id:saved.id,version:{seconds:saved.updatedAt.seconds,nanoseconds:saved.updatedAt.nanoseconds}}),/Outro usuário/);});
test('importação Windows: transação cria uma vez e reimportação preserva edição',{skip:!enabled},async()=>{
 let source=(await readFile(new URL('../js/core/appointmentRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');globalThis.winDb=dbFor('operator');globalThis.winFs=fs;const policy=new URL('../js/core/appointmentPolicy.js',import.meta.url).href;
 source=`import {validateAppointment,buildOccurrences,appointmentConflicts} from '${policy}';const requirePermission=async()=>({uid:'operator',allSchools:true});const accessDb=async()=>({db:globalThis.winDb,fs:globalThis.winFs});const getCloudTenantId=()=>'a';`+source;
 const repo=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64')),ctx=await repo.loadAppointments(),d=data();for(const k of ['tenantId','serieId','createdBy','updatedBy','createdAt','updatedAt'])delete d[k];
 const id='windows-agenda-Windows-83',results=await Promise.all([repo.importWindowsAppointment(d,ctx,id),repo.importWindowsAppointment(d,ctx,id)]);const {default:assert}=await import('node:assert/strict');assert.equal(results.filter(Boolean).length,1);
 await fs.updateDoc(fs.doc(globalThis.winDb,'tenants/a/appointments',id),{nome:'Editado no site',updatedBy:'operator',updatedAt:fs.serverTimestamp()});assert.equal(await repo.importWindowsAppointment(d,ctx,id),false);assert.equal((await fs.getDoc(fs.doc(globalThis.winDb,'tenants/a/appointments',id))).data().nome,'Editado no site');
});
test('repositório integral: arquivo completo, retomada e anexação a agenda existente sem sobrescrever',{skip:!enabled},async()=>{
 const {default:assert}=await import('node:assert/strict');const pack={versao:3,banco:'Windows',tabelas:{tblAgendaEvento:[{idAgenda:83,status:'REAGENDADO'}]}};
 globalThis.intDb=dbFor('operator');globalThis.intFs=fs;
 const policyURL=new URL('../js/core/windowsIntegralPolicy.js',import.meta.url).href;
 let src=(await readFile(new URL('../js/core/windowsArchiveRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
 src=`import {archivePayload} from '${policyURL}';const requirePermission=async()=>({uid:'operator',allSchools:true});const accessDb=async()=>({db:globalThis.intDb,fs:globalThis.intFs});const getCloudTenantId=()=>'a';`+src;
 const repo=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64')),hash=await repo.saveWindowsArchive(pack,{'1':'s1'},'a');assert.equal(await repo.saveWindowsArchive(pack,{'1':'s1'},'a'),hash);assert.deepEqual((await repo.loadWindowsArchive(hash,'a')).pack,pack);
 let app=(await readFile(new URL('../js/core/appointmentRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');const appointmentPolicy=new URL('../js/core/appointmentPolicy.js',import.meta.url).href;
 app=`import {validateAppointment,buildOccurrences,appointmentConflicts} from '${appointmentPolicy}';const requirePermission=async()=>({uid:'operator',allSchools:true});const accessDb=async()=>({db:globalThis.intDb,fs:globalThis.intFs});const getCloudTenantId=()=>'a';`+app;
 const agenda=await import('data:text/javascript;base64,'+Buffer.from(app).toString('base64')),ctx=await agenda.loadAppointments(),id='windows-agenda-Windows-83',d=data();for(const k of ['tenantId','serieId','createdBy','updatedBy','createdAt','updatedAt'])delete d[k];
 const ref=fs.doc(globalThis.intDb,'tenants/a/appointments',id),before=(await fs.getDoc(ref)).data();assert.equal(await agenda.importWindowsAppointment({...d,status:'Reagendado'},ctx,id,{archiveId:hash,agendaId:83}),false);const after=(await fs.getDoc(ref)).data();assert.equal(after.nome,before.nome);assert.equal(after.status,before.status);assert.equal(after.windowsSource.archiveId,hash);
});
test('turmas Windows: transação concorrente e edição preservada',{skip:!enabled},async()=>{
 const {default:assert}=await import('node:assert/strict');const policy=new URL('../js/core/windowsClassPolicy.js',import.meta.url).href;globalThis.wcDb=dbFor('owner');globalThis.wcFs=fs;globalThis.wcUid='owner';
 let src=(await readFile(new URL('../js/core/windowsClassRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');src=`import {windowsClassData,matchingWindowsClasses} from '${policy}';const requirePermission=async()=>({uid:globalThis.wcUid,allSchools:true});const accessDb=async()=>({db:globalThis.wcDb,fs:globalThis.wcFs});const getCloudTenantId=()=>'a';`+src;
 const repo=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64')),ctx=await repo.loadWindowsClassCatalog(),s={idTurma:999,idEscola:1,descricao:'2 A manhã',turno:'Manhã',anoLetivo:2026,serie:'2',ativo:1},p={banco:'Windows'};
 const results=await Promise.all([repo.importWindowsClass(s,p,'s1',ctx),repo.importWindowsClass(s,p,'s1',ctx)]);assert.equal(results.filter(r=>r.created).length,1);const ref=fs.doc(globalThis.wcDb,'tenants/a/classes/windows-class-Windows-999');await fs.updateDoc(ref,{nome:'Editada',updatedBy:'owner',updatedAt:fs.serverTimestamp()});assert.equal((await repo.importWindowsClass(s,p,'s1',ctx)).created,false);assert.equal((await fs.getDoc(ref)).data().nome,'Editada');await assert.rejects(repo.importWindowsClass(s,p,'wrong',ctx),/outra escola|Escola não encontrada/);globalThis.wcDb=dbFor('operator');globalThis.wcUid='operator';await assert.rejects(repo.importWindowsClass({...s,idTurma:998},p,'s1',ctx));
});
test('alunos Windows: cria uma vez, mantém edições, valida turma e exige permissão',{skip:!enabled},async()=>{
 const {default:assert}=await import('node:assert/strict');const policy=new URL('../js/core/windowsStudentPolicy.js',import.meta.url).href;globalThis.wsDb=dbFor('owner');globalThis.wsFs=fs;globalThis.wsUid='owner';
 let src=(await readFile(new URL('../js/core/windowsStudentRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');src=`import {windowsStudentData} from '${policy}';const requirePermission=async()=>({uid:globalThis.wsUid,allSchools:true});const accessDb=async()=>({db:globalThis.wsDb,fs:globalThis.wsFs});const getCloudTenantId=()=>'a';`+src;
 const repo=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64')),ctx=await repo.loadWindowsStudentCatalog(),a={idParticipante:999,idEscola:1,idTurma:1,nome:'Aluno importado',ativo:1};const results=await Promise.all([repo.importWindowsStudent(a,'Windows','c1',ctx),repo.importWindowsStudent(a,'Windows','c1',ctx)]);assert.equal(results.filter(r=>r.created).length,1);const ref=fs.doc(globalThis.wsDb,'tenants/a/students/windows-student-Windows-999');await fs.updateDoc(ref,{nome:'Editado',responsavel:'Mãe',updatedBy:'owner',updatedAt:fs.serverTimestamp()});assert.equal((await repo.importWindowsStudent(a,'Windows','c1',ctx)).created,false);assert.equal((await fs.getDoc(ref)).data().responsavel,'Mãe');await assert.rejects(repo.importWindowsStudent(a,'Windows','c2',ctx),/outra turma/);await assert.rejects(repo.importWindowsStudent({...a,idParticipante:998},'Windows','missing',ctx),/Turma não encontrada/);
 const reuse=await repo.importWindowsStudent({...a,idParticipante:997},'Windows','c1',ctx,'windows-student-Windows-999');assert.equal(reuse.created,false);assert.equal((await fs.getDoc(fs.doc(globalThis.wsDb,'tenants/a/students/windows-student-Windows-997'))).exists(),false);globalThis.wsDb=dbFor('operator');globalThis.wsUid='operator';await assert.rejects(repo.importWindowsStudent({...a,idParticipante:996},'Windows','c1',ctx));
});

test('Windows: completar turmas vazias preserva edição e rejeita concorrência ou outro vínculo',{skip:!enabled},async()=>{
 const {default:assert}=await import('node:assert/strict');globalThis.linkDb=dbFor('operator');globalThis.linkFs=fs;
 let source=(await readFile(new URL('../js/core/appointmentRepository.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
 const url=new URL('../js/core/appointmentPolicy.js',import.meta.url).href;
 source=`import {validateAppointment,buildOccurrences,appointmentConflicts} from '${url}';const requirePermission=async()=>({uid:'operator',allSchools:true});const accessDb=async()=>({db:globalThis.linkDb,fs:globalThis.linkFs});const getCloudTenantId=()=>'a';`+source;
 const repo=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));const ref=fs.doc(globalThis.linkDb,'tenants/a/appointments/windows-agenda-Windows-9999');
 await fs.setDoc(ref,{...data(),nome:'Editado manualmente',idsTurmas:[],status:'Reagendado'});let ctx=await repo.loadAppointments(),old=ctx.rows.find(r=>r.id==='windows-agenda-Windows-9999');
 await assert.rejects(repo.completeWindowsAppointmentClasses(old.id,['wrong'],ctx,old),/turma|Turma/);
 await fs.updateDoc(ref,{local:'Local editado',updatedBy:'operator',updatedAt:fs.serverTimestamp()});await assert.rejects(repo.completeWindowsAppointmentClasses(old.id,['c1'],ctx,old),/alterado/);
 ctx=await repo.loadAppointments();old=ctx.rows.find(r=>r.id==='windows-agenda-Windows-9999');assert.equal(await repo.completeWindowsAppointmentClasses(old.id,['c1'],ctx,old),true);
 const saved=(await fs.getDoc(ref)).data();assert.equal(saved.nome,'Editado manualmente');assert.equal(saved.local,'Local editado');assert.equal(saved.status,'Reagendado');assert.deepEqual(saved.idsTurmas,['c1']);
 ctx=await repo.loadAppointments();old=ctx.rows.find(r=>r.id==='windows-agenda-Windows-9999');await assert.rejects(repo.completeWindowsAppointmentClasses(old.id,['c2'],ctx,old),/já possui turmas/);
});
