import {loadAppointments} from '../core/appointmentRepository.js?v=8';
import {accessDb} from '../core/cloudAccess.js?v=1';
import {getCloudTenantId} from '../cloudGateway.js?v=6';
import {agendaSummary} from '../core/agendaSummary.js?v=1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateText=d=>d.split('-').reverse().join('/');
export async function loadAgendaOverview(){
 const ctx=await loadAppointments(),{db,fs}=await accessDb();let events=[],eventsError='';
 try{const snap=await fs.getDocsFromServer(fs.collection(db,'tenants',ctx.tenantId,'publicEvents'));events=snap.docs.map(d=>({...d.data(),id:d.id}));}catch(e){eventsError='Não foi possível carregar os eventos online. O resumo abaixo inclui os atendimentos disponíveis.';}
 if(ctx.tenantId!==getCloudTenantId())throw new Error('Cliente alterado. Atualize o painel.');
 return {ctx,events,eventsError,loadedAt:new Date()};
}
export function renderAgendaOverview(host,onOpen){
 host._agendaCleanup?.();let request=0,disposed=false,cache=null,selectedDay='',busy=false;
 const alive=()=>!disposed&&host.isConnected;
 const school=r=>cache.ctx.schools.find(s=>s.id===r.idEscola)?.nome||r.solicitante||r.local||'Local a definir';
 const openRow=key=>{const r=agendaSummary(cache.ctx,cache.events).all.find(r=>r.key===key);if(r)onOpen(r.kind==='Evento'?{publicEvents:true}:{appointmentId:r.id});};
 const rowsHtml=rows=>rows.length?rows.map(r=>`<button type="button" class="overview-item" data-overview-row="${esc(r.key)}"><span class="overview-time">${r.horaInicio?esc(r.horaInicio):'Horário a definir'}<small>${dateText(r.dataInicio)}${r.dataFim!==r.dataInicio?' a '+dateText(r.dataFim):''}</small></span><span class="overview-copy"><strong>${esc(r.nome)}</strong><small>${esc(school(r))}</small><small>${esc(r.local||'Local a definir')}${r.responsavel?' • '+esc(r.responsavel):''}</small></span><span class="overview-status"><span>${esc(r.status||'Não informado')}</span><small>${r.kind}</small></span></button>`).join(''):'<p class="overview-empty">Nenhum compromisso neste período.</p>';
 function draw(){if(!alive()||!cache)return;const s=agendaSummary(cache.ctx,cache.events),day=selectedDay||s.today;const stamp=(cache.loadedAt||new Date()).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
  host.innerHTML=`<section class="agenda-overview"><header class="overview-heading"><div><p class="eyebrow">AGENDA E COMPROMISSOS</p><h2>Sua agenda em dia</h2><p>${new Date(s.today+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><div class="overview-actions"><button type="button" class="btn ghost" id="overviewRefresh">↻ Atualizar resumo</button><button type="button" class="btn primary" id="overviewAgenda">Abrir agenda</button></div></header><p class="overview-sync" role="status">Atualizado às ${stamp} • dados online do cliente selecionado • atualização automática a cada 5 minutos.</p>${cache.eventsError?`<p class="overview-warning" role="alert">${esc(cache.eventsError)}</p>`:''}<div class="overview-kpis">${[['Hoje',s.todayRows.length,'Compromissos do dia'],['Nesta semana',s.week.length,'Segunda a domingo'],['Em andamento',s.inProgress.length,'Atendimentos e eventos'],['A confirmar',s.toConfirm.length,'Solicitados ou em preparação'],['Pendências vencidas',s.overdue.length,'Conferir o status'],['Avisos',s.alerts.length,'Horários e organização']].map(([label,note,detail])=>`<article><span>${label}</span><strong>${note}</strong><small>${detail}</small></article>`).join('')}</div><div class="overview-layout"><section class="overview-card"><header><h3>Compromissos de hoje</h3><span>${s.todayRows.length}</span></header>${rowsHtml(s.todayRows)}</section><section class="overview-card"><header><h3>Avisos e pendências</h3><span>${s.alerts.length}</span></header><p class="overview-note">Avisos nesta página, calculados a partir da agenda.</p>${s.alerts.slice(0,6).map(a=>`<button type="button" class="overview-alert ${a.level}" data-overview-row="${esc(a.key)}"><strong>${esc(a.title)}</strong><span>${esc(a.text)}</span></button>`).join('')||'<p class="overview-empty">Nenhum aviso identificado na agenda.</p>'}${s.alerts.length>6?`<p class="overview-note">Mais ${s.alerts.length-6} avisos. Abra a agenda para conferir os demais registros.</p>`:''}</section></div><section class="overview-card overview-week"><header><h3>Visão da semana</h3><span>${dateText(s.weekStart)} a ${dateText(s.weekEnd)}</span></header><div class="overview-days">${s.days.map(d=>`<button type="button" data-overview-day="${d}" class="${d===day?'selected':''} ${d===s.today?'today':''}" aria-pressed="${d===day}"><span>${new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short'})}</span><strong>${d.slice(8,10)}</strong><small>${s.onDay(d).length} compromisso(s)</small></button>`).join('')}</div><h4>${dateText(day)}${day===s.today?' • Hoje':''}</h4>${rowsHtml(s.onDay(day))}</section><section class="overview-card"><header><h3>Em curso e próximos compromissos</h3><span>${s.upcoming.length}</span></header>${rowsHtml(s.upcoming.slice(0,6))}${s.upcoming.length>6?'<button type="button" class="btn ghost" id="overviewMore">Ver agenda completa</button>':''}</section></section>`;
  host.querySelectorAll('[data-overview-row]').forEach(b=>b.onclick=()=>openRow(b.dataset.overviewRow));host.querySelectorAll('[data-overview-day]').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.overviewDay;draw();});host.querySelector('#overviewRefresh').onclick=refresh;host.querySelector('#overviewAgenda').onclick=()=>onOpen({});const more=host.querySelector('#overviewMore');if(more)more.onclick=()=>onOpen({});
 }
 async function refresh(){if(!alive()||busy)return;busy=true;const n=++request,tenant=getCloudTenantId();host.innerHTML='<section class="overview-card"><h2>Agenda e compromissos</h2><p role="status">Carregando resumo online...</p></section>';
  try{const data=await loadAgendaOverview();if(!alive()||n!==request||tenant!==getCloudTenantId())return;cache=data;draw();}catch(e){if(alive()&&n===request){cache=null;host.innerHTML=`<section class="overview-card"><h2>Agenda e compromissos</h2><p role="alert">${esc(e.message)}</p><button class="btn ghost" type="button" id="overviewRetry">Tentar novamente</button></section>`;host.querySelector('#overviewRetry').onclick=refresh;}}finally{busy=false;}
 }
 const interval=setInterval(()=>{if(!document.hidden)refresh();},300000),visibility=()=>{if(!document.hidden)refresh();};document.addEventListener('visibilitychange',visibility);
 host._agendaCleanup=()=>{disposed=true;request++;clearInterval(interval);document.removeEventListener('visibilitychange',visibility);};refresh();
}
