import {tenant,subscription,currentPlan,PLAN_CATALOG,FEATURE_CATALOG,saveTenant,previewPlan,usageSnapshot} from '../core/saasContext.js?v=2';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function css(){
 if(document.getElementById('saas360css'))return;
 const s=document.createElement('style');s.id='saas360css';
 s.textContent='.saas-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.saas-kpi,.saas-panel,.plan-card{background:#fff;border:1px solid #d9e7ee;border-radius:14px;padding:14px}.saas-kpi strong{display:block;font-size:1.3rem;color:#0a678f}.saas-kpi span{font-size:.76rem;color:#6f8491}.saas-note{padding:12px 14px;border-left:4px solid #0b78a8;background:#eef8fc;border-radius:10px;line-height:1.45;margin:10px 0}.saas-warn{border-left-color:#dda000;background:#fff6d9}.saas-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.saas-grid label{display:grid;gap:5px;font-size:.8rem;font-weight:900;color:#315a72}.saas-grid input,.saas-grid select{padding:10px;border:1px solid #c8dce7;border-radius:10px}.plans{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.plan-card.current{outline:2px solid #0b78a8}.plan-card h3{margin:0}.plan-card p{color:#708593;min-height:48px}.feat{display:block;font-size:.75rem;padding:4px 0}.limit{font-size:.72rem;color:#6f8491}.saas-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;margin-top:12px}.meter{height:8px;border-radius:999px;background:#e8eff3;overflow:hidden}.meter span{display:block;height:100%;background:#0b78a8}@media(max-width:1000px){.plans{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.saas-kpis,.saas-grid,.plans{grid-template-columns:1fr}}';
 document.head.appendChild(s);
}
function limitText(v,label){return v==null?'Ilimitado':v+' '+label;}
function pct(v,max){return max==null?15:Math.min(100,Math.round((Number(v)||0)/Math.max(1,max)*100));}

export function renderAssinaturaSaas(host){
 css();
 const draw=()=>{
  const t=tenant(),s=subscription(),p=currentPlan(),u=usageSnapshot();
  host.innerHTML='<section class="admin-module"><p class="eyebrow">PRODUTO & ASSINATURA • FUNDAÇÃO SAAS</p><h2>Modelo comercial do Mobiliza Educa</h2><p class="admin-intro">Organização, planos, recursos e consumo preparados para futura cobrança recorrente.</p>'+
  '<div class="saas-note saas-warn"><strong>Ambiente de desenvolvimento.</strong> A seleção de plano abaixo é apenas uma prévia local. Nenhum bloqueio comercial é considerado seguro enquanto autenticação, assinatura e autorização não forem validadas no backend.</div>'+
  '<div class="saas-kpis"><div class="saas-kpi"><strong>'+esc(p.name)+'</strong><span>plano em prévia</span></div><div class="saas-kpi"><strong>'+u.users+'</strong><span>usuários ativos</span></div><div class="saas-kpi"><strong>'+u.eventsMonth+'</strong><span>eventos neste mês</span></div><div class="saas-kpi"><strong>'+u.schools+'</strong><span>escolas cadastradas</span></div></div>'+
  '<div class="saas-panel"><h3>Organização / tenant</h3><form id="tenantForm"><div class="saas-grid"><label>Nome da organização<input name="name" value="'+esc(t.name)+'"></label><label>Slug técnico<input name="slug" value="'+esc(t.slug)+'"></label><label>Tipo<input name="type" value="'+esc(t.type||'CLIENTE')+'"></label><label>ID local<input value="'+esc(t.id)+'" disabled></label></div><div class="saas-actions"><button class="btn primary">Salvar organização</button></div></form></div>'+
  '<div class="saas-panel" style="margin-top:12px"><h3>Catálogo inicial de planos</h3><p style="color:#6f8491">Valores ainda não definidos. Primeiro estamos separando recursos e limites para evitar amarrar cobrança à interface.</p><div class="plans">'+PLAN_CATALOG.map(x=>'<article class="plan-card '+(x.id===p.id?'current':'')+'"><h3>'+esc(x.name)+'</h3><p>'+esc(x.description)+'</p><div>'+x.features.map(f=>'<span class="feat">✓ '+esc(FEATURE_CATALOG[f]||f)+'</span>').join('')+'</div><hr><div class="limit">Usuários: '+limitText(x.limits.users,'usuário(s)')+'</div><div class="limit">Eventos/mês: '+limitText(x.limits.eventsMonth,'evento(s)')+'</div><div class="limit">Armazenamento: '+(x.limits.storageMb==null?'Ilimitado':x.limits.storageMb+' MB')+'</div><div class="saas-actions"><button class="btn '+(x.id===p.id?'ghost':'primary')+' small" data-plan="'+x.id+'">'+(x.id===p.id?'Selecionado':'Simular plano')+'</button></div></article>').join('')+'</div></div>'+
  '<div class="saas-panel" style="margin-top:12px"><h3>Consumo atual × limites do plano</h3><div class="saas-grid"><div><strong>Usuários</strong><p>'+u.users+' de '+(p.limits.users==null?'∞':p.limits.users)+'</p><div class="meter"><span style="width:'+pct(u.users,p.limits.users)+'%"></span></div></div><div><strong>Eventos neste mês</strong><p>'+u.eventsMonth+' de '+(p.limits.eventsMonth==null?'∞':p.limits.eventsMonth)+'</p><div class="meter"><span style="width:'+pct(u.eventsMonth,p.limits.eventsMonth)+'%"></span></div></div></div></div>'+
  '<div class="saas-note"><strong>Arquitetura comercial preparada:</strong> tenant → assinatura → plano → entitlements → limites de uso. Na fase de nuvem, esses dados deverão ser autoritativos no servidor e integrados ao provedor de cobrança.</div></section>';
  host.querySelector('#tenantForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());saveTenant({name:d.name.trim(),slug:d.slug.trim().toLowerCase().replace(/[^a-z0-9-]/g,'-'),type:d.type.trim()||'CLIENTE'});alert('Organização atualizada.');draw();};
  host.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{if(b.dataset.plan===p.id)return;if(confirm('Simular o plano '+b.dataset.plan+' neste ambiente local? Isso não cria cobrança nem contrato.')){previewPlan(b.dataset.plan);draw();}});
 };
 draw();
}
