
import {listEditorialQuestions,listEditorialHistory,listCategories,saveCategory,saveEditorialQuestion,setQuestionStatus,duplicateQuestion,questionStats,resetEditorialToBase} from '../core/contentRepository.js?v=1';
import {currentUser} from '../core/accessControl.js?v=1';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const canHomologate=()=>currentUser()?.profileId==='GESTOR';

function ensureCss(){
 if(document.getElementById('editorial360css'))return;
 const s=document.createElement('style');s.id='editorial360css';
 s.textContent='.ed-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.ed-tab{border:1px solid #c9dce7;background:#fff;color:#214e69;padding:10px 13px;border-radius:11px;font-weight:900;cursor:pointer}.ed-tab.active{background:#0b709f;color:#fff}.ed-kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin:12px 0}.ed-kpi,.ed-panel{background:#fff;border:1px solid #d9e7ee;border-radius:14px;padding:13px}.ed-kpi strong{display:block;font-size:1.35rem;color:#0a678f}.ed-kpi span{font-size:.72rem;color:#6f8491}.ed-filter{display:grid;grid-template-columns:1.5fr 1fr 1fr 1fr 1fr auto;gap:8px;margin:10px 0}.ed-filter input,.ed-filter select,.ed-grid input,.ed-grid select,.ed-grid textarea{padding:9px;border:1px solid #c9dce7;border-radius:10px;font:inherit;background:#fff}.ed-table-wrap{overflow:auto}.ed-table{width:100%;border-collapse:collapse;font-size:.75rem}.ed-table th,.ed-table td{padding:8px;border-bottom:1px solid #e4edf2;text-align:left;vertical-align:top}.ed-table th{font-size:.64rem;text-transform:uppercase;color:#6b8190}.ed-table small{display:block;color:#748894}.ed-status{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:.68rem;font-weight:900;background:#edf4f7;color:#456a80}.ed-status.ok{background:#e3f6e9;color:#176638}.ed-status.warn{background:#fff2d5;color:#855b05}.ed-status.muted{background:#eceff1;color:#6e777d}.ed-editor{margin-top:12px;padding:14px;border:1px solid #cfe0e9;border-radius:14px;background:#f9fcfd}.ed-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.ed-grid label{display:grid;gap:5px;font-size:.8rem;font-weight:900;color:#315a72}.ed-span2{grid-column:1/-1}.ed-actions{display:flex;gap:6px;flex-wrap:wrap}.ed-note{padding:11px 13px;border-left:4px solid #0b78a8;background:#eef8fc;border-radius:10px}.cat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.cat-card{border:1px solid #dce8ee;border-radius:11px;padding:10px}.cat-card small{display:block;color:#748894}@media(max-width:1000px){.ed-kpis{grid-template-columns:repeat(3,1fr)}.ed-filter{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.ed-grid,.cat-grid{grid-template-columns:1fr}.ed-span2{grid-column:auto}.ed-filter{grid-template-columns:1fr 1fr}.ed-kpis{grid-template-columns:repeat(2,1fr)}}';
 document.head.appendChild(s);
}
function statusClass(v){return v==='Homologado'?'ok':v==='Em revisão'?'warn':v==='Arquivado'?'muted':'';}
function nextId(){const rows=listEditorialQuestions(),n=Math.max(0,...rows.map(x=>Number((String(x.id).match(/\d+/)||['0'])[0])))+1;return 'Q'+String(n).padStart(4,'0');}
function blank(){return{id:nextId(),audience:'criancas',category:listCategories()[0]?.id||'geral',difficulty:'facil',prompt:'',options:['','','',''],correct:0,why:'',status:'Rascunho'};}

export function renderCentroEditorial(host){
 ensureCss();let tab='banco';
 function shell(){
  const st=questionStats();
  host.innerHTML='<section class="admin-module"><p class="eyebrow">CENTRO EDITORIAL • v1.0</p><h2>Conteúdo pedagógico governado</h2><p class="admin-intro">Crie, revise, homologue e versione o banco utilizado pelos jogos e avaliações.</p>'+
  '<div class="ed-kpis"><div class="ed-kpi"><strong>'+st.total+'</strong><span>questões</span></div><div class="ed-kpi"><strong>'+st.published+'</strong><span>homologadas</span></div><div class="ed-kpi"><strong>'+st.drafts+'</strong><span>rascunhos</span></div><div class="ed-kpi"><strong>'+st.review+'</strong><span>em revisão</span></div><div class="ed-kpi"><strong>'+st.archived+'</strong><span>arquivadas</span></div><div class="ed-kpi"><strong>'+st.categories+'</strong><span>categorias</span></div></div>'+
  '<div class="ed-tabs"><button class="ed-tab '+(tab==='banco'?'active':'')+'" data-tab="banco">📝 Banco</button><button class="ed-tab '+(tab==='categorias'?'active':'')+'" data-tab="categorias">🏷️ Categorias</button><button class="ed-tab '+(tab==='revisao'?'active':'')+'" data-tab="revisao">✅ Revisão</button><button class="ed-tab '+(tab==='historico'?'active':'')+'" data-tab="historico">🕓 Histórico</button></div><div id="edBody"></div></section>';
  host.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;shell();});renderBody();
 }
 function renderBody(){const b=host.querySelector('#edBody');if(tab==='banco')bankView(b);else if(tab==='categorias')categoryView(b);else if(tab==='revisao')reviewView(b);else historyView(b);}
 function bankView(b){
  const rows=listEditorialQuestions(),cats=listCategories();
  b.innerHTML='<div class="ed-panel"><div class="ed-actions" style="justify-content:space-between"><div><h3>Banco de perguntas</h3><small>Somente conteúdo homologado entra nos jogos e avaliações.</small></div><button class="btn primary" id="edNew">+ Nova questão</button></div>'+
  '<div class="ed-filter"><input id="edQ" type="search" placeholder="Pesquisar..."><select id="edAud"><option value="">Todos públicos</option><option value="criancas">Crianças</option><option value="adolescentes">Adolescentes</option><option value="adultos">Adultos</option></select><select id="edCat"><option value="">Todas categorias</option>'+cats.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('')+'</select><select id="edDif"><option value="">Todas dificuldades</option><option value="facil">Fácil</option><option value="medio">Médio</option><option value="dificil">Difícil</option></select><select id="edSt"><option value="">Todos status</option><option>Rascunho</option><option>Em revisão</option><option>Homologado</option><option>Arquivado</option></select><button class="btn ghost" id="edClear">Limpar</button></div><div id="edTable"></div><div id="edEditor"></div></div>';
  const paint=()=>{const q=b.querySelector('#edQ').value.toLowerCase(),aud=b.querySelector('#edAud').value,cat=b.querySelector('#edCat').value,dif=b.querySelector('#edDif').value,st=b.querySelector('#edSt').value,filtered=rows.filter(x=>(!q||x.id.toLowerCase().includes(q)||x.prompt.toLowerCase().includes(q))&&(!aud||x.audience===aud)&&(!cat||x.category===cat)&&(!dif||x.difficulty===dif)&&(!st||x.status===st));b.querySelector('#edTable').innerHTML='<div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>ID</th><th>Questão</th><th>Público</th><th>Categoria</th><th>Dificuldade</th><th>Status</th><th>Rev.</th><th>Ações</th></tr></thead><tbody>'+filtered.map(x=>'<tr><td><strong>'+esc(x.id)+'</strong></td><td>'+esc(x.prompt)+'<small>'+esc(x.why)+'</small></td><td>'+esc(x.audience)+'</td><td>'+esc(x.category)+'</td><td>'+esc(x.difficulty)+'</td><td><span class="ed-status '+statusClass(x.status)+'">'+esc(x.status)+'</span></td><td>'+x.revision+'</td><td><div class="ed-actions"><button class="btn ghost small" data-edit="'+x.id+'">Editar</button><button class="btn ghost small" data-copy="'+x.id+'">Duplicar</button></div></td></tr>').join('')+'</tbody></table></div>';b.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>editor(rows.find(r=>r.id===x.dataset.edit)));b.querySelectorAll('[data-copy]').forEach(x=>x.onclick=()=>{duplicateQuestion(x.dataset.copy);shell();});};
  ['#edQ','#edAud','#edCat','#edDif','#edSt'].forEach(sel=>b.querySelector(sel).addEventListener(sel==='#edQ'?'input':'change',paint));b.querySelector('#edClear').onclick=()=>{['#edQ','#edAud','#edCat','#edDif','#edSt'].forEach(x=>b.querySelector(x).value='');paint();};b.querySelector('#edNew').onclick=()=>editor(blank());paint();
  function editor(row){
   const exists=listEditorialQuestions().some(x=>x.id===row.id),opts=[...(row.options||[])];while(opts.length<4)opts.push('');
   b.querySelector('#edEditor').innerHTML='<div class="ed-editor"><div class="ed-actions" style="justify-content:space-between"><h3>'+(exists?'Editar ':'Nova ')+esc(row.id)+'</h3><button class="btn ghost small" id="edClose">Fechar</button></div><form id="edForm"><div class="ed-grid"><label>ID<input name="id" value="'+esc(row.id)+'" '+(exists?'readonly':'')+'></label><label>Público<select name="audience"><option value="criancas" '+(row.audience==='criancas'?'selected':'')+'>Crianças</option><option value="adolescentes" '+(row.audience==='adolescentes'?'selected':'')+'>Adolescentes</option><option value="adultos" '+(row.audience==='adultos'?'selected':'')+'>Adultos</option></select></label><label>Categoria<select name="category">'+listCategories().map(c=>'<option value="'+c.id+'" '+(row.category===c.id?'selected':'')+'>'+esc(c.name)+'</option>').join('')+'</select></label><label>Dificuldade<select name="difficulty"><option value="facil" '+(row.difficulty==='facil'?'selected':'')+'>Fácil</option><option value="medio" '+(row.difficulty==='medio'?'selected':'')+'>Médio</option><option value="dificil" '+(row.difficulty==='dificil'?'selected':'')+'>Difícil</option></select></label><label class="ed-span2">Enunciado<textarea name="prompt" rows="3" required>'+esc(row.prompt)+'</textarea></label><div class="ed-span2"><strong>Alternativas — marque a correta</strong>'+opts.map((o,i)=>'<label style="display:grid;grid-template-columns:auto 1fr;gap:8px;align-items:center"><input type="radio" name="correct" value="'+i+'" '+(Number(row.correct)===i?'checked':'')+'><input name="option'+i+'" value="'+esc(o)+'" required></label>').join('')+'</div><label class="ed-span2">Explicação<textarea name="why" rows="3" required>'+esc(row.why||'')+'</textarea></label><label>Status<select name="status"><option '+(row.status==='Rascunho'?'selected':'')+'>Rascunho</option><option '+(row.status==='Em revisão'?'selected':'')+'>Em revisão</option>'+(canHomologate()?'<option '+(row.status==='Homologado'?'selected':'')+'>Homologado</option>':'')+'<option '+(row.status==='Arquivado'?'selected':'')+'>Arquivado</option></select></label></div><div class="ed-actions" style="justify-content:flex-end;margin-top:12px"><button class="btn primary">Salvar revisão</button></div></form></div>';
   b.querySelector('#edClose').onclick=()=>b.querySelector('#edEditor').innerHTML='';
   b.querySelector('#edForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries()),options=[0,1,2,3].map(i=>String(d['option'+i]||'').trim());try{saveEditorialQuestion({id:d.id,audience:d.audience,category:d.category,difficulty:d.difficulty,prompt:d.prompt,options,correct:Number(d.correct),why:d.why,status:d.status});shell();}catch(err){alert(err.message);}};
  }
 }
 function categoryView(b){
  const cats=listCategories(),counts={};listEditorialQuestions().forEach(q=>counts[q.category]=(counts[q.category]||0)+1);
  b.innerHTML='<div class="ed-panel"><div class="ed-note"><strong>Categorias editoriais.</strong> Organizam banco, relatórios e experiências futuras.</div><div class="cat-grid" style="margin-top:10px">'+cats.map(c=>'<article class="cat-card"><strong>'+esc(c.name)+'</strong><small>'+esc(c.id)+' • '+(counts[c.id]||0)+' questão(ões)</small></article>').join('')+'</div><form id="catForm" class="ed-grid" style="margin-top:12px"><label>Nova categoria<input name="name" required></label><label><span><input name="active" type="checkbox" checked> Ativa</span></label><div><button class="btn primary">Adicionar</button></div></form></div>';b.querySelector('#catForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());try{saveCategory({name:d.name,active:!!d.active});shell();}catch(err){alert(err.message);}};
 }
 function reviewView(b){
  const rows=listEditorialQuestions().filter(x=>['Rascunho','Em revisão'].includes(x.status));
  b.innerHTML='<div class="ed-panel"><div class="ed-note"><strong>Fluxo:</strong> Rascunho → Em revisão → Homologado. Apenas Gestor homologa conteúdo para uso.</div><div class="ed-table-wrap"><table class="ed-table"><thead><tr><th>ID</th><th>Questão</th><th>Status</th><th>Ações</th></tr></thead><tbody>'+rows.map(x=>'<tr><td>'+esc(x.id)+'</td><td>'+esc(x.prompt)+'</td><td><span class="ed-status '+statusClass(x.status)+'">'+esc(x.status)+'</span></td><td><div class="ed-actions">'+(x.status==='Rascunho'?'<button class="btn ghost small" data-review="'+x.id+'">Enviar à revisão</button>':'')+(canHomologate()?'<button class="btn primary small" data-ok="'+x.id+'">Homologar</button>':'')+'<button class="btn danger small" data-archive="'+x.id+'">Arquivar</button></div></td></tr>').join('')+'</tbody></table></div></div>';b.querySelectorAll('[data-review]').forEach(x=>x.onclick=()=>{setQuestionStatus(x.dataset.review,'Em revisão');shell();});b.querySelectorAll('[data-ok]').forEach(x=>x.onclick=()=>{if(confirm('Homologar e liberar para jogos/avaliações?')){setQuestionStatus(x.dataset.ok,'Homologado');shell();}});b.querySelectorAll('[data-archive]').forEach(x=>x.onclick=()=>{setQuestionStatus(x.dataset.archive,'Arquivado');shell();});
 }
 function historyView(b){
  const hist=listEditorialHistory();b.innerHTML='<div class="ed-panel"><div class="ed-actions" style="justify-content:space-between"><div><h3>Histórico editorial</h3><small>'+hist.length+' registro(s)</small></div><button class="btn danger" id="edResetBase">Restaurar banco-base</button></div><div style="display:grid;gap:8px;margin-top:10px">'+hist.slice(0,500).map(h=>'<article class="cat-card"><strong>'+esc(h.type)+' • '+esc(h.questionId)+' • rev. '+h.revision+'</strong><small>'+new Date(h.at).toLocaleString('pt-BR')+' • '+esc(h.userName||'Sistema')+' • '+esc(h.status||'')+'</small></article>').join('')+'</div></div>';b.querySelector('#edResetBase').onclick=()=>{if(!canHomologate()){alert('Somente Gestor pode restaurar o banco-base.');return;}if(confirm('Descartar alterações editoriais locais e restaurar o banco-base?')){resetEditorialToBase();shell();}};
 }
 shell();
}
