import {ACCESS_PERMISSIONS,ACCESS_LABELS,accessDb,loadAccess,listAccessTenants,permissionAllowed,refreshOnlineAccess} from '../core/cloudAccess.js?v=1';
import {getCloudTenantId,setCloudTenantId} from '../cloudGateway.js?v=6';
import {getCloudUser,getCloudAuth,isCloudEmulatorMode} from '../core/cloudAuth.js?v=3';
import {cloudConfig} from '../cloudConfig.js?v=3';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function renderCloudUsers(host){
 host.innerHTML='<p>Carregando usuários online...</p>';
 try{
  const me=await loadAccess();if(!permissionAllowed(me,'users.manage'))throw new Error('Sem permissão para gerenciar usuários.');
  const {db,fs}=await accessDb(),tenants=await listAccessTenants();let mode='members';
  host.innerHTML=`<section class="admin-module"><h2>Usuários online e permissões</h2><p>Contas Firebase, com acesso por cliente e escola. Bloquear o vínculo impede o acesso aos dados desse cliente.</p><label>Cliente<select id="cuTenant">${tenants.map(t=>`<option value="${esc(t.id)}" ${t.id===getCloudTenantId()?'selected':''}>${esc(t.name||t.id)}</option>`).join('')}</select></label>${me.owner?'<label><input type="checkbox" id="cuStaff"> Equipe administrativa do sistema (vários clientes)</label>':''}${me.owner?'<button class="btn ghost" type="button" id="cuCreateClient">Cadastrar cliente online</button>':''}<div id="cuRows"></div><hr><h3>Conceder ou editar acesso</h3><form id="cuForm"><div class="form-grid"><label>UID da conta Firebase<input name="uid" required></label><label>Nome<input name="name" required maxlength="180"></label><label>E-mail<input name="email" type="email" required></label><label>Perfil<select name="role"><option value="PERSONALIZADO">Permissões selecionadas</option><option value="GESTOR">Gestor completo deste cliente</option></select></label></div><label><input name="active" type="checkbox" checked> Acesso ativo</label><div id="cuScope"></div><fieldset><legend>Permissões</legend>${ACCESS_PERMISSIONS.map(p=>`<label style="display:block"><input type="checkbox" data-permission="${p}"> ${esc(ACCESS_LABELS[p])}</label>`).join('')}</fieldset><p>Consultar cadastros acompanha cadastrar, editar ou excluir. Agenda e relatórios desta etapa exigem acesso a todas as escolas do cliente. A emissão de certificados pode ser liberada para escolas específicas.</p><button class="btn primary" type="submit">Salvar acesso</button></form><details><summary>Criar conta Firebase</summary><p>Crie a conta e depois conceda o vínculo acima. Uma conta sem vínculo não recebe acesso aos dados.</p><form id="cuAccount"><label>E-mail<input name="email" type="email" required></label><label>Senha inicial<input name="password" type="password" minlength="8" required autocomplete="new-password"></label><button class="btn" type="submit">Criar conta</button></form><p>Contas já existentes: copie o UID em Firebase Authentication → Usuários. Nenhuma senha é gravada no Firestore.</p></details><p id="cuMessage" role="status"></p></section>`;
  const qs=s=>host.querySelector(s),form=qs('#cuForm'),message=qs('#cuMessage');
  if(qs('#cuCreateClient'))qs('#cuCreateClient').onclick=async()=>{const name=prompt('Nome do cliente / organização:');if(!name?.trim())return;try{const a=await loadAccess();if(!a.owner)throw new Error('Apenas o administrador do sistema cadastra clientes.');const id='client-'+crypto.randomUUID();await fs.setDoc(fs.doc(db,'tenants',id),{name:name.trim(),type:'CLIENTE',createdBy:a.uid,createdAt:fs.serverTimestamp(),updatedAt:fs.serverTimestamp()});await renderCloudUsers(host);}catch(e){message.textContent=e.message;}};
  async function draw(){
   const tenantId=qs('#cuTenant').value;setCloudTenantId(tenantId);await refreshOnlineAccess();const access=await loadAccess();if(!permissionAllowed(access,'users.manage'))throw new Error('Você não pode gerenciar usuários desse cliente.');
   const snap=await fs.getDocsFromServer(fs.collection(db,...(mode==='staff'?['platformStaff']:['tenants',tenantId,'members'])));
   const rows=snap.docs.map(d=>({id:d.id,...d.data()}));qs('#cuRows').innerHTML='<h3>Acessos cadastrados</h3>'+rows.map(r=>`<p><strong>${esc(r.name||r.email||r.id)}</strong> — ${esc(r.email)} — ${r.active?'Ativo':'Bloqueado'} <button type="button" class="btn ghost" data-edit="${esc(r.id)}">Editar</button></p>`).join('');
   const schools=mode==='members'?await fs.getDocsFromServer(fs.collection(db,'tenants',tenantId,'schools')):null;
   qs('#cuScope').innerHTML=mode==='staff'?`<label><input name="allClients" type="checkbox"> Todos os clientes atuais e futuros</label>${tenants.map(t=>`<label style="display:block"><input data-client="${esc(t.id)}" type="checkbox"> ${esc(t.name||t.id)}</label>`).join('')}`:`<label><input name="allSchools" type="checkbox" checked> Todas as escolas do cliente</label>${schools.docs.filter(d=>!d.data().deletedAt).map(d=>`<label style="display:block"><input data-school="${esc(d.id)}" type="checkbox"> ${esc(d.data().nome)}</label>`).join('')}`;
   form.reset();form.elements.role.disabled=mode==='staff';
   host.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>{const r=rows.find(x=>x.id===button.dataset.edit);for(const k of ['uid','name','email','role'])form.elements[k].value=r[k]|| (k==='uid'?r.id:k==='role'?'PERSONALIZADO':'');form.elements.active.checked=r.active===true;if(mode==='staff'){form.elements.allClients.checked=r.allClients===true;host.querySelectorAll('[data-client]').forEach(i=>i.checked=r.tenantIds?.includes(i.dataset.client));}else{form.elements.allSchools.checked=r.allSchools!==false;host.querySelectorAll('[data-school]').forEach(i=>i.checked=r.schoolIds?.includes(i.dataset.school));}host.querySelectorAll('[data-permission]').forEach(i=>i.checked=r.permissions?.includes(i.dataset.permission)||r.role==='GESTOR');message.textContent='Editando '+(r.name||r.email||r.id);});
  }
  qs('#cuTenant').onchange=()=>draw().catch(e=>message.textContent=e.message);if(qs('#cuStaff'))qs('#cuStaff').onchange=e=>{mode=e.target.checked?'staff':'members';draw().catch(e=>message.textContent=e.message);};
  form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;try{const user=await getCloudUser(),tenantId=qs('#cuTenant').value,data=Object.fromEntries(new FormData(form)),uid=data.uid.trim();if(!uid||uid.includes('/'))throw new Error('UID inválido.');if(uid===user.uid)throw new Error('Use outro administrador para alterar seu próprio acesso.');const access=await loadAccess();if(!permissionAllowed(access,'users.manage')||mode==='staff'&&!access.owner)throw new Error('Sem permissão.');let permissions=[...host.querySelectorAll('[data-permission]:checked')].map(i=>i.dataset.permission);if(permissions.some(p=>['education.create','education.update','education.delete'].includes(p))&&!permissions.includes('education.read'))permissions.push('education.read');const common={uid,name:data.name.trim(),email:data.email.trim().toLowerCase(),active:!!data.active,permissions,updatedBy:user.uid,updatedAt:fs.serverTimestamp()};const batch=fs.writeBatch(db);
   if(mode==='staff'){batch.set(fs.doc(db,'platformStaff',uid),{...common,allClients:!!data.allClients,tenantIds:[...host.querySelectorAll('[data-client]:checked')].map(i=>i.dataset.client),role:'PERSONALIZADO'});}
   else{const role=data.role||'PERSONALIZADO',row={...common,tenantId,role,allSchools:role==='GESTOR'||!!data.allSchools,schoolIds:[...host.querySelectorAll('[data-school]:checked')].map(i=>i.dataset.school)};if(!row.allSchools&&!row.schoolIds.length)throw new Error('Selecione ao menos uma escola.');if(role==='GESTOR')row.permissions=[...ACCESS_PERMISSIONS];batch.set(fs.doc(db,'tenants',tenantId,'members',uid),row);batch.set(fs.doc(db,'memberships',uid+'_'+tenantId),row);}
   await batch.commit();await draw();message.textContent='Acesso salvo online.';
  }catch(err){message.textContent='Não foi possível salvar: '+err.message;}finally{button.disabled=false;}};
  qs('#cuAccount').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;let app;try{const a=await loadAccess();if(!permissionAllowed(a,'users.manage'))throw new Error('Sem permissão.');const data=new FormData(e.target),[apps,auths]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js')]);app=apps.initializeApp((await getCloudAuth()).app.options,'create-account-'+crypto.randomUUID());const auth=auths.getAuth(app);if(isCloudEmulatorMode())auths.connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});await auths.setPersistence(auth,auths.inMemoryPersistence);const cred=await auths.createUserWithEmailAndPassword(auth,data.get('email'),data.get('password'));form.elements.uid.value=cred.user.uid;form.elements.email.value=cred.user.email;message.textContent='Conta criada. UID preenchido. Defina escolas e permissões e clique em Salvar acesso.';await auths.signOut(auth);e.target.reset();}catch(err){message.textContent='Não foi possível criar: '+err.message;}finally{if(app){const apps=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js');await apps.deleteApp(app);}button.disabled=false;}};
  await draw();
 }catch(e){host.textContent='Não foi possível abrir usuários online: '+e.message;}
}
