const words=[
{word:'TRANSITO',clue:'Espaço de convivência e circulação de pessoas e veículos.',row:1,col:2,dir:'H'},
{word:'RESPEITO',clue:'Valor essencial para uma convivência segura.',row:1,col:3,dir:'V'},
{word:'SEGURANCA',clue:'Objetivo principal da educação para o trânsito.',row:3,col:3,dir:'H'},
{word:'PEDESTRE',clue:'Pessoa que se desloca a pé.',row:5,col:2,dir:'H'},
{word:'CINTO',clue:'Equipamento de proteção obrigatório no veículo.',row:7,col:0,dir:'H'},
{word:'SEMAFORO',clue:'Sinal luminoso que organiza os fluxos.',row:0,col:11,dir:'V'}
];
const clean=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z]/g,'');
export function openCruzadas(dialog,host,onFinish){
 let solved=new Set(),attempts=0;
 const cells=new Map(),starts=new Map();
 words.forEach((w,wi)=>{[...w.word].forEach((ch,i)=>{const r=w.row+(w.dir==='V'?i:0),c=w.col+(w.dir==='H'?i:0),k=`${r}-${c}`;if(!cells.has(k))cells.set(k,{r,c,letter:ch,words:[]});cells.get(k).words.push(wi);});starts.set(`${w.row}-${w.col}`,wi+1);});
 const grid=()=>{let html='';for(let r=0;r<8;r++)for(let c=0;c<12;c++){const k=`${r}-${c}`,cell=cells.get(k);html+=cell?`<label class="cw-cell" data-cell="${k}">${starts.has(k)?`<span>${starts.get(k)}</span>`:''}<input maxlength="1" inputmode="text" autocomplete="off" aria-label="Linha ${r+1}, coluna ${c+1}" data-r="${r}" data-c="${c}"></label>`:`<span class="cw-cell block"></span>`;}return html;};
 const clueList=()=>words.map((w,i)=>`<button type="button" class="cw-clue ${solved.has(i)?'solved':''}" data-clue="${i}"><span>${i+1}</span><div><strong>${w.dir==='H'?'Horizontal':'Vertical'}</strong><p>${w.clue}</p></div><b>${solved.has(i)?'✓':'Conferir'}</b></button>`).join('');
 const render=()=>{host.innerHTML=`<section class="game crossword-game"><div class="crossword-hero"><img src="assets/games/palavras_cruzadas_do_transito.webp?v=7" alt=""><div><p class="eyebrow">PALAVRAS CRUZADAS DO TRÂNSITO</p><h2>Complete a grade pelas pistas</h2><p>Cada letra correta ajuda a formar outras palavras.</p></div></div><div class="crossword-layout"><div class="crossword-board" id="cwBoard">${grid()}</div><div class="crossword-clues">${clueList()}</div></div><div class="game-score crossword-score"><span>Concluídas: <strong id="crossCount">${solved.size}/${words.length}</strong></span><span>Tentativas: <strong id="crossAttempts">${attempts}</strong></span><button class="btn ghost" id="crossHelp">💡 Mostrar uma letra</button></div></section>`;
  host.querySelectorAll('.cw-cell input').forEach(inp=>{inp.addEventListener('input',()=>{inp.value=clean(inp.value).slice(-1);if(inp.value){const all=[...host.querySelectorAll('.cw-cell input')],idx=all.indexOf(inp);all[idx+1]?.focus();}});inp.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!inp.value){const all=[...host.querySelectorAll('.cw-cell input')],idx=all.indexOf(inp);all[idx-1]?.focus();}});});
  host.querySelectorAll('[data-clue]').forEach(b=>b.onclick=()=>check(+b.dataset.clue));
  host.querySelector('#crossHelp').onclick=help;
 };
 const getInput=(r,c)=>host.querySelector(`[data-r="${r}"][data-c="${c}"]`);
 const check=i=>{if(solved.has(i))return;attempts++;const w=words[i];let ok=true;[...w.word].forEach((ch,n)=>{const r=w.row+(w.dir==='V'?n:0),c=w.col+(w.dir==='H'?n:0),inp=getInput(r,c);if(clean(inp?.value||'')!==ch)ok=false;});if(ok){solved.add(i);[...w.word].forEach((ch,n)=>{const r=w.row+(w.dir==='V'?n:0),c=w.col+(w.dir==='H'?n:0),inp=getInput(r,c);if(inp){inp.value=ch;inp.closest('.cw-cell').classList.add('correct');}});host.querySelector(`[data-clue="${i}"]`)?.classList.add('solved');host.querySelector(`[data-clue="${i}"] b`).textContent='✓';host.querySelector('#crossCount').textContent=`${solved.size}/${words.length}`;if(solved.size===words.length)setTimeout(finish,450);}else{[...w.word].forEach((ch,n)=>{const r=w.row+(w.dir==='V'?n:0),c=w.col+(w.dir==='H'?n:0),inp=getInput(r,c);if(inp&&inp.value)inp.closest('.cw-cell').classList.add('wrong');setTimeout(()=>inp?.closest('.cw-cell')?.classList.remove('wrong'),500);});}host.querySelector('#crossAttempts').textContent=attempts;};
 const help=()=>{const options=words.map((w,i)=>({w,i})).filter(x=>!solved.has(x.i));if(!options.length)return;const pick=options[Math.floor(Math.random()*options.length)],w=pick.w;const blanks=[...w.word].map((ch,n)=>({ch,n})).filter(({n})=>{const r=w.row+(w.dir==='V'?n:0),c=w.col+(w.dir==='H'?n:0);return !getInput(r,c)?.value;});if(!blanks.length)return;const b=blanks[Math.floor(Math.random()*blanks.length)],r=w.row+(w.dir==='V'?b.n:0),c=w.col+(w.dir==='H'?b.n:0),inp=getInput(r,c);inp.value=b.ch;inp.closest('.cw-cell').classList.add('hint');setTimeout(()=>inp.closest('.cw-cell').classList.remove('hint'),900);};
 const finish=()=>{const score=Math.max(100,1200-attempts*30);const s=JSON.parse(localStorage.getItem('mobiliza.results')||'{"games":0,"correct":0,"answers":0,"best":0,"streak":0}');s.games=(s.games||0)+1;s.correct=(s.correct||0)+words.length;s.answers=(s.answers||0)+attempts;s.best=Math.max(s.best||0,score);localStorage.setItem('mobiliza.results',JSON.stringify(s));onFinish?.();host.innerHTML=`<section class="game"><div class="result-trophy">✏️</div><h2>Palavras concluídas!</h2><p>${score} pontos em ${attempts} tentativa(s).</p><button class="btn primary" id="crossAgain">Jogar novamente</button></section>`;host.querySelector('#crossAgain').onclick=()=>openCruzadas(dialog,host,onFinish);};
 render();if(!dialog.open)dialog.showModal();
}