import {loadEducation,educationRows} from '../core/educationRepository.js?v=1';
import {getCloudTenantId} from '../cloudGateway.js?v=6';
import {getCloudUser} from '../core/cloudAuth.js?v=3';
import {qrSvg} from '../core/qr.js?v=1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function fitCertificateName(font,text,maxSize,maxWidth){let size=maxSize;while(size>8&&font.widthOfTextAtSize(text,size)>maxWidth)size-=.5;if(font.widthOfTextAtSize(text,size)>maxWidth)throw new Error('Nome muito longo: aumente a largura do campo ou diminua a fonte.');return size;}
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open('mobiliza-certificate-models',1);req.onupgradeneeded=()=>req.result.createObjectStore('models');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function savedModels(scope){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('models'),r=tx.objectStore('models').getAll();r.onsuccess=()=>resolve(r.result.filter(x=>x.scope===scope));r.onerror=()=>reject(r.error);});}finally{db.close();}}
async function storeModel(model){const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction('models','readwrite');tx.objectStore('models').put(model,model.scope+'|'+model.name);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
async function imageFile(file){if(!file)return '';if(!['image/png','image/jpeg'].includes(file.type)||file.size>5*1024*1024)throw new Error('Use uma imagem PNG ou JPG de até 5 MB.');return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file);});}
async function qrPng(payload){const blob=new Blob([qrSvg(payload,{scale:10})],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);try{const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url;});const c=document.createElement('canvas');c.width=c.height=500;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,500,500);ctx.drawImage(img,0,0,500,500);return c.toDataURL('image/png');}finally{URL.revokeObjectURL(url);}}
export async function certificatePdf(PDFLib,model,people,details,makeQr=qrPng){
 const doc=await PDFLib.PDFDocument.create(),font=await doc.embedFont(PDFLib.StandardFonts.HelveticaBold),regular=await doc.embedFont(PDFLib.StandardFonts.Helvetica);
 const embed=async data=>data.startsWith('data:image/png')?doc.embedPng(data):doc.embedJpg(data);
 const bg=model.background?await embed(model.background):null,crest=model.crest?await embed(model.crest):null,logo=model.logo?await embed(model.logo):null;
 const records=[];
 for(const person of people){
  const page=doc.addPage([841.89,595.28]),width=page.getWidth(),height=page.getHeight();
  if(bg){const scale=Math.min(width/bg.width,height/bg.height);page.drawImage(bg,{x:(width-bg.width*scale)/2,y:(height-bg.height*scale)/2,width:bg.width*scale,height:bg.height*scale});}
  else {page.drawText(details.title||'CERTIFICADO',{x:70,y:height-130,size:34,font});page.drawText('Certificamos a participação de',{x:70,y:height-205,size:20,font:regular});page.drawText(details.activity||'Atividade educativa',{x:70,y:height-335,size:20,font:regular});}
  const placeImage=(asset,x,y,w)=>{if(!asset)return;const drawW=width*w/100,drawH=drawW*asset.height/asset.width;page.drawImage(asset,{x:width*x/100-drawW/2,y:height*(1-y/100)-drawH/2,width:drawW,height:drawH});};
  placeImage(crest,model.crestX,model.crestY,model.crestWidth);placeImage(logo,model.logoX,model.logoY,model.logoWidth);
  const name=person.nome||person.name,size=fitCertificateName(font,name,model.fontSize,width*model.nameWidth/100),nameWidth=font.widthOfTextAtSize(name,size);
  page.drawText(name,{x:width*model.nameX/100-nameWidth/2,y:height*(1-model.nameY/100)-size*.35,size,font});
  const code='MEC-'+crypto.randomUUID().replaceAll('-','').slice(0,16).toUpperCase();
  if(model.showQr){const qr=await doc.embedPng(await makeQr('MEC|'+code));const qWidth=width*model.qrWidth/100;page.drawImage(qr,{x:width*model.qrX/100-qWidth/2,y:height*(1-model.qrY/100)-qWidth/2,width:qWidth,height:qWidth});page.drawText(code,{x:width*model.qrX/100-regular.widthOfTextAtSize(code,6)/2,y:height*(1-model.qrY/100)-qWidth/2-9,size:6,font:regular});}
  records.push({studentId:person.id,name,code,schoolId:details.schoolId,classId:details.classId,activity:details.activity,date:details.date});
 }
 return {bytes:await doc.save(),records};
}
export async function renderCustomCertificates(host){
 host.innerHTML='<p>Carregando escolas, turmas e alunos do Firestore...</p>';
 try{
  await loadEducation();const user=await getCloudUser(),tenant=getCloudTenantId(),scope=tenant+'|'+user.uid;
  let model={name:'Meu modelo',background:'',crest:'',logo:'',nameX:50,nameY:44.5,nameWidth:58,fontSize:24,crestX:15,crestY:12,crestWidth:10,logoX:85,logoY:12,logoWidth:10,qrX:90,qrY:43,qrWidth:6,showQr:true},models=await savedModels(scope),working=false;
  const numbers=(prefix,label,fields)=>`<fieldset style="border:1px solid #d7e2eb;border-radius:10px;padding:10px"><legend>${label}</legend>${fields.map(([key,title])=>`<label>${title}<input data-param="${key}" type="number" value="${model[key]}" min="${key==='fontSize'?8:0}" max="${key==='fontSize'?60:100}" step="0.5"></label>`).join('')}</fieldset>`;
  host.innerHTML=`<section class="admin-module"><h2>Certificados por escola e turma</h2><p>Selecione os alunos importados e envie sua arte. PNG ou JPG, até 5 MB. Os modelos salvos ficam neste navegador, separados por conta e organização.</p><div class="form-grid"><label>Escola<select id="ccSchool"><option value="">Selecione</option>${educationRows('escolas').map(s=>`<option value="${esc(s.id)}">${esc(s.nome)}</option>`).join('')}</select></label><label>Turma<select id="ccClass"><option value="">Selecione a escola</option></select></label><label>Atividade<input id="ccActivity" value="Agente de Trânsito Mirim"></label><label>Data da participação<input id="ccDate" type="date"></label></div><div id="ccStudents"></div><hr><div class="form-grid"><label>Modelo salvo<select id="ccSaved"><option value="">Novo modelo</option>${models.map((m,i)=>`<option value="${i}">${esc(m.name)}</option>`).join('')}</select></label><label>Nome do modelo<input id="ccModelName" value="Meu modelo"></label><label>Arte de fundo<input id="ccBackground" type="file" accept="image/png,image/jpeg"></label><label>Brasão<input id="ccCrest" type="file" accept="image/png,image/jpeg"></label><label>Logotipo<input id="ccLogo" type="file" accept="image/png,image/jpeg"></label></div><p>Se a arte já contém brasão, logotipo e assinaturas, envie apenas o fundo. Posições em porcentagem da página A4 horizontal; Y é medido a partir do topo.</p><div class="form-grid">${numbers('', 'Nome do aluno',[['nameX','Centro X (%)'],['nameY','Centro Y (%)'],['nameWidth','Largura (%)'],['fontSize','Fonte (pt)']])}${numbers('', 'Brasão',[['crestX','Centro X (%)'],['crestY','Centro Y (%)'],['crestWidth','Largura (%)']])}${numbers('', 'Logotipo',[['logoX','Centro X (%)'],['logoY','Centro Y (%)'],['logoWidth','Largura (%)']])}${numbers('', 'QR Code',[['qrX','Centro X (%)'],['qrY','Centro Y (%)'],['qrWidth','Largura (%)']])}</div><label><input id="ccQr" type="checkbox" checked> Incluir código e QR de identificação</label><p>O QR contém um código de identificação. Esta versão ainda não oferece consulta pública de autenticidade ou histórico compartilhado de emissões.</p><div class="form-actions"><button class="btn ghost" id="ccClear" type="button">Limpar imagens</button><button class="btn ghost" id="ccStore" type="button">Salvar modelo neste navegador</button><button class="btn ghost" id="ccPreview" type="button">Prévia PDF do primeiro aluno</button><button class="btn primary" id="ccEmit" type="button">PDF dos alunos selecionados</button></div><p id="ccMessage" role="status" aria-live="polite"></p><iframe id="ccFrame" title="Prévia do certificado" style="width:100%;height:420px;border:1px solid #d7e2eb" hidden></iframe></section>`;
  const qs=s=>host.querySelector(s),msg=qs('#ccMessage');let previewUrl='';
  const ensureScope=()=>{if(getCloudTenantId()!==tenant)throw new Error('A organização mudou. Abra o módulo novamente.');};
  function syncModel(){model.name=qs('#ccModelName').value.trim();if(!model.name)throw new Error('Informe o nome do modelo.');for(const field of host.querySelectorAll('[data-param]')){const value=Number(field.value);if(!field.value||!Number.isFinite(value)||value<Number(field.min)||value>Number(field.max))throw new Error('Confira os campos de posição e fonte.');model[field.dataset.param]=value;}if(!model.nameWidth||!model.qrWidth||!model.crestWidth||!model.logoWidth)throw new Error('As larguras devem ser maiores que zero.');model.showQr=qs('#ccQr').checked;return {...model};}
  qs('#ccSchool').onchange=()=>{const classes=educationRows('turmas').filter(t=>t.idEscola===qs('#ccSchool').value);qs('#ccClass').innerHTML='<option value="">Selecione</option>'+classes.map(t=>`<option value="${esc(t.id)}">${esc(t.nome)} — ${esc(t.turno)} — ${esc(t.anoLetivo||'')}</option>`).join('');qs('#ccStudents').innerHTML='';};
  qs('#ccClass').onchange=()=>{const students=educationRows('alunos').filter(a=>a.idTurma===qs('#ccClass').value).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));qs('#ccStudents').innerHTML=`<p>${students.length} aluno(s). Marque apenas os participantes que receberão certificado.</p><button class="btn ghost" id="ccAll" type="button">Selecionar todos</button><div style="max-height:220px;overflow:auto">${students.map(a=>`<label style="display:block"><input type="checkbox" data-student="${esc(a.id)}"> ${esc(a.nome)}</label>`).join('')}</div>`;qs('#ccAll').onclick=()=>host.querySelectorAll('[data-student]').forEach(i=>i.checked=true);};
  for(const [selector,key] of [['#ccBackground','background'],['#ccCrest','crest'],['#ccLogo','logo']])qs(selector).onchange=async e=>{try{model[key]=await imageFile(e.target.files[0]);msg.textContent='Imagem carregada. Abra a prévia para conferir.';}catch(e){msg.textContent=e.message;}};
  qs('#ccClear').onclick=()=>{model.background=model.crest=model.logo='';for(const id of ['#ccBackground','#ccCrest','#ccLogo'])qs(id).value='';msg.textContent='Imagens removidas do modelo atual.';};
  qs('#ccSaved').onchange=()=>{if(qs('#ccSaved').value==='')return;model={...models[Number(qs('#ccSaved').value)]};qs('#ccModelName').value=model.name;host.querySelectorAll('[data-param]').forEach(i=>i.value=model[i.dataset.param]);qs('#ccQr').checked=model.showQr;msg.textContent='Modelo carregado.';};
  qs('#ccStore').onclick=async()=>{try{ensureScope();await storeModel({...syncModel(),scope});models=await savedModels(scope);qs('#ccSaved').innerHTML='<option value="">Novo modelo</option>'+models.map((m,i)=>`<option value="${i}">${esc(m.name)}</option>`).join('');msg.textContent='Modelo salvo neste navegador.';}catch(e){msg.textContent='Não foi possível salvar: '+e.message;}};
  async function generate(preview){if(working)return;working=true;msg.textContent='Preparando PDF...';let temporaryUrl='';try{ensureScope();const config=syncModel(),schoolId=qs('#ccSchool').value,classId=qs('#ccClass').value;if(!schoolId||!classId)throw new Error('Selecione escola e turma.');const ids=new Set([...host.querySelectorAll('[data-student]:checked')].map(i=>i.dataset.student));let people=educationRows('alunos').filter(a=>a.idTurma===classId&&ids.has(a.id));if(!people.length)throw new Error('Selecione ao menos um aluno.');if(preview)people=people.slice(0,1);const PDFLib=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');const result=await certificatePdf(PDFLib,config,people,{schoolId,classId,title:'CERTIFICADO',activity:qs('#ccActivity').value,date:qs('#ccDate').value});ensureScope();const blob=new Blob([result.bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob);temporaryUrl=url;if(preview){if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=url;qs('#ccFrame').src=url;qs('#ccFrame').hidden=false;temporaryUrl='';msg.textContent='Prévia gerada. Confira o nome, as imagens e o QR antes de emitir.';}else{const a=document.createElement('a');a.href=url;a.download='certificados-turma.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);temporaryUrl='';msg.textContent=people.length+' certificado(s) gerado(s) no PDF. Emissão ainda sem histórico compartilhado.';}}catch(e){msg.textContent='Não foi possível gerar: '+(e.message||e);}finally{if(temporaryUrl)URL.revokeObjectURL(temporaryUrl);working=false;}}
  qs('#ccPreview').onclick=()=>generate(true);qs('#ccEmit').onclick=()=>generate(false);
 }catch(e){host.innerHTML='<p class="form-error">'+esc(e.message)+'</p><p>Conecte o Firestore no painel e tente novamente.</p>';}
}
