import {putEvidenceFile,getEvidenceFile,deleteEvidenceFile,blobToDataUrl,estimateEvidenceStorage} from '../core/evidenceStore.js?v=2';

const K='mobiliza.admin.';
const read=k=>{try{return JSON.parse(localStorage.getItem(K+k)||'[]')}catch{return[]}};
const write=(k,v)=>{localStorage.setItem(K+k,JSON.stringify(v));window.dispatchEvent(new CustomEvent('mobiliza-data-change',{detail:{entity:k}}));};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const fmtBytes=n=>{n=Number(n)||0;if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const byId=(k,id)=>read(k).find(x=>x.id===id);
const impacts=()=>read('impactos'),evidences=()=>read('evidencias');

function css(){
 if(document.getElementById('impacto-v1'))return;
 const s=document.createElement('style');s.id='impacto-v1';s.textContent=`
 .imp-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 16px}.imp-tab{border:1px solid #c9dce7;background:#fff;color:#214d68;padding:10px 13px;border-radius:11px;font-weight:900;cursor:pointer}.imp-tab.active{background:#0b719f;color:#fff;border-color:#0b719f}
 .imp-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin:12px 0 16px}.imp-kpi{background:#fff;border:1px solid #d9e7ee;border-radius:14px;padding:14px}.imp-kpi strong{display:block;font-size:1.4rem;color:#0b678f}.imp-kpi span{font-size:.78rem;color:#6e8491}
 .imp-panel{background:#fff;border:1px solid #d7e5ed;border-radius:16px;padding:16px}.imp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.imp-grid label,.imp-panel>label{display:grid;gap:5px;font-size:.84rem;font-weight:800;color:#234e68}.imp-panel input,.imp-panel select,.imp-panel textarea{width:100%;padding:10px;border:1px solid #c9dce7;border-radius:10px;font:inherit;color:#173f60;background:#fff}.imp-panel textarea{resize:vertical}.imp-span2{grid-column:1/-1}.imp-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;margin-top:14px}
 .imp-help{padding:11px 13px;border-left:4px solid #0b78a8;background:#eef8fc;border-radius:10px;margin:10px 0;line-height:1.45}.imp-warn{border-left-color:#e2a200;background:#fff6d8}.imp-danger{border-left-color:#c54141;background:#fff0f0}
 .mat-table{width:100%;border-collapse:collapse;margin-top:8px}.mat-table th,.mat-table td{padding:7px;border-bottom:1px solid #e6edf2;text-align:left}.mat-table input{padding:7px}.mat-table th{font-size:.75rem;color:#6c8290}
 .ev-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:12px}.ev-card{border:1px solid #dbe7ed;border-radius:13px;padding:10px;background:#fff;display:grid;gap:8px}.ev-thumb{height:150px;border-radius:10px;background:#eef3f6;display:grid;place-items:center;overflow:hidden}.ev-thumb img{width:100%;height:100%;object-fit:cover}.ev-thumb .file-icon{font-size:2rem}.ev-meta{font-size:.76rem;color:#6e8390}.ev-card select,.ev-card input{font-size:.8rem;padding:8px}.ev-status{display:inline-flex;padding:4px 7px;border-radius:999px;background:#edf3f6;color:#5c7180;font-size:.7rem;font-weight:900}.ev-status.public{background:#e3f6e8;color:#17683b}
 .report-preview{border:1px solid #d8e5ec;border-radius:15px;padding:18px;background:#fff}.report-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;border-bottom:3px solid #0b719f;padding-bottom:12px}.report-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.report-kpis div{border:1px solid #dce8ee;border-radius:11px;padding:10px}.report-kpis strong,.report-kpis span{display:block}.report-kpis strong{font-size:1.25rem;color:#0b688f}.report-section{margin-top:15px}.report-section h4{margin:0 0 6px;color:#173f60}.report-list{margin:0;padding-left:18px}.report-photo-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.report-photo-grid img{width:100%;height:150px;object-fit:cover;border-radius:9px}
 .ind-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ind-card{border:1px solid #dbe7ed;border-radius:14px;padding:14px;background:#fff}.ind-row{display:grid;grid-template-columns:1fr auto;gap:8px;padding:7px 0;border-bottom:1px solid #edf2f5}.ind-row:last-child{border-bottom:0}
 @media(max-width:900px){.imp-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.ev-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.report-kpis{grid-template-columns:repeat(2,1fr)}}
 @media(max-width:650px){.imp-grid,.ind-grid{grid-template-columns:1fr}.imp-span2{grid-column:auto}.ev-grid{grid-template-columns:1fr}.report-photo-grid{grid-template-columns:1fr}.report-kpis{grid-template-columns:1fr}.mat-table{font-size:.8rem}}
 `;document.head.appendChild(s);
}
function attendance(e){
 const students=Object.values(e?.presenca||{}).filter(Boolean).length;
 const external=read('inscricoes').filter(r=>r.idEvento===e?.id&&r.status==='Presente').reduce((s,r)=>s+(Number(r.quantidade)||1),0);
 return students+external;
}
function plannedMaterials(e){return (e?.materiais||[]).map(m=>({id:uid(),nome:m.nome||'',quantidade:Number(m.quantidade)||0,unidade:m.unidade||'un'}));}
function getImpact(eventId){return impacts().find(x=>x.eventId===eventId)||null;}
function saveImpact(row){
 const all=impacts(),i=all.findIndex(x=>x.eventId===row.eventId);row.updatedAt=new Date().toISOString();
 if(i>=0)all[i]=row;else{row.id=row.id||uid();row.createdAt=row.createdAt||new Date().toISOString();all.unshift(row)}write('impactos',all);return row;
}
function evaluationSummary(eventId){
 const plans=read('avaliacaoPlanos'),plan=plans.find(p=>p.eventId===eventId&&p.active!==false)||plans.find(p=>p.eventId===eventId);
 if(!plan)return null;const rows=read('avaliacoes').filter(r=>r.planId===plan.id),pre=rows.filter(r=>r.phase==='PRE'),pos=rows.filter(r=>r.phase==='POS');
 const avg=a=>a.length?Math.round(a.reduce((s,x)=>s+(Number(x.pct)||0),0)/a.length):0;
 const a=avg(pre),b=avg(pos),pairs=(plan.participants||[]).filter(p=>pre.some(x=>x.participantKey===p.key)&&pos.some(x=>x.participantKey===p.key)).length;
 return{pre:a,pos:b,delta:b-a,pairs,preCount:pre.length,posCount:pos.length};
}
function certificateCount(eventId){return read('certificados').filter(c=>c.eventId===eventId&&c.status!=='Revogado').length;}
function checklistPct(e){const c=e?.checklist||{},keys=['solicitante','local','equipe','materiais','equipamentos','transporte','participantes','comunicacao'];return Math.round(keys.filter(k=>c[k]).length/keys.length*100);}
function materialTotal(row){return(row?.materiaisDistribuidos||[]).reduce((s,m)=>s+(Number(m.quantidade)||0),0);}
function partnerList(row,e){const fromEvent=(e?.parceiros||[]).map(x=>typeof x==='string'?x:x.nome).filter(Boolean),extra=String(row?.parceirosTexto||'').split(',').map(x=>x.trim()).filter(Boolean);return[...new Set([...fromEvent,...extra])];}
function allMetrics(){
 const ev=read('eventos'),im=impacts(),evid=evidences();
 const reached=im.reduce((s,x)=>s+(Number(x.publicoTotal)||0),0),materials=im.reduce((s,x)=>s+materialTotal(x),0),closed=im.filter(x=>x.status==='Finalizado').length;
 const pending=ev.filter(e=>e.status==='Concluído'&&!im.some(x=>x.eventId===e.id&&x.status==='Finalizado')).length;
 return{events:ev.length,closed,pending,reached,materials,evidence:evid.length};
}
async function previewEvidenceCard(meta,card){
 const holder=card.querySelector('.ev-thumb');try{const item=await getEvidenceFile(meta.id);if(!item?.blob)return;if((item.type||'').startsWith('image/')){const url=URL.createObjectURL(item.blob),img=document.createElement('img');img.src=url;img.onload=()=>URL.revokeObjectURL(url);holder.innerHTML='';holder.appendChild(img);}}catch{}
}
function reportModel(e,row){
 const evals=evaluationSummary(e.id),partners=partnerList(row,e),certs=certificateCount(e.id),evs=evidences().filter(x=>x.eventId===e.id),authorized=evs.filter(x=>x.authorization==='Autorizada para divulgação institucional');
 return{event:e,impact:row,attendance:attendance(e),publicTotal:Number(row?.publicoTotal)||attendance(e),materials:row?.materiaisDistribuidos||[],materialsTotal:materialTotal(row),partners,evals,certs,evidenceCount:evs.length,authorizedCount:authorized.length,checklist:checklistPct(e),authorized};
}
function reportHtml(m,photos=[]){
 const e=m.event,r=m.impact||{},delta=m.evals?.delta??null;
 return `<div class="report-preview"><div class="report-head"><div><p class="eyebrow">MOBILIZA EDUCA • RELATÓRIO FINAL DA AÇÃO</p><h2>${esc(e.nome||'Atividade educativa')}</h2><p>${fmtDate(e.dataInicio||e.data)} • ${esc(e.horaInicio||'')}–${esc(e.horaFim||'')} • ${esc(e.local||'Local a definir')}</p></div><span class="ev-status ${r.status==='Finalizado'?'public':''}">${esc(r.status||'Rascunho')}</span></div>
 <div class="report-kpis"><div><strong>${m.publicTotal}</strong><span>Público alcançado</span></div><div><strong>${m.materialsTotal}</strong><span>Materiais distribuídos</span></div><div><strong>${m.evidenceCount}</strong><span>Evidências anexadas</span></div><div><strong>${m.certs}</strong><span>Certificados emitidos</span></div></div>
 <div class="report-section"><h4>Identificação</h4><p><strong>Tipo:</strong> ${esc(e.tipo||'—')} • <strong>Público:</strong> ${esc(e.publico||'—')} • <strong>Responsável:</strong> ${esc(r.responsavelFechamento||e.responsavel||'—')}</p><p><strong>Solicitante:</strong> ${esc(e.contato||e.email||'—')} • <strong>Parceiros:</strong> ${esc(m.partners.join(', ')||'—')}</p></div>
 <div class="report-section"><h4>Resultados e impacto</h4><p>${esc(r.resumoResultados||'Sem resumo registrado.')}</p>${m.evals?`<p><strong>Avaliação pedagógica:</strong> pré ${m.evals.pre}% • pós ${m.evals.pos}% • variação <strong class="${delta>0?'av-pos':delta<0?'av-neg':''}">${delta>0?'+':''}${delta} p.p.</strong> • ${m.evals.pairs} pares comparáveis.</p>`:''}</div>
 <div class="report-section"><h4>Materiais distribuídos</h4>${m.materials.length?'<ul class="report-list">'+m.materials.map(x=>`<li>${esc(x.nome)} — ${Number(x.quantidade)||0} ${esc(x.unidade||'un')}</li>`).join('')+'</ul>':'<p>Não informado.</p>'}</div>
 <div class="report-section"><h4>Ocorrências, encaminhamentos e observações</h4><p><strong>Ocorrências:</strong> ${esc(r.ocorrencias||'Nenhuma registrada.')}</p><p><strong>Encaminhamentos:</strong> ${esc(r.encaminhamentos||'—')}</p><p><strong>Observações:</strong> ${esc(r.observacoes||'—')}</p></div>
 <div class="report-section"><h4>Comprovação</h4><p>Checklist pré-evento: ${m.checklist}% • Evidências: ${m.evidenceCount} • Imagens autorizadas para divulgação institucional: ${m.authorizedCount}</p>${photos.length?'<div class="report-photo-grid">'+photos.map(x=>`<figure><img src="${x.dataUrl}" alt=""><figcaption>${esc(x.description||x.name)}</figcaption></figure>`).join('')+'</div>':''}</div>
 <div class="report-section"><small>Relatório gerado em ${new Date().toLocaleString('pt-BR')}. A inclusão de imagens respeita o status de autorização registrado em cada evidência.</small></div></div>`;
}
async function authorizedPhotos(m,limit=6){
 const out=[];for(const meta of m.authorized){if(out.length>=limit)break;try{const item=await getEvidenceFile(meta.id);if(item?.blob&&(item.type||'').startsWith('image/'))out.push({...meta,dataUrl:await blobToDataUrl(item.blob)});}catch{}}
 return out;
}
async function printFinalReport(m){
 const photos=await authorizedPhotos(m,6),w=window.open('','_blank');if(!w)return;
 const body=reportHtml(m,photos);
 w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Relatório final • Mobiliza Educa</title><style>body{font-family:Arial;color:#173f60;padding:28px}.report-preview{max-width:1000px;margin:auto}.report-head{display:flex;justify-content:space-between;border-bottom:4px solid #0b719f;padding-bottom:12px}.report-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:16px 0}.report-kpis div{border:1px solid #dbe5eb;border-radius:10px;padding:10px}.report-kpis strong,.report-kpis span{display:block}.report-kpis strong{font-size:22px;color:#0b688f}.report-section{margin-top:16px}.report-photo-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.report-photo-grid img{width:100%;height:170px;object-fit:cover;border-radius:8px}figure{margin:0}figcaption{font-size:11px;color:#697e8b}.ev-status{font-weight:bold}.eyebrow{font-size:11px;font-weight:bold;letter-spacing:.08em}@media print{body{padding:0}.report-preview{max-width:none}}</style></head><body>${body}<script>window.onload=function(){setTimeout(function(){window.print()},400)}<\/script></body></html>`);w.document.close();
}

export function renderEvidenciasImpacto(host){
 css();let tab='fechamento',eventId=read('eventos').sort((a,b)=>String(b.dataInicio||b.data||'').localeCompare(String(a.dataInicio||a.data||'')))[0]?.id||'';
 const draw=async()=>{
  const e=byId('eventos',eventId),row=e?getImpact(e.id):null,m=allMetrics(),eventEvs=e?evidences().filter(x=>x.eventId===e.id):[];
  host.innerHTML=`<section class="admin-module"><p class="eyebrow">EVIDÊNCIAS & IMPACTO • v1.0</p><h2>Comprovação da ação educativa</h2><p class="admin-intro">Feche cada atendimento com dados reais de alcance, materiais, parceiros, arquivos autorizados e resultados pedagógicos.</p>
  <div class="imp-kpis"><div class="imp-kpi"><strong>${m.closed}</strong><span>ações finalizadas</span></div><div class="imp-kpi"><strong>${m.pending}</strong><span>concluídas sem fechamento</span></div><div class="imp-kpi"><strong>${m.reached}</strong><span>pessoas alcançadas</span></div><div class="imp-kpi"><strong>${m.materials}</strong><span>materiais distribuídos</span></div><div class="imp-kpi"><strong>${m.evidence}</strong><span>evidências armazenadas</span></div></div>
  <div class="imp-panel"><div class="imp-grid"><label>Evento / ação<select id="impEvent">${read('eventos').sort((a,b)=>String(b.dataInicio||b.data||'').localeCompare(String(a.dataInicio||a.data||''))).map(x=>`<option value="${x.id}" ${x.id===eventId?'selected':''}>${fmtDate(x.dataInicio||x.data)} • ${esc(x.nome)}</option>`).join('')}</select></label><div><span class="ev-status ${row?.status==='Finalizado'?'public':''}">${esc(row?.status||'Sem fechamento')}</span><p style="margin:5px 0 0;color:#6d8290">Presença registrada: <strong>${e?attendance(e):0}</strong> • Evidências: <strong>${eventEvs.length}</strong></p></div></div></div>
  <div class="imp-tabs"><button class="imp-tab ${tab==='fechamento'?'active':''}" data-imptab="fechamento">✅ Fechamento</button><button class="imp-tab ${tab==='evidencias'?'active':''}" data-imptab="evidencias">📷 Evidências</button><button class="imp-tab ${tab==='relatorio'?'active':''}" data-imptab="relatorio">📑 Relatório final</button><button class="imp-tab ${tab==='indicadores'?'active':''}" data-imptab="indicadores">📊 Indicadores</button></div><div id="impBody"></div></section>`;
  host.querySelector('#impEvent').onchange=x=>{eventId=x.target.value;draw();};host.querySelectorAll('[data-imptab]').forEach(b=>b.onclick=()=>{tab=b.dataset.imptab;draw();});
  const body=host.querySelector('#impBody');if(!e){body.innerHTML='<div class="imp-panel">Cadastre um evento antes de registrar impacto.</div>';return;}
  if(tab==='fechamento')renderClose(body,e,row);else if(tab==='evidencias')await renderEvidence(body,e,row);else if(tab==='relatorio')await renderReport(body,e,row);else renderIndicators(body);
 };
 function renderClose(body,e,row){
  const base=row||{eventId:e.id,status:'Rascunho',publicoNominal:attendance(e),publicoExtra:0,publicoTotal:attendance(e),materiaisDistribuidos:plannedMaterials(e),parceirosTexto:'',responsavelFechamento:e.responsavel||'',resumoResultados:'',ocorrencias:'',encaminhamentos:'',observacoes:''};
  body.innerHTML=`<form class="imp-panel" id="impactForm"><div class="imp-help"><strong>Público nominal</strong> vem automaticamente das presenças e check-ins. Use “público adicional” apenas para ações abertas em que nem todos foram identificados individualmente.</div><div class="imp-grid"><label>Público nominal<input id="impNominal" value="${attendance(e)}" disabled></label><label>Público adicional / não nominal<input name="publicoExtra" type="number" min="0" value="${Number(base.publicoExtra)||0}"></label><label>Responsável pelo fechamento<input name="responsavelFechamento" value="${esc(base.responsavelFechamento||'')}"></label><label>Status<select name="status"><option ${base.status!=='Finalizado'?'selected':''}>Rascunho</option><option ${base.status==='Finalizado'?'selected':''}>Finalizado</option></select></label><label class="imp-span2">Parceiros adicionais, separados por vírgula<input name="parceirosTexto" value="${esc(base.parceirosTexto||'')}"></label><label class="imp-span2">Resumo dos resultados<textarea name="resumoResultados" rows="4">${esc(base.resumoResultados||'')}</textarea></label><label class="imp-span2">Ocorrências durante a ação<textarea name="ocorrencias" rows="3">${esc(base.ocorrencias||'')}</textarea></label><label class="imp-span2">Encaminhamentos / próximos passos<textarea name="encaminhamentos" rows="3">${esc(base.encaminhamentos||'')}</textarea></label><label class="imp-span2">Observações gerais<textarea name="observacoes" rows="3">${esc(base.observacoes||'')}</textarea></label></div>
  <h3>Materiais efetivamente distribuídos</h3><div style="overflow:auto"><table class="mat-table"><thead><tr><th>Material</th><th>Quantidade</th><th>Unidade</th><th></th></tr></thead><tbody id="matBody"></tbody></table></div><div class="imp-actions" style="justify-content:flex-start"><button type="button" class="btn ghost" id="addMat">+ Material</button></div>
  <div class="imp-actions"><button class="btn primary">Salvar fechamento</button></div></form>`;
  let mats=(base.materiaisDistribuidos||[]).map(x=>({...x}));const mb=body.querySelector('#matBody');
  const paintMats=()=>{mb.innerHTML=mats.map((m,i)=>`<tr><td><input data-mat-name="${i}" value="${esc(m.nome||'')}"></td><td><input data-mat-qty="${i}" type="number" min="0" value="${Number(m.quantidade)||0}"></td><td><input data-mat-unit="${i}" value="${esc(m.unidade||'un')}"></td><td><button type="button" class="btn danger small" data-mat-del="${i}">×</button></td></tr>`).join('')||'<tr><td colspan="4">Nenhum material informado.</td></tr>';mb.querySelectorAll('[data-mat-del]').forEach(b=>b.onclick=()=>{mats.splice(Number(b.dataset.matDel),1);paintMats();});};
  paintMats();body.querySelector('#addMat').onclick=()=>{mats.push({id:uid(),nome:'',quantidade:0,unidade:'un'});paintMats();};
  body.querySelector('#impactForm').onsubmit=ev=>{ev.preventDefault();mb.querySelectorAll('[data-mat-name]').forEach(x=>{const i=Number(x.dataset.matName);mats[i].nome=x.value.trim();mats[i].quantidade=Math.max(0,Number(mb.querySelector('[data-mat-qty="'+i+'"]').value)||0);mats[i].unidade=mb.querySelector('[data-mat-unit="'+i+'"]').value.trim()||'un';});mats=mats.filter(x=>x.nome);const data=Object.fromEntries(new FormData(ev.target).entries()),nom=attendance(e);const saved={...(row||{}),eventId:e.id,...data,publicoNominal:nom,publicoExtra:Math.max(0,Number(data.publicoExtra)||0),publicoTotal:nom+Math.max(0,Number(data.publicoExtra)||0),materiaisDistribuidos:mats};if(saved.status==='Finalizado'&&!saved.responsavelFechamento.trim()){alert('Informe o responsável pelo fechamento antes de finalizar.');return;}saveImpact(saved);alert(saved.status==='Finalizado'?'Fechamento finalizado.':'Rascunho salvo.');draw();};
 }
 async function renderEvidence(body,e,row){
  const evs=evidences().filter(x=>x.eventId===e.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),storage=await estimateEvidenceStorage().catch(()=>({usage:0,quota:0}));
  body.innerHTML=`<div class="imp-panel"><div class="imp-help imp-warn"><strong>Autorização de imagem:</strong> anexar o arquivo não significa autorização para divulgação. O padrão é “Uso interno/documental”. Somente itens marcados como autorizados podem entrar como imagem no relatório institucional.</div><div class="imp-grid"><label>Categoria<select id="evCategory"><option>Foto</option><option>Lista de presença</option><option>Ofício / documento</option><option>Material produzido</option><option>Outro</option></select></label><label>Autorização / uso<select id="evAuth"><option>Uso interno/documental</option><option>Autorizada para divulgação institucional</option><option>Sem autorização de imagem</option></select></label><label class="imp-span2">Descrição do lote<input id="evDescription" placeholder="Ex.: atividade prática na faixa de pedestres"></label><label class="imp-span2">Arquivos<input id="evFiles" type="file" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt"></label></div><div class="imp-actions"><button class="btn primary" id="evUpload">Adicionar evidências</button></div><p class="ev-meta">Armazenamento do navegador: ${fmtBytes(storage.usage)} usado${storage.quota?' de '+fmtBytes(storage.quota):''}. Limite por arquivo neste módulo: 12 MB.</p><div id="evGrid" class="ev-grid"></div></div>`;
  const grid=body.querySelector('#evGrid');
  const paint=()=>{grid.innerHTML=evs.map(x=>`<article class="ev-card" data-evidence-card="${x.id}"><div class="ev-thumb"><span class="file-icon">${(x.mime||'').startsWith('image/')?'🖼️':'📄'}</span></div><strong>${esc(x.name)}</strong><div class="ev-meta">${esc(x.category)} • ${fmtBytes(x.size)} • ${new Date(x.createdAt).toLocaleString('pt-BR')}</div><input data-ev-desc="${x.id}" value="${esc(x.description||'')}" placeholder="Descrição"><select data-ev-auth="${x.id}"><option ${x.authorization==='Uso interno/documental'?'selected':''}>Uso interno/documental</option><option ${x.authorization==='Autorizada para divulgação institucional'?'selected':''}>Autorizada para divulgação institucional</option><option ${x.authorization==='Sem autorização de imagem'?'selected':''}>Sem autorização de imagem</option></select><span class="ev-status ${x.authorization==='Autorizada para divulgação institucional'?'public':''}">${esc(x.authorization)}</span><div class="imp-actions"><button class="btn ghost small" data-ev-save="${x.id}">Salvar</button><button class="btn ghost small" data-ev-open="${x.id}">Abrir</button><button class="btn danger small" data-ev-del="${x.id}">Excluir</button></div></article>`).join('')||'<p>Nenhuma evidência anexada a este evento.</p>';grid.querySelectorAll('[data-evidence-card]').forEach(card=>previewEvidenceCard(evs.find(x=>x.id===card.dataset.evidenceCard),card));bindCards();};
  const bindCards=()=>{grid.querySelectorAll('[data-ev-save]').forEach(b=>b.onclick=()=>{const x=evs.find(v=>v.id===b.dataset.evSave);x.description=grid.querySelector('[data-ev-desc="'+x.id+'"]').value.trim();x.authorization=grid.querySelector('[data-ev-auth="'+x.id+'"]').value;x.updatedAt=new Date().toISOString();const all=evidences(),i=all.findIndex(z=>z.id===x.id);if(i>=0)all[i]=x;write('evidencias',all);draw();});grid.querySelectorAll('[data-ev-open]').forEach(b=>b.onclick=async()=>{try{const item=await getEvidenceFile(b.dataset.evOpen);if(!item?.blob){alert('Arquivo não encontrado neste navegador.');return;}const url=URL.createObjectURL(item.blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(err){alert(err.message);}});grid.querySelectorAll('[data-ev-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir esta evidência e o arquivo armazenado?'))return;await deleteEvidenceFile(b.dataset.evDel).catch(()=>{});write('evidencias',evidences().filter(x=>x.id!==b.dataset.evDel));draw();});};
  paint();
  body.querySelector('#evUpload').onclick=async()=>{const files=[...body.querySelector('#evFiles').files];if(!files.length){alert('Selecione ao menos um arquivo.');return;}const category=body.querySelector('#evCategory').value,authorization=body.querySelector('#evAuth').value,description=body.querySelector('#evDescription').value.trim(),all=evidences();let ok=0;for(const file of files){if(file.size>12*1024*1024){alert(file.name+' excede 12 MB e não foi anexado.');continue;}const id='EVD-'+uid(),meta={id,eventId:e.id,name:file.name,mime:file.type||'application/octet-stream',size:file.size,category,authorization,description,createdAt:new Date().toISOString()};try{await putEvidenceFile(id,file);all.unshift(meta);ok++;}catch(err){alert('Falha ao armazenar '+file.name+': '+err.message);}}if(ok){write('evidencias',all);alert(ok+' evidência(s) adicionada(s).');draw();}};
 }
 async function renderReport(body,e,row){
  const m=reportModel(e,row||{eventId:e.id,status:'Rascunho',publicoTotal:attendance(e),materiaisDistribuidos:[]}),photos=await authorizedPhotos(m,6);
  body.innerHTML=`<div class="imp-actions"><button class="btn ghost" id="reportRefresh">Atualizar</button><button class="btn primary" id="reportPrint">🖨 Imprimir / Salvar PDF</button></div>${reportHtml(m,photos)}`;
  body.querySelector('#reportRefresh').onclick=()=>draw();body.querySelector('#reportPrint').onclick=()=>printFinalReport(m);
 }
 function renderIndicators(body){
  const all=impacts(),events=read('eventos'),m=allMetrics(),partners=new Map(),materials=new Map();
  for(const r of all){const e=events.find(x=>x.id===r.eventId);for(const p of partnerList(r,e))partners.set(p,(partners.get(p)||0)+1);for(const mat of r.materiaisDistribuidos||[])materials.set(mat.nome,(materials.get(mat.nome)||0)+(Number(mat.quantidade)||0));}
  const pRows=[...partners.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10),mRows=[...materials.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10);
  body.innerHTML=`<div class="imp-help"><strong>Indicadores operacionais:</strong> estes números são formados pelos fechamentos registrados. Ações sem fechamento final continuam sinalizadas como pendentes.</div><div class="ind-grid"><div class="ind-card"><h3>Resumo acumulado</h3><div class="ind-row"><span>Ações finalizadas</span><strong>${m.closed}</strong></div><div class="ind-row"><span>Fechamentos pendentes</span><strong>${m.pending}</strong></div><div class="ind-row"><span>Público alcançado</span><strong>${m.reached}</strong></div><div class="ind-row"><span>Materiais distribuídos</span><strong>${m.materials}</strong></div><div class="ind-row"><span>Evidências</span><strong>${m.evidence}</strong></div></div><div class="ind-card"><h3>Parceiros mais presentes</h3>${pRows.map(x=>`<div class="ind-row"><span>${esc(x[0])}</span><strong>${x[1]} ação(ões)</strong></div>`).join('')||'<p>Sem parceiros consolidados.</p>'}</div><div class="ind-card"><h3>Materiais mais distribuídos</h3>${mRows.map(x=>`<div class="ind-row"><span>${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join('')||'<p>Sem materiais consolidados.</p>'}</div><div class="ind-card"><h3>Qualidade do fechamento</h3><div class="ind-row"><span>Eventos cadastrados</span><strong>${m.events}</strong></div><div class="ind-row"><span>% finalizados</span><strong>${m.events?Math.round(m.closed/m.events*100):0}%</strong></div><div class="ind-row"><span>Evidências por ação finalizada</span><strong>${m.closed?(m.evidence/m.closed).toFixed(1):'0'}</strong></div></div></div>`;
 }
 draw();
}
