const cards=[
['🛑','PARE'],['🚦','SEMÁFORO'],['🚲','BICICLETA'],['🚸','PEDESTRE'],['🦺','SEGURANÇA'],['🚗','VEÍCULO'],['30','VELOCIDADE'],['🔒','CINTO']
];
function save(correct,moves,score){const s=JSON.parse(localStorage.getItem('mobiliza.results')||'{"games":0,"correct":0,"answers":0,"best":0,"streak":0}');s.games=(s.games||0)+1;s.correct=(s.correct||0)+correct;s.answers=(s.answers||0)+moves;s.best=Math.max(s.best||0,score);localStorage.setItem('mobiliza.results',JSON.stringify(s));}
export function openMemoria(dialog,host,onFinish){
 let deck=[...cards,...cards].map((x,i)=>({id:i,key:x[1],face:x[0],label:x[1]})).sort(()=>Math.random()-.5),open=[],matched=new Set(),moves=0,start=Date.now(),lock=false,timerId=null;
 const render=()=>{host.innerHTML=`<section class="game memory-game"><div class="game-cover game-cover-memoria"></div><div class="game-score"><span>Jogadas: <strong id="memoryMoves">${moves}</strong></span><span>Pares: <strong id="memoryPairs">${matched.size/2}/${cards.length}</strong></span><span>Tempo: <strong id="memoryTime">0s</strong></span></div><div class="memory-grid">${deck.map(c=>`<button class="memory-card ${matched.has(c.id)?'matched':''}" data-card="${c.id}" aria-label="Carta"><span class="memory-back">M</span><span class="memory-front"><b>${c.face}</b><small>${c.label}</small></span></button>`).join('')}</div></section>`;host.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>flip(+b.dataset.card));tick();};
 const tick=()=>{clearTimeout(timerId);const el=host.querySelector('#memoryTime');if(el)el.textContent=Math.floor((Date.now()-start)/1000)+'s';if(el&&matched.size<deck.length)timerId=setTimeout(tick,1000);};
 const flip=id=>{if(lock||matched.has(id)||open.includes(id))return;const b=host.querySelector(`[data-card="${id}"]`);b.classList.add('open');open.push(id);if(open.length===2){moves++;host.querySelector('#memoryMoves').textContent=moves;const [a,c]=open.map(i=>deck.find(x=>x.id===i));if(a.key===c.key){matched.add(a.id);matched.add(c.id);open=[];host.querySelector('#memoryPairs').textContent=`${matched.size/2}/${cards.length}`;if(matched.size===deck.length)setTimeout(finish,500);}else{lock=true;setTimeout(()=>{open.forEach(i=>host.querySelector(`[data-card="${i}"]`)?.classList.remove('open'));open=[];lock=false;},850);}}};
 const finish=()=>{clearTimeout(timerId);const seconds=Math.floor((Date.now()-start)/1000),score=Math.max(100,2000-moves*50-seconds*4);save(cards.length,moves,score);onFinish?.();host.innerHTML=`<section class="game memory-result"><div class="result-trophy">🧠</div><h2>Memória concluída!</h2><p>${moves} jogadas • ${seconds}s • ${score} pontos</p><button class="btn primary" id="memoryAgain">Jogar novamente</button></section>`;host.querySelector('#memoryAgain').onclick=()=>openMemoria(dialog,host,onFinish);};
 render();dialog.showModal();
}