const questions=[
{q:'Ao se aproximar de uma faixa de pedestres ocupada, o condutor deve:',a:['Acelerar para passar primeiro','Reduzir e dar passagem com segurança','Buzinar para o pedestre sair','Desviar pela contramão'],correct:1,why:'A travessia deve ser protegida com velocidade compatível e prioridade ao pedestre.'},
{q:'Usar o celular ao dirigir aumenta o risco porque:',a:['Divide a atenção entre a via e outra tarefa','Melhora o tempo de reação','Só atrapalha em rodovias','Reduz a velocidade automaticamente'],correct:0,why:'A distração visual, manual e cognitiva reduz percepção e tempo disponível para reagir.'},
{q:'O cinto de segurança deve ser usado:',a:['Só pelo motorista','Só nos bancos dianteiros','Por todos os ocupantes','Somente em rodovias'],correct:2,why:'Todos os ocupantes precisam estar protegidos, inclusive no banco traseiro.'},
{q:'Em área escolar, a atitude mais segura é:',a:['Acelerar para liberar a via','Adequar a velocidade e redobrar atenção','Parar sobre a faixa','Usar a buzina continuamente'],correct:1,why:'Áreas escolares exigem atenção reforçada, velocidade adequada e respeito às travessias.'},
{q:'Ao ultrapassar um ciclista, é correto:',a:['Passar muito perto','Manter distância lateral segura e só ultrapassar com visibilidade','Buzinar até ele sair','Ultrapassar em curva'],correct:1,why:'Distância lateral e visibilidade reduzem conflitos e protegem usuários vulneráveis.'},
{q:'No semáforo amarelo, o condutor deve:',a:['Acelerar sempre','Reduzir e parar com segurança quando possível','Ignorar a sinalização','Parar no meio do cruzamento'],correct:1,why:'O amarelo indica atenção e transição. A decisão deve priorizar uma parada segura.'},
{q:'Ao atravessar a rua, o pedestre deve:',a:['Usar a faixa e observar os dois sentidos','Correr entre veículos','Olhar apenas para um lado','Usar o celular durante a travessia'],correct:0,why:'A faixa organiza a travessia, mas a observação e a atenção continuam indispensáveis.'},
{q:'Uma criança no veículo deve ser transportada:',a:['De qualquer forma se o trajeto for curto','Conforme as regras de retenção e segurança aplicáveis','No colo de um adulto','Sem cinto no banco traseiro'],correct:1,why:'Dispositivos e formas corretas de retenção reduzem o risco de lesões em colisões e frenagens.'},
{q:'Dirigir acima da velocidade adequada:',a:['Reduz a distância de parada','Aumenta tempo para reagir','Aumenta distância de parada e gravidade dos impactos','Não muda o risco'],correct:2,why:'Quanto maior a velocidade, maior a distância percorrida durante percepção, reação e frenagem.'},
{q:'Convivência segura no trânsito significa:',a:['Cada um defender seu espaço','Agir com previsibilidade, respeito e atenção aos mais vulneráveis','Priorizar apenas os veículos','Ignorar quem circula mais devagar'],correct:1,why:'Segurança viária depende de cooperação, previsibilidade, respeito e proteção dos usuários vulneráveis.'}
];
const ladder=[100,200,300,500,1000,2000,5000,10000,50000,100000];
const letters=['A','B','C','D'];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

function stats(correct,answers,score,streak){
 const s=JSON.parse(localStorage.getItem('mobiliza.results')||'{"games":0,"correct":0,"answers":0,"best":0,"streak":0}');
 s.games=(s.games||0)+1;s.correct=(s.correct||0)+correct;s.answers=(s.answers||0)+answers;s.best=Math.max(s.best||0,score);s.streak=Math.max(s.streak||0,streak);
 localStorage.setItem('mobiliza.results',JSON.stringify(s));
}
function ranking(name,score){
 const key='mobiliza.milhao.ranking',r=JSON.parse(localStorage.getItem(key)||'[]');
 r.push({name:name||'Jogador',score,date:new Date().toISOString()});
 r.sort((a,b)=>b.score-a.score);localStorage.setItem(key,JSON.stringify(r.slice(0,10)));return r.slice(0,10);
}
function beep(freq=660,dur=.08){
 try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.value=.04;o.connect(g);g.connect(c.destination);o.start();setTimeout(()=>{o.stop();c.close();},dur*1000);}catch{}
}
export function openMilhao(dialog,host,onFinish){
 let name='Jogador',i=0,score=0,pulos=2,cartas=1,plateia=1,time=30,timer=null,locked=false,selected=null,correctCount=0,bestStreak=0,streak=0,answers=0;
 const stop=()=>{if(timer){clearInterval(timer);timer=null;}};
 const openStart=()=>{stop();host.innerHTML=`<section class="game milhao milhao-start windows-look"><div class="milhao-rings"></div><div class="game-cover game-cover-milhao"></div><div class="milhao-start-copy"><p class="eyebrow">MOBILIZA EDUCA • DESAFIO PRINCIPAL</p><h2>Quiz do Milhão do Trânsito</h2><p>Responda 10 perguntas, avance na escala de pontuação e use suas ajudas no momento certo.</p><label class="player-name">Nome do jogador<input id="milhaoName" maxlength="40" value="${name==='Jogador'?'':name}" placeholder="Digite seu nome"></label><div class="milhao-rules"><span>⏱ 30 s</span><span>⏭ 2 pulos</span><span>🃏 1 cartas</span><span>👥 1 plateia</span></div><button class="btn primary big" id="milhaoStart">Começar desafio</button></div></section>`;host.querySelector('#milhaoStart').onclick=()=>{name=host.querySelector('#milhaoName').value.trim()||'Jogador';render();};};
 const ladderHtml=()=>ladder.map((v,n)=>`<span class="${n<i?'done':n===i?'current':''}"><small>${n+1}</small> ${v.toLocaleString('pt-BR')}</span>`).join('');
 const render=()=>{stop();time=30;locked=false;selected=null;const q=questions[i];host.innerHTML=`<section class="game milhao"><div class="milhao-top"><div><p class="eyebrow">QUIZ DO MILHÃO DO TRÂNSITO</p><h2>${name}</h2><p class="milhao-score">Pontuação: <strong>${score.toLocaleString('pt-BR')}</strong></p></div><div class="milhao-timer" id="milhaoTimer">30</div></div><div class="milhao-layout windows-layout"><div class="milhao-stage"><div class="milhao-brand-stage"><div class="milhao-logo-disc">SHOW<br><strong>DO MILHÃO</strong><small>DO TRÂNSITO</small></div></div><div class="milhao-question-wrap"><span>Pergunta ${i+1} de ${questions.length}</span><h2 class="milhao-question">${q.q}</h2></div><div class="quiz-options milhao-options">${q.a.map((x,n)=>`<button type="button" class="quiz-option" data-answer="${n}"><b>${letters[n]}</b><span>${x}</span></button>`).join('')}</div><div class="milhao-confirm" id="milhaoConfirm" hidden><span>Confirma a alternativa <strong id="confirmLetter"></strong>?</span><button class="btn primary" id="confirmYes">CONFIRMAR</button><button class="btn ghost" id="confirmNo">TROCAR</button></div><div class="milhao-aids"><button class="btn ghost" id="jump" ${pulos?'':'disabled'}>⏭ Pular <b>${pulos}</b></button><button class="btn ghost" id="cards" ${cartas?'':'disabled'}>🃏 Cartas <b>${cartas}</b></button><button class="btn ghost" id="audience" ${plateia?'':'disabled'}>👥 Plateia <b>${plateia}</b></button><button class="btn ghost" id="fullscreen">⛶ Telão</button></div><div id="feedback"></div></div><aside class="milhao-ladder">${ladderHtml()}</aside></div><div id="milhaoHelpOverlay" class="milhao-help-overlay"></div></section>`;
  const opts=[...host.querySelectorAll('[data-answer]')];
  opts.forEach(b=>b.onclick=()=>{if(locked||b.disabled)return;opts.forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=+b.dataset.answer;host.querySelector('#confirmLetter').textContent=letters[selected];host.querySelector('#milhaoConfirm').hidden=false;beep(520,.05);});
  host.querySelector('#confirmNo').onclick=()=>{selected=null;opts.forEach(x=>x.classList.remove('selected'));host.querySelector('#milhaoConfirm').hidden=true;};
  host.querySelector('#confirmYes').onclick=()=>{if(selected!==null)answer(selected);};
  host.querySelector('#jump').onclick=async()=>{if(!pulos||locked)return;locked=true;stop();pulos--;const o=host.querySelector('#milhaoHelpOverlay');o.className='milhao-help-overlay show';o.innerHTML='<div class="help-stage jump-help"><div class="jump-track"></div><div class="jump-car">🚗</div><div class="jump-cones">🚧 🚧 🚧</div><h3>PULO!</h3><p>Vamos trocar a pergunta.</p></div>';beep(430,.07);await sleep(1200);nextQuestion();};
  host.querySelector('#cards').onclick=async()=>{if(!cartas||locked)return;locked=true;stop();cartas--;const o=host.querySelector('#milhaoHelpOverlay');o.className='milhao-help-overlay show';o.innerHTML='<div class="help-stage cards-help"><div class="flying-cards"><span>🂠</span><span>🂠</span><span>🂠</span><span>🂠</span></div><h3>CARTAS</h3><p>Duas respostas incorretas serão eliminadas.</p></div>';await sleep(1000);o.classList.remove('show');const wrong=q.a.map((_,n)=>n).filter(n=>n!==q.correct).sort(()=>Math.random()-.5).slice(0,2);wrong.forEach(n=>{opts[n].disabled=true;opts[n].classList.add('eliminated');});host.querySelector('#cards').disabled=true;locked=false;timer=setInterval(()=>{time--;const t=host.querySelector('#milhaoTimer');if(t)t.textContent=time;if(time<=10)t?.classList.add('danger');if(time<=0){stop();locked=true;answers++;reveal(false,null,'⏱ Tempo esgotado.');}},1000);};
  host.querySelector('#audience').onclick=async()=>{if(!plateia||locked)return;locked=true;stop();plateia--;const o=host.querySelector('#milhaoHelpOverlay');o.className='milhao-help-overlay show';o.innerHTML='<div class="help-stage audience-help"><div class="crowd">🙋‍♀️ 🙋 🙋‍♂️ 🙋‍♀️ 🙋 🙋‍♂️</div><h3>PLATEIA</h3><p>Vamos ouvir a opinião do público.</p></div>';await sleep(1000);o.classList.remove('show');const base=[12,12,12,12];base[q.correct]=64;host.querySelector('#feedback').innerHTML=`<div class="audience-panel"><strong>👥 Ajuda da plateia</strong>${base.map((p,n)=>`<div class="audience-row"><span>${letters[n]}</span><i><b style="width:${p}%"></b></i><em>${p}%</em></div>`).join('')}</div>`;host.querySelector('#audience').disabled=true;locked=false;timer=setInterval(()=>{time--;const t=host.querySelector('#milhaoTimer');if(t)t.textContent=time;if(time<=10)t?.classList.add('danger');if(time<=0){stop();locked=true;answers++;reveal(false,null,'⏱ Tempo esgotado.');}},1000);};
  host.querySelector('#fullscreen').onclick=()=>{const el=dialog; if(!document.fullscreenElement)el.requestFullscreen?.();else document.exitFullscreen?.();};
  timer=setInterval(()=>{time--;const t=host.querySelector('#milhaoTimer');if(t)t.textContent=time;if(time<=10)t?.classList.add('danger');if(time<=0){stop();locked=true;answers++;reveal(false,null,'⏱ Tempo esgotado.');}},1000);
 };
 const answer=n=>{if(locked)return;locked=true;stop();answers++;const ok=n===questions[i].correct;if(ok){correctCount++;streak++;bestStreak=Math.max(bestStreak,streak);score=ladder[i];beep(880,.12);}else{streak=0;beep(180,.22);}reveal(ok,n,ok?'✅ Resposta correta!':'❌ Resposta incorreta.');};
 const reveal=(ok,n,title)=>{const q=questions[i],opts=[...host.querySelectorAll('[data-answer]')];opts.forEach((b,idx)=>{b.disabled=true;if(idx===q.correct)b.classList.add('correct');if(n===idx&&!ok)b.classList.add('wrong');});host.querySelector('#milhaoConfirm')?.setAttribute('hidden','');host.querySelector('#feedback').innerHTML=`<div class="quiz-feedback milhao-feedback"><strong>${title}</strong><p>${q.why}</p><button class="btn primary" id="milhaoNext">${ok&&i<questions.length-1?'Próxima pergunta':'Ver resultado'}</button></div>`;host.querySelector('#milhaoNext').onclick=()=>ok&&i<questions.length-1?nextQuestion():end();};
 const nextQuestion=()=>{if(i<questions.length-1){i++;render();}else end();};
 const end=()=>{stop();const rank=ranking(name,score);stats(correctCount,answers,score,bestStreak);host.innerHTML=`<section class="game milhao milhao-result"><div class="result-trophy">🏆</div><p class="eyebrow">RESULTADO FINAL</p><h2>${name}, você fez ${score.toLocaleString('pt-BR')} pontos</h2><p>${correctCount} acerto(s) em ${answers} resposta(s). Melhor sequência: ${bestStreak}.</p><div class="ranking-box"><h3>Ranking local</h3>${rank.slice(0,5).map((r,n)=>`<div><span>#${n+1} ${r.name}</span><strong>${r.score.toLocaleString('pt-BR')}</strong></div>`).join('')}</div><div class="hero-actions"><button class="btn primary" id="milhaoAgain">Jogar novamente</button><button class="btn ghost" id="milhaoClose">Encerrar</button></div></section>`;onFinish?.();host.querySelector('#milhaoAgain').onclick=()=>{i=0;score=0;pulos=2;cartas=1;plateia=1;correctCount=0;answers=0;streak=0;bestStreak=0;openStart();};host.querySelector('#milhaoClose').onclick=()=>dialog.close();};
 openStart();dialog.showModal();dialog.addEventListener('close',stop,{once:true});
}