const questions=[
{q:'Ao se aproximar de uma faixa de pedestres ocupada, o condutor deve:',a:['Acelerar antes que outro pedestre entre','Reduzir a velocidade e dar passagem com segurança','Buzinar para avisar que vai passar','Desviar pela contramão'],correct:1,why:'A prioridade do pedestre deve ser respeitada, com redução de velocidade e parada quando necessária.'},
{q:'O uso do celular ao dirigir aumenta o risco principalmente porque:',a:['Diminui o consumo de combustível','Divide a atenção entre a via e outra tarefa','Melhora o tempo de reação','Só atrapalha em rodovias'],correct:1,why:'A distração visual, manual e cognitiva reduz a percepção e aumenta o tempo de reação.'},
{q:'Por que o cinto no banco traseiro é indispensável?',a:['Apenas para evitar multa','Porque protege o ocupante e também quem está à frente','Somente em alta velocidade','Porque substitui outros dispositivos'],correct:1,why:'Sem cinto, um ocupante traseiro pode ser projetado com enorme força em uma colisão.'},
{q:'Em área escolar, a atitude mais segura é:',a:['Manter a mesma velocidade da avenida','Redobrar atenção e adequar a velocidade ao ambiente','Usar buzina continuamente','Parar sobre a faixa para observar'],correct:1,why:'Áreas escolares exigem velocidade compatível, atenção reforçada e respeito às travessias.'},
{q:'Ao perceber um ciclista à frente, o condutor deve:',a:['Passar o mais perto possível','Manter distância lateral segura e ultrapassar somente quando houver condições','Buzinar até ele sair da pista','Ultrapassar em curva sem visibilidade'],correct:1,why:'Distância, previsibilidade e ultrapassagem segura reduzem conflitos e protegem usuários vulneráveis.'}
];
const ladder=[100,200,300,500,1000];

export function openMilhao(dialog,host,onFinish){
 let i=0,score=0,pulos=2,cartas=1,plateia=1,time=30,timer=null,locked=false,eliminated=new Set();
 const stop=()=>{if(timer){clearInterval(timer);timer=null;}};
 const render=()=>{stop();time=30;locked=false;eliminated.clear();const q=questions[i];host.innerHTML=`<section class="game milhao"><div class="milhao-top"><div><p class="eyebrow">SHOW DO MILHÃO DO TRÂNSITO • ALPHA</p><h2>${score} pontos</h2></div><div class="milhao-timer" id="milhaoTimer" aria-label="Tempo restante">30</div></div><div class="milhao-progress">${ladder.map((v,n)=>`<span class="${n<i?'done':n===i?'current':''}">${v}</span>`).join('')}</div><h2 class="milhao-question">${q.q}</h2><div class="quiz-options">${q.a.map((x,n)=>`<button type="button" class="quiz-option" data-answer="${n}">${String.fromCharCode(65+n)}. ${x}</button>`).join('')}</div><div class="milhao-aids"><button class="btn ghost" id="jump" ${pulos?'':'disabled'}>⏭ Pular (${pulos})</button><button class="btn ghost" id="cards" ${cartas?'':'disabled'}>🃏 Cartas</button><button class="btn ghost" id="audience" ${plateia?'':'disabled'}>👥 Plateia</button></div><div id="feedback"></div></section>`;
 host.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(+b.dataset.answer)));
 host.querySelector('#jump').addEventListener('click',()=>{if(!pulos)return;pulos--;next(false);});
 host.querySelector('#cards').addEventListener('click',()=>{if(!cartas||locked)return;cartas--;const wrong=q.a.map((_,n)=>n).filter(n=>n!==q.correct).slice(0,2);wrong.forEach(n=>{eliminated.add(n);const b=host.querySelector(`[data-answer="${n}"]`);b.disabled=true;b.classList.add('eliminated');});host.querySelector('#cards').disabled=true;});
 host.querySelector('#audience').addEventListener('click',()=>{if(!plateia||locked)return;plateia--;const pct=q.a.map((_,n)=>n===q.correct?64:12);host.querySelector('#feedback').innerHTML=`<div class="quiz-feedback"><strong>👥 Opinião da plateia</strong><p>A: ${pct[0]}% • B: ${pct[1]}% • C: ${pct[2]}% • D: ${pct[3]}%</p></div>`;host.querySelector('#audience').disabled=true;});
 timer=setInterval(()=>{time--;const t=host.querySelector('#milhaoTimer');if(t)t.textContent=time;if(time<=0){stop();locked=true;finish(false,'⏱️ Tempo esgotado.');}},1000);
 };
 const answer=n=>{if(locked||eliminated.has(n))return;locked=true;stop();const q=questions[i],ok=n===q.correct;if(ok){score=ladder[i];finish(true,'✅ Resposta correta!');}else finish(false,'❌ Não foi desta vez.');};
 const finish=(ok,title)=>{const q=questions[i];host.querySelectorAll('[data-answer]').forEach((b,n)=>{b.disabled=true;if(n===q.correct)b.classList.add('correct');});host.querySelector('#feedback').innerHTML=`<div class="quiz-feedback"><strong>${title}</strong><p>${q.why}</p><button type="button" class="btn primary" id="milhaoNext">${ok&&i<questions.length-1?'Próxima pergunta':'Ver resultado'}</button></div>`;host.querySelector('#milhaoNext').addEventListener('click',()=>{if(ok&&i<questions.length-1){i++;render();}else end();});};
 const next=()=>{if(i<questions.length-1){i++;render();}else end();};
 const end=()=>{stop();host.innerHTML=`<section class="game milhao milhao-result"><p class="eyebrow">RESULTADO FINAL</p><h2>${score} pontos</h2><p>Você chegou até a faixa de <strong>${score||0}</strong> pontos.</p><p>Esta é a primeira versão web do jogo. As próximas evoluções incluirão animações, áudio, confirmação de resposta, modo operador e telão.</p><button class="btn primary" id="milhaoAgain">Jogar novamente</button></section>`;const s=JSON.parse(localStorage.getItem('mobiliza.results')||'{"games":0,"correct":0,"answers":0,"best":0,"streak":0}');s.games=(s.games||0)+1;s.answers=(s.answers||0)+Math.max(i+1,1);s.correct=(s.correct||0)+i+(score?1:0);s.best=Math.max(s.best||0,score);localStorage.setItem('mobiliza.results',JSON.stringify(s));onFinish?.();host.querySelector('#milhaoAgain').addEventListener('click',()=>openMilhao(dialog,host,onFinish));};
 render();dialog.showModal();dialog.addEventListener('close',stop,{once:true});
}