import {
 listTenants,listSubscriptions,activeTenantId,activeTenant,subscriptionFor,subscriptionHealth,tenantWorkspaceStats,
 createTenant,updateTenant,updateSubscription,switchTenant,deleteTenant,planSettings,savePlanSettings,
 projectedMrrCents,formatMoney
} from '../core/tenantRegistry.js?v=1';
import {PLAN_CATALOG,FEATURE_CATALOG} from '../core/saasContext.js?v=2';
import {recordAudit,currentUser} from '../core/accessControl.js?v=1';

const BILLING_EVENTS='mobiliza.platform.billingEvents';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const safe=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const fmtDate=v=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
const fmtDateTime=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const statusLabel=s=>({trialing:'Trial',active:'Ativa',past_due:'Pagamento pendente',suspended:'Suspensa',canceled:'Cancelada',trial_expired:'Trial expirado'}[s]||s||'—');
const statusClass=s=>s==='active'?'ok':s==='trialing'?'trial':s==='past_due'?'warn':['suspended','canceled','trial_expired'].includes(s)?'bad':'';
const planName=id=>PLAN_CATALOG.find(p=>p.id===id)?.name||id;
const billingEvents=()=>safe(BILLING_EVENTS,[]);
function recordBilling(tenantId,type,details=''){
 const t=listTenants().find(x=>x.id===tenantId),u=currentUser(),rows=billingEvents();
 rows.unshift({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),tenantId,tenantName:t?.name||'',type,details,at:new Date().toISOString(),user:u?.name||'Sistema'});
 localStorage.setItem(BILLING_EVENTS,JSON.stringify(rows.slice(0,3000)));
}
function addMonthsIso(base,n=1){const d=new Date(base||Date.now());d.setMonth(d.getMonth()+n);return d.toISOString();}
function percent(v,max){if(max==null)return 12;return Math.min(100,Math.round((Number(v)||0)/Math.max(1,max)*100));}

function css(){
 if(document.getElementById('platformCommercialCss'))return;
 const s=document.createElement('style');s.id='platformCommercialCss';
 s.textContent='.pc-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.pc-tab{border:1px solid #c9dce7;background:#fff;color:#214e69;padding:10px 13px;border-radius:11px;font-weight:900;cursor:pointer}.pc-tab.active{background:#0b709f;color:#fff}.pc-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin:12px 0}.pc-kpi,.pc-panel{background:#fff;border:1px solid #d9e7ee;border-radius:14px;padding:13px}.pc-kpi strong{display:block;font-size:1.3rem;color:#0a678f}.pc-kpi span{font-size:.72rem;color:#6f8491}.pc-note{padding:12px 14px;border-left:4px solid #0b78a8;background:#eef8fc;border-radius:10px;line-height:1.45}.pc-warn{border-left-color:#dda000;background:#fff6d9}.pc-toolbar,.pc-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center;justify-content:space-between}.pc-actions{justify-content:flex-start}.pc-table-wrap{overflow:auto}.pc-table{width:100%;border-collapse:collapse;font-size:.76rem;margin-top:10px}.pc-table th,.pc-table td{padding:9px;border-bottom:1px solid #e4edf2;text-align:left;vertical-align:top}.pc-table th{font-size:.64rem;text-transform:uppercase;color:#6b8190}.pc-table small{display:block;color:#748894;margin-top:2px}.pc-status{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:.68rem;font-weight:900;background:#edf4f7}.pc-status.ok{background:#e3f6e9;color:#176638}.pc-status.trial{background:#e9f1ff;color:#345c98}.pc-status.warn{background:#fff2d5;color:#855b05}.pc-status.bad{background:#ffe5e5;color:#8e2c2c}.pc-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.pc-grid label{display:grid;gap:5px;font-size:.8rem;font-weight:900;color:#315a72}.pc-grid input,.pc-grid select{padding:10px;border:1px solid #c8dce7;border-radius:10px;background:#fff}.pc-span2{grid-column:1/-1}.pc-editor{margin-top:12px;padding:14px;border:1px solid #cfe0e9;border-radius:14px;background:#f9fcfd}.plan-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.plan-card{border:1px solid #dce8ee;border-radius:13px;padding:13px;background:#fff}.plan-card h3{margin:0}.plan-card p{color:#708593;min-height:42px}.plan-price{font-size:1.25rem;color:#0b678f;font-weight:900}.pc-meter{height:7px;border-radius:999px;background:#e8eff3;overflow:hidden;margin:5px 0}.pc-meter span{display:block;height:100%;background:#0b78a8}.event-list{display:grid;gap:7px}.event-row{display:grid;grid-template-columns:150px 160px 1fr;gap:8px;padding:9px;border:1px solid #dfe9ee;border-radius:10px}.event-row small{color:#748894}@media(max-width:1050px){.pc-kpis{grid-template-columns:repeat(3,1fr)}.plan-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.pc-kpis,.pc-grid,.plan-grid{grid-template-columns:1fr}.pc-span2{grid-column:auto}.event-row{grid-template-columns:1fr}}';
 document.head.appendChild(s);
}

export function renderPlataformaComercial(host){
 css();let tab='clientes',editing=null;
 function shell(){
  const tenants=listTenants(),subs=listSubscriptions(),healths=tenants.map(t=>({t,h:subscriptionHealth(t.id),s:subscriptionFor(t.id)})),active=healths.filter(x=>x.h.status==='active').length,trials=healths.filter(x=>x.h.status==='trialing').length,attention=healths.filter(x=>['past_due','suspended','trial_expired'].includes(x.h.status)).length;
  host.innerHTML='<section class="admin-module"><p class="eyebrow">CONSOLE DO PROPRIETÁRIO • v1.0</p><h2>Clientes, assinaturas e planos</h2><p class="admin-intro">Administre organizações, trials, planos, limites e preparação do faturamento recorrente.</p>'+
   '<div class="pc-note pc-warn"><strong>Modo comercial de desenvolvimento.</strong> Os estados abaixo são locais e administrativos. Em produção, criação de clientes, pagamentos e liberação de recursos deverão ser confirmados pelo backend e pelo provedor de cobrança.</div>'+
   '<div class="pc-kpis"><div class="pc-kpi"><strong>'+tenants.length+'</strong><span>organizações</span></div><div class="pc-kpi"><strong>'+active+'</strong><span>assinaturas ativas</span></div><div class="pc-kpi"><strong>'+trials+'</strong><span>trials</span></div><div class="pc-kpi"><strong>'+attention+'</strong><span>exigem atenção</span></div><div class="pc-kpi"><strong>'+formatMoney(projectedMrrCents())+'</strong><span>MRR projetado configurado</span></div></div>'+
   '<div class="pc-tabs"><button class="pc-tab '+(tab==='clientes'?'active':'')+'" data-pctab="clientes">🏢 Clientes</button><button class="pc-tab '+(tab==='planos'?'active':'')+'" data-pctab="planos">💳 Planos e preços</button><button class="pc-tab '+(tab==='faturamento'?'active':'')+'" data-pctab="faturamento">🧾 Ciclo comercial</button></div><div id="pcBody"></div></section>';
  host.querySelectorAll('[data-pctab]').forEach(b=>b.onclick=()=>{tab=b.dataset.pctab;editing=null;shell();});renderBody();
 }
 function renderBody(){const b=host.querySelector('#pcBody');if(tab==='clientes')clientsView(b);else if(tab==='planos')plansView(b);else billingView(b);}
 function clientsView(b){
  const tenants=listTenants(),activeId=activeTenantId();
  b.innerHTML='<div class="pc-panel"><div class="pc-toolbar"><div><h3>Organizações / tenants</h3><small>Workspace ativo: <strong>'+esc(activeTenant()?.name||'—')+'</strong></small></div><button class="btn primary" id="newTenant">+ Novo cliente / trial</button></div>'+
   '<div class="pc-table-wrap"><table class="pc-table"><thead><tr><th>Organização</th><th>Plano</th><th>Status</th><th>Uso atual</th><th>Trial / período</th><th>Ações</th></tr></thead><tbody>'+
   tenants.map(t=>{const sub=subscriptionFor(t.id),h=subscriptionHealth(t.id),u=tenantWorkspaceStats(t.id),plan=PLAN_CATALOG.find(p=>p.id===sub?.planId),days=h.daysRemaining;return '<tr><td><strong>'+esc(t.name)+'</strong><small>'+esc(t.slug)+' • '+esc(t.type)+(t.id===activeId?' • WORKSPACE ATIVO':'')+'</small></td><td>'+esc(plan?.name||sub?.planId||'—')+'<small>'+u.eventsMonth+' evento(s)/mês</small></td><td><span class="pc-status '+statusClass(h.status)+'">'+esc(statusLabel(h.status))+'</span></td><td><strong>'+u.schools+'</strong> escolas • <strong>'+u.eventsTotal+'</strong> eventos<small>'+u.students+' aluno(s) • '+u.registrations+' inscrição(ões)</small></td><td>'+(h.status==='trialing'?(days+' dia(s) restantes'):(sub?.currentPeriodEnd?'até '+fmtDate(sub.currentPeriodEnd):'—'))+'<small>início '+fmtDate(sub?.startedAt)+'</small></td><td><div class="pc-actions"><button class="btn ghost small" data-edit="'+t.id+'">Editar</button><button class="btn ghost small" data-sub="'+t.id+'">Assinatura</button>'+(t.id!==activeId?'<button class="btn primary small" data-switch="'+t.id+'">Abrir workspace</button>':'')+(t.type!=='OWNER'&&t.id!==activeId?'<button class="btn danger small" data-delete="'+t.id+'">Excluir</button>':'')+'</div></td></tr>';}).join('')+
   '</tbody></table></div><div id="pcEditor"></div></div>';
  const editor=b.querySelector('#pcEditor');
  b.querySelector('#newTenant').onclick=()=>tenantEditor(null,editor);
  b.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>tenantEditor(listTenants().find(t=>t.id===x.dataset.edit),editor));
  b.querySelectorAll('[data-sub]').forEach(x=>x.onclick=()=>subscriptionEditor(listTenants().find(t=>t.id===x.dataset.sub),editor));
  b.querySelectorAll('[data-switch]').forEach(x=>x.onclick=()=>{const t=listTenants().find(v=>v.id===x.dataset.switch);if(!confirm('Salvar o workspace atual e abrir '+t.name+'? A página será recarregada.'))return;switchTenant(t.id);recordAudit('TENANT_TROCADO','plataforma',t.id,t.name);location.reload();});
  b.querySelectorAll('[data-delete]').forEach(x=>x.onclick=()=>{const t=listTenants().find(v=>v.id===x.dataset.delete);if(!confirm('Excluir a organização '+t.name+' e seu snapshot local? Esta ação não poderá ser desfeita.'))return;deleteTenant(t.id);recordBilling(t.id,'TENANT_EXCLUIDO',t.name);recordAudit('TENANT_EXCLUIDO','plataforma',t.id,t.name);shell();});
 }
 function tenantEditor(t,box){
  const sub=t?subscriptionFor(t.id):null;
  box.innerHTML='<div class="pc-editor"><div class="pc-toolbar"><h3>'+(t?'Editar organização':'Novo cliente / trial')+'</h3><button class="btn ghost small" id="pcClose">Fechar</button></div><form id="tenantForm"><div class="pc-grid"><label>Nome da organização<input name="name" value="'+esc(t?.name||'')+'" required></label>'+(t?'<label>Slug<input value="'+esc(t.slug)+'" disabled></label>':'<label>Slug opcional<input name="slug" placeholder="gerado automaticamente"></label>')+'<label>CNPJ/CPF ou documento<input name="document" value="'+esc(t?.document||'')+'"></label><label>Responsável<input name="contactName" value="'+esc(t?.contactName||'')+'"></label><label>E-mail<input name="contactEmail" type="email" value="'+esc(t?.contactEmail||'')+'"></label><label>Telefone<input name="contactPhone" value="'+esc(t?.contactPhone||'')+'"></label>'+
   (t?'':'<label>Plano inicial<select name="planId">'+PLAN_CATALOG.map(p=>'<option value="'+p.id+'" '+(p.id==='TRIAL'?'selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select></label><label>Dias de trial<input name="trialDays" type="number" min="1" value="'+(planSettings().find(x=>x.id==='TRIAL')?.trialDays||14)+'"></label>')+
   '</div><div class="pc-actions" style="justify-content:flex-end;margin-top:12px"><button class="btn primary">Salvar</button></div></form></div>';
  box.querySelector('#pcClose').onclick=()=>box.innerHTML='';
  box.querySelector('#tenantForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());try{if(t){updateTenant(t.id,{name:d.name.trim(),document:d.document.trim(),contactName:d.contactName.trim(),contactEmail:d.contactEmail.trim(),contactPhone:d.contactPhone.trim()});recordAudit('TENANT_ATUALIZADO','plataforma',t.id,d.name);}else{const created=createTenant({name:d.name,slug:d.slug,document:d.document,contactName:d.contactName,contactEmail:d.contactEmail,contactPhone:d.contactPhone,planId:d.planId,trialDays:Number(d.trialDays)||14});recordBilling(created.id,'TENANT_CRIADO','Plano '+d.planId);recordAudit('TENANT_CRIADO','plataforma',created.id,created.name);}shell();}catch(err){alert(err.message);}};
 }
 function subscriptionEditor(t,box){
  const sub=subscriptionFor(t.id),h=subscriptionHealth(t.id);
  box.innerHTML='<div class="pc-editor"><div class="pc-toolbar"><div><h3>Assinatura • '+esc(t.name)+'</h3><small>Status calculado: '+esc(statusLabel(h.status))+'</small></div><button class="btn ghost small" id="pcClose">Fechar</button></div><form id="subForm"><div class="pc-grid"><label>Plano<select name="planId">'+PLAN_CATALOG.map(p=>'<option value="'+p.id+'" '+(p.id===sub.planId?'selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select></label><label>Status<select name="status"><option value="trialing" '+(sub.status==='trialing'?'selected':'')+'>Trial</option><option value="active" '+(sub.status==='active'?'selected':'')+'>Ativa</option><option value="past_due" '+(sub.status==='past_due'?'selected':'')+'>Pagamento pendente</option><option value="suspended" '+(sub.status==='suspended'?'selected':'')+'>Suspensa</option><option value="canceled" '+(sub.status==='canceled'?'selected':'')+'>Cancelada</option></select></label><label>Fim do trial<input name="trialEndsAt" type="date" value="'+(sub.trialEndsAt?sub.trialEndsAt.slice(0,10):'')+'"></label><label>Fim do período atual<input name="periodEnd" type="date" value="'+(sub.currentPeriodEnd?sub.currentPeriodEnd.slice(0,10):'')+'"></label></div><div class="pc-actions" style="justify-content:flex-end;margin-top:12px"><button class="btn primary">Atualizar assinatura</button></div></form></div>';
  box.querySelector('#pcClose').onclick=()=>box.innerHTML='';
  box.querySelector('#subForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries()),before={...sub},patch={planId:d.planId,status:d.status,authority:'local-development'};if(d.status==='trialing'){patch.trialStartedAt=sub.trialStartedAt||new Date().toISOString();patch.trialEndsAt=d.trialEndsAt?new Date(d.trialEndsAt+'T23:59:59').toISOString():new Date(Date.now()+14*86400000).toISOString();}else if(d.status==='active'){patch.startedAt=sub.startedAt||new Date().toISOString();patch.currentPeriodStart=new Date().toISOString();patch.currentPeriodEnd=d.periodEnd?new Date(d.periodEnd+'T23:59:59').toISOString():addMonthsIso(new Date(),1);}if(d.status!=='trialing'&&d.trialEndsAt)patch.trialEndsAt=new Date(d.trialEndsAt+'T23:59:59').toISOString();updateSubscription(t.id,patch);recordBilling(t.id,'ASSINATURA_ATUALIZADA',before.planId+'/'+before.status+' → '+d.planId+'/'+d.status);recordAudit('ASSINATURA_ATUALIZADA','plataforma',t.id,d.planId+' • '+d.status);shell();};
 }
 function plansView(b){
  const settings=planSettings();
  b.innerHTML='<div class="pc-panel"><div class="pc-note"><strong>Preço autoritativo futuro.</strong> Os valores abaixo servem para modelagem comercial e MRR projetado. O backend de cobrança será a fonte oficial quando o gateway for conectado.</div><form id="planForm"><div class="plan-grid" style="margin-top:10px">'+PLAN_CATALOG.map(p=>{const cfg=settings.find(x=>x.id===p.id)||{},price=cfg.monthlyCents==null?'':(cfg.monthlyCents/100).toFixed(2).replace('.',',');return '<article class="plan-card"><h3>'+esc(p.name)+'</h3><p>'+esc(p.description)+'</p><div class="plan-price">'+(cfg.monthlyCents==null?'Preço a definir':formatMoney(cfg.monthlyCents))+'</div><label style="display:grid;gap:4px;margin-top:8px">Mensalidade R$<input data-price="'+p.id+'" inputmode="decimal" value="'+price+'" placeholder="0,00"></label><label style="display:grid;gap:4px;margin-top:8px">Dias de trial<input data-trial="'+p.id+'" type="number" min="0" value="'+Number(cfg.trialDays||0)+'"></label><small>'+p.features.length+' recurso(s) • '+(p.limits.users==null?'usuários ilimitados':p.limits.users+' usuário(s)')+' • '+(p.limits.eventsMonth==null?'eventos ilimitados':p.limits.eventsMonth+' eventos/mês')+'</small></article>';}).join('')+'</div><div class="pc-actions" style="justify-content:flex-end;margin-top:12px"><button class="btn primary">Salvar preços e parâmetros</button></div></form><div class="pc-panel" style="margin-top:12px"><h3>Mapa de recursos</h3><div class="pc-table-wrap"><table class="pc-table"><thead><tr><th>Recurso</th>'+PLAN_CATALOG.map(p=>'<th>'+esc(p.name)+'</th>').join('')+'</tr></thead><tbody>'+Object.entries(FEATURE_CATALOG).map(([id,label])=>'<tr><td><strong>'+esc(label)+'</strong><small>'+id+'</small></td>'+PLAN_CATALOG.map(p=>'<td>'+(p.features.includes(id)?'✓':'—')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div></div></div>';
  b.querySelector('#planForm').onsubmit=e=>{e.preventDefault();const rows=PLAN_CATALOG.map(p=>{const raw=b.querySelector('[data-price="'+p.id+'"]').value.trim().replace('.','').replace(',','.'),trial=Number(b.querySelector('[data-trial="'+p.id+'"]').value)||0;return{id:p.id,monthlyCents:raw===''?null:Math.round(Number(raw)*100),trialDays:trial,active:true};});savePlanSettings(rows);recordBilling(activeTenantId(),'PLANOS_PRECOS','Tabela comercial atualizada');recordAudit('PLANOS_PRECOS','plataforma','','Tabela comercial local atualizada');alert('Parâmetros comerciais salvos.');shell();};
 }
 function billingView(b){
  const events=billingEvents(),tenants=listTenants();
  b.innerHTML='<div class="pc-panel"><div class="pc-toolbar"><div><h3>Ciclo comercial</h3><small>Histórico administrativo local das mudanças de assinatura.</small></div><span class="pc-status">'+events.length+' evento(s)</span></div><div class="event-list" style="margin-top:10px">'+events.slice(0,500).map(e=>'<article class="event-row"><div><strong>'+fmtDateTime(e.at)+'</strong><small>'+esc(e.user||'Sistema')+'</small></div><div><strong>'+esc(e.type)+'</strong><small>'+esc(e.tenantName||tenants.find(t=>t.id===e.tenantId)?.name||e.tenantId)+'</small></div><div>'+esc(e.details||'—')+'</div></article>').join('')||'<div class="pc-note">Nenhum evento comercial registrado ainda.</div>'+'</div></div>';
 }
 shell();
}
