import {cloudConfigured,submitSolicitacao,submitInscricao,consultarProtocolo,listPublicEvents,isCloudEmulatorMode} from '../cloudGateway.js?v=6';
import {directFirestoreConfigured,submitSolicitacaoDireta,submitInscricaoDireta,consultarProtocoloDireto,listPublicEventsDireto} from '../directFirestore.js?v=1';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const phone=v=>String(v||'').replace(/\D/g,'').replace(/^(\d{2})(\d)/,'($1) $2').replace(/(\d{5})(\d{4}).*/,'$1-$2');

function css(){
 if(document.getElementById('public-service-css'))return;
 const s=document.createElement('style');s.id='public-service-css';s.textContent=`
 .ps{max-width:1160px;margin:auto}.ps-hero{padding:24px;border-radius:22px;background:linear-gradient(135deg,#073d68,#087fac);color:#fff;display:grid;grid-template-columns:1fr auto;gap:18px;align-items:center}
 .ps-hero h2{margin:4px 0;font-size:1.55rem}.ps-hero p{margin:4px 0;color:#d9f3ff}.ps-state{padding:8px 12px;border-radius:999px;background:#fff;color:#0d4c70;font-weight:900;font-size:.78rem}
 .ps-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.ps-tab{border:1px solid #c8dce7;background:#fff;padding:10px 14px;border-radius:12px;font-weight:900;color:#174766;cursor:pointer}.ps-tab.active{background:#0a6fa4;color:#fff;border-color:#0a6fa4}
 .ps-panel{background:#fff;border:1px solid #d9e7ef;border-radius:18px;padding:18px;box-shadow:0 10px 32px rgba(17,55,80,.08)}.ps-panel h3{margin-top:0}
 .ps-alert{padding:12px 14px;border-radius:12px;background:#fff8df;border-left:4px solid #f0b429;color:#59440c;margin-bottom:14px}.ps-offline{background:#ffecec;border-color:#d64545;color:#6d2222}
 .ps-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ps-grid label,.ps-panel>form>label{display:grid;gap:5px;font-weight:800;color:#214c67;font-size:.86rem}.ps input,.ps select,.ps textarea{width:100%;padding:10px 11px;border:1px solid #c9dbe6;border-radius:10px;background:#fff;color:#173f60;font:inherit}.ps textarea{resize:vertical}.ps .span2{grid-column:1/-1}.ps-actions{display:flex;gap:10px;justify-content:flex-end;margin-top:14px}.ps-result{margin-top:14px;padding:16px;border-radius:14px;background:#edf9f1;border:1px solid #b8e5c7}.ps-result strong{display:block;font-size:1.1rem}.ps-protocol{font-size:1.25rem;font-weight:1000;color:#096a3a;margin:4px 0}.ps-status{display:inline-block;padding:5px 9px;border-radius:999px;background:#e7f4fb;color:#0c5f88;font-weight:900}
 @media(max-width:700px){.ps-hero{grid-template-columns:1fr}.ps-grid{grid-template-columns:1fr}.ps .span2{grid-column:auto}}
 `;document.head.appendChild(s);
}
const directMode=()=>!isCloudEmulatorMode()&&directFirestoreConfigured();
const publicConfigured=()=>isCloudEmulatorMode()?cloudConfigured():(directMode()||cloudConfigured());
const sendRequest=data=>directMode()?submitSolicitacaoDireta(data):submitSolicitacao(data);
const sendRegistration=data=>directMode()?submitInscricaoDireta(data):submitInscricao(data);
const lookupProtocol=(p,c)=>directMode()?consultarProtocoloDireto(p,c):consultarProtocolo(p,c);
const loadEvents=()=>directMode()?listPublicEventsDireto():listPublicEvents();
function availability(){if(isCloudEmulatorMode())return '<div class="ps-alert"><strong>Emulador local ativo.</strong> Solicitações e inscrições serão gravadas somente no ambiente Firebase local desta máquina.</div>';return directMode()?'<div class="ps-alert"><strong>Envio online ativo pelo Firestore.</strong> Solicitações e inscrições são registradas na nuvem e ficam disponíveis para análise do gestor autenticado.</div>':(cloudConfigured()?'<div class="ps-alert"><strong>Envio online ativo.</strong> Solicitações e inscrições são encaminhadas à área do gestor para análise.</div>':'<div class="ps-alert ps-offline"><strong>Integração online indisponível.</strong> O envio está temporariamente bloqueado.</div>');}

export async function renderPublicService(host){
 if(!host)return;css();let tab='solicitar',events=[];
 host.innerHTML=`<div class="ps"><div class="ps-hero"><div><p class="eyebrow">ATENDIMENTO • MOBILIZA EDUCA</p><h2>Solicite uma ação ou inscreva-se em uma atividade</h2><p>Todo pedido passa por análise do gestor. Protocolo de recebimento não significa atendimento ou vaga confirmada.</p></div><div class="ps-state">SOB APROVAÇÃO DO GESTOR</div></div><div class="ps-tabs"><button class="ps-tab active" data-ps="solicitar">📥 Solicitar atendimento</button><button class="ps-tab" data-ps="inscrever">📝 Inscrição</button><button class="ps-tab" data-ps="consultar">🔎 Consultar protocolo</button></div><div id="psPanel"></div></div>`;
 const panel=host.querySelector('#psPanel');
 const draw=async()=>{host.querySelectorAll('[data-ps]').forEach(b=>b.classList.toggle('active',b.dataset.ps===tab));if(tab==='solicitar')solicitar();else if(tab==='inscrever')await inscrever();else consultar();};
 function bindPhone(root){root.querySelectorAll('[data-phone]').forEach(i=>i.oninput=()=>i.value=phone(i.value));}
 function solicitar(){
  panel.innerHTML=`<section class="ps-panel"><h3>Solicitação de palestra, curso ou ação educativa</h3>${availability()}<div class="ps-alert"><strong>Importante:</strong> ao enviar, você receberá apenas um protocolo de recebimento. A data, o horário e o atendimento somente estarão confirmados após retorno do gestor.</div><form id="psRequest"><div class="ps-grid">
  <label>Tipo de solicitante<select name="origemTipo"><option>Escola</option><option>Instituição</option><option>Pessoa / Comunidade</option></select></label>
  <label>Escola / instituição / entidade<input name="origemNome" required></label><label>Nome do responsável<input name="solicitanteNome" required></label><label>Telefone<input name="telefone" data-phone required></label>
  <label>E-mail<input name="email" type="email" required></label><label>Atividade desejada<select name="atividade"><option>Palestra</option><option>Curso</option><option>Oficina</option><option>Ação educativa</option><option>Programa</option><option>SIPAT</option><option>Visita técnica</option><option>Outro</option></select></label>
  <label>Data preferida<input name="dataPreferida" type="date"></label><label>Hora preferida<input name="horaPreferida" type="time"></label>
  <label>Flexibilidade<select name="flexibilidade"><option>Data/horário fixos</option><option>Pode ajustar horário</option><option>Pode ajustar data</option><option>Data e horário flexíveis</option></select></label>
  <label>Quantidade prevista<input name="quantidade" type="number" min="1" required></label><label>Público-alvo<input name="publico" placeholder="Ex.: 2º ano, colaboradores, comunidade"></label><label>Local desejado<input name="local"></label>
  <label class="span2">Objetivo / necessidades<textarea name="necessidades" rows="4"></textarea></label><label class="span2"><span><input name="ciente" type="checkbox" required> Estou ciente de que esta solicitação não garante atendimento e será analisada pelo gestor.</span></label>
  </div><div class="ps-actions"><button class="btn primary" ${publicConfigured()?'':'disabled'}>Enviar solicitação</button></div></form><div id="psResult"></div></section>`;
  const f=panel.querySelector('#psRequest');bindPhone(f);f.onsubmit=async e=>{e.preventDefault();if(!publicConfigured())return;const b=f.querySelector('button'),out=panel.querySelector('#psResult');b.disabled=true;b.textContent='Enviando...';try{const data=Object.fromEntries(new FormData(f).entries());delete data.ciente;const r=await sendRequest(data);out.innerHTML=`<div class="ps-result"><strong>Solicitação recebida</strong><div class="ps-protocol">${esc(r.protocolo)}</div><p>Status: <span class="ps-status">Recebida</span></p><p>Guarde o protocolo. O atendimento ainda depende de análise e confirmação do gestor.</p></div>`;f.reset();}catch(err){out.innerHTML=`<div class="ps-alert ps-offline">${esc(err.message)}</div>`;}finally{b.disabled=false;b.textContent='Enviar solicitação';}};
 }
 async function inscrever(){
  panel.innerHTML=`<section class="ps-panel"><h3>Inscrição em atividade disponível</h3>${availability()}<div id="psEvents">Carregando atividades...</div></section>`;
  if(!publicConfigured()){panel.querySelector('#psEvents').innerHTML='<p>As atividades com inscrição pública estão temporariamente indisponíveis.</p>';return;}
  try{const r=await loadEvents();events=r.eventos||[];}catch(err){panel.querySelector('#psEvents').innerHTML='<div class="ps-alert ps-offline">'+esc(err.message)+'</div>';return;}
  const box=panel.querySelector('#psEvents');if(!events.length){box.innerHTML='<p>Nenhuma atividade com inscrições abertas neste momento.</p>';return;}
  box.innerHTML=`<div class="ps-alert"><strong>A inscrição também passa por confirmação.</strong> O envio da ficha não reserva vaga até o gestor alterar o status para Confirmada.</div><form id="psReg"><div class="ps-grid"><label class="span2">Atividade<select name="idEvento" required>${events.map(x=>`<option value="${esc(x.id)}">${esc(x.dataLabel||'')} • ${esc(x.nome)} • ${esc(x.vagasInfo||'')}</option>`).join('')}</select></label><label>Tipo<select name="tipoInscricao"><option>Pessoa individual</option><option>Instituição / Grupo</option></select></label><label>Quantidade de vagas<input name="quantidade" type="number" min="1" value="1" required></label><label>Nome / grupo<input name="nome" required></label><label>Responsável / contato<input name="responsavel"></label><label>Telefone<input name="telefone" data-phone required></label><label>E-mail<input name="email" type="email" required></label><label class="span2">Necessidades de acessibilidade / observações<textarea name="observacao" rows="3"></textarea></label><label class="span2"><span><input name="ciente" type="checkbox" required> Estou ciente de que a inscrição só estará garantida após confirmação do gestor.</span></label></div><div class="ps-actions"><button class="btn primary">Enviar inscrição</button></div></form><div id="psResult"></div>`;
  const f=box.querySelector('#psReg');bindPhone(f);f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button'),out=box.querySelector('#psResult');b.disabled=true;b.textContent='Enviando...';try{const data=Object.fromEntries(new FormData(f).entries());delete data.ciente;const r=await sendRegistration(data);out.innerHTML=`<div class="ps-result"><strong>Inscrição recebida</strong><div class="ps-protocol">${esc(r.protocolo)}</div><p>Status: <span class="ps-status">Recebida</span></p><p>Aguarde a confirmação do gestor antes de considerar sua vaga garantida.</p></div>`;f.reset();}catch(err){out.innerHTML=`<div class="ps-alert ps-offline">${esc(err.message)}</div>`;}finally{b.disabled=false;b.textContent='Enviar inscrição';}};
 }
 function consultar(){
  const contactField=directMode()?'':'<label>E-mail ou telefone informado no envio<input name="contato" required></label>';
  panel.innerHTML=`<section class="ps-panel"><h3>Consultar andamento</h3>${availability()}<div class="ps-alert"><strong>Guarde seu protocolo.</strong> No modo Firestore direto ele funciona como chave de consulta e não expõe seus dados pessoais.</div><form id="psLookup"><div class="ps-grid"><label>Protocolo<input name="protocolo" required placeholder="SOL-... ou INS-..."></label>${contactField}</div><div class="ps-actions"><button class="btn primary" ${publicConfigured()?'':'disabled'}>Consultar</button></div></form><div id="psResult"></div></section>`;
  const f=panel.querySelector('#psLookup');f.onsubmit=async e=>{e.preventDefault();const out=panel.querySelector('#psResult');try{const d=Object.fromEntries(new FormData(f).entries()),r=await lookupProtocol(d.protocolo.trim(),(d.contato||'').trim());out.innerHTML=`<div class="ps-result"><strong>${esc(r.tipoLabel||'Protocolo')}</strong><div class="ps-protocol">${esc(r.protocolo)}</div><p>Status atual: <span class="ps-status">${esc(r.status)}</span></p><p>${esc(r.mensagem||'')}</p></div>`;}catch(err){out.innerHTML=`<div class="ps-alert ps-offline">${esc(err.message)}</div>`;}};
 }
 host.querySelectorAll('[data-ps]').forEach(b=>b.onclick=()=>{tab=b.dataset.ps;draw();});draw();
}
