import {
 exportOperationalBackup,exportProtectedBackup,inspectBackupContainer,parseBackup,restoreBackup,storageEstimate,backupFilename
} from '../core/backupManager.js?v=2';
import {listEvidenceFiles} from '../core/evidenceStore.js?v=3';
import {recordAudit,currentUser} from '../core/accessControl.js?v=1';
import {cloudConfigured,hasManagerKey} from '../cloudGateway.js?v=3';

const SETTINGS='mobiliza.system.settings';
const BACKUP_STATE='mobiliza.system.backupState';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtBytes=n=>{n=Number(n)||0;if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB';};
const safe=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const settings=()=>({org:'Prefeitura de Presidente Prudente',secretaria:'SEMOB',departamento:'Educação para o Trânsito',cidade:'Presidente Prudente - SP',responsavel:'',email:'',telefone:'',rodape:'Mobiliza Educa • Educação para o Trânsito',...safe(SETTINGS,{})});
const backupState=()=>safe(BACKUP_STATE,{lastOperationalAt:null,lastProtectedAt:null,lastRestoreAt:null});
const setBackupState=p=>localStorage.setItem(BACKUP_STATE,JSON.stringify({...backupState(),...p}));
const download=(name,text,type='application/json;charset=utf-8')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);};

function css(){
 if(document.getElementById('system360css'))return;
 const s=document.createElement('style');s.id='system360css';s.textContent=`
 .sys-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 16px}.sys-tab{border:1px solid #c9dce7;background:#fff;color:#214e69;padding:10px 13px;border-radius:11px;font-weight:900;cursor:pointer}.sys-tab.active{background:#0b709f;color:#fff}
 .sys-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0 16px}.sys-kpi,.sys-panel{background:#fff;border:1px solid #d9e7ee;border-radius:14px;padding:14px}.sys-kpi strong{display:block;font-size:1.25rem;color:#0a678f}.sys-kpi span{font-size:.76rem;color:#6f8491}
 .sys-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:11px}.sys-grid label{display:grid;gap:5px;font-size:.81rem;font-weight:900;color:#315a72}.sys-grid input,.sys-grid select,.sys-grid textarea{padding:10px;border:1px solid #c8dce7;border-radius:10px;background:#fff;font:inherit}.sys-span2{grid-column:1/-1}
 .sys-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;margin-top:12px}.sys-note{padding:12px 14px;border-left:4px solid #0b78a8;background:#eef8fc;border-radius:10px;line-height:1.45;margin:10px 0}.sys-warn{border-left-color:#dda000;background:#fff6d9}.sys-danger{border-left-color:#c43e3e;background:#ffeded}
 .backup-cards{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.backup-card{border:1px solid #dbe7ed;border-radius:14px;padding:15px;background:#fff}.backup-card h3{margin:0 0 6px}.backup-card p{color:#6e8390;line-height:1.45}.backup-meta{display:grid;gap:5px;font-size:.78rem;color:#617987;margin:10px 0}.backup-meta strong{color:#173f60}
 .restore-preview{border:1px solid #cfe0e9;border-radius:13px;padding:13px;background:#f9fcfd;margin-top:12px}.restore-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.restore-grid div{border:1px solid #dce8ee;border-radius:10px;padding:9px;background:#fff}.restore-grid strong,.restore-grid span{display:block}.restore-grid strong{color:#0b678f}.restore-grid span{font-size:.7rem;color:#718693}
 .storage-bar{height:14px;border-radius:999px;background:#e6eef2;overflow:hidden;margin:8px 0}.storage-bar span{display:block;height:100%;background:linear-gradient(90deg,#0b78a8,#21aa72)}.health-list{display:grid;gap:7px;margin-top:10px}.health-row{display:grid;grid-template-columns:1fr auto;gap:8px;padding:10px;border:1px solid #dce8ee;border-radius:10px}.health-row small{display:block;color:#728692}.health-badge{align-self:center;border-radius:999px;padding:5px 8px;background:#e3f6e9;color:#176638;font-size:.7rem;font-weight:900}.health-badge.warn{background:#fff2d5;color:#835c08}
 .cloud-steps{display:grid;gap:9px}.cloud-step{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;border:1px solid #dce8ee;border-radius:11px;padding:11px}.cloud-step .n{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#e9f5fa;color:#0b668f;font-weight:900}.cloud-step small{display:block;color:#718592}.cloud-step .state{font-size:.7rem;font-weight:900;border-radius:999px;padding:5px 8px;background:#edf3f6;color:#5b7180}.cloud-step .state.ok{background:#e2f5e8;color:#176638}
 @media(max-width:850px){.sys-kpis,.restore-grid{grid-template-columns:repeat(2,1fr)}.backup-cards,.sys-grid{grid-template-columns:1fr}.sys-span2{grid-column:auto}}
 @media(max-width:560px){.sys-kpis,.restore-grid{grid-template-columns:1fr}.cloud-step{grid-template-columns:auto 1fr}.cloud-step .state{grid-column:2}}
 `;document.head.appendChild(s);
}
function stateText(v){return v?new Date(v).toLocaleString('pt-BR'):'Nunca';}
function counts(){
 const names=['escolas','instituicoes','pessoas','turmas','professores','alunos','eventos','solicitacoes','inscricoes','certificados','avaliacoes','impactos','evidencias'];
 const o={};for(const n of names){try{o[n]=JSON.parse(localStorage.getItem('mobiliza.admin.'+n)||'[]').length}catch{o[n]=0}}return o;
}
async function diagnostics(){
 const c=counts(),meta=c.evidencias,files=await listEvidenceFiles().catch(()=>[]),storage=await storageEstimate(),persisted=await navigator.storage?.persisted?.().catch(()=>false);
 const totalCore=c.escolas+c.instituicoes+c.pessoas+c.turmas+c.alunos+c.eventos+c.solicitacoes+c.inscricoes;
 return{c,meta,files:files.length,fileBytes:files.reduce((s,x)=>s+Number(x.size||x.blob?.size||0),0),storage,persisted:!!persisted,totalCore,missingFiles:Math.max(0,meta-files.length),orphanFiles:Math.max(0,files.length-meta)};
}
function identitySummary(s){return[s.org,s.secretaria,s.departamento,s.cidade].filter(Boolean).join(' • ');}
function backupEstimateFromMeta(){const arr=safe('mobiliza.admin.evidencias',[]);return Array.isArray(arr)?arr.reduce((s,x)=>s+Number(x.size||0),0):0;}

export function renderSistemaContinuity(host){
 css();let tab='identidade',restoreFile=null,restoreParsed=null,restoreInfo=null;
 const shell=async()=>{
  const bs=backupState(),diag=await diagnostics(),cloud=cloudConfigured(),manager=hasManagerKey();
  host.innerHTML=`<section class="admin-module"><p class="eyebrow">CONFIGURAÇÕES, BACKUP & CONTINUIDADE • v1.0</p><h2>Continuidade operacional do Mobiliza Educa</h2><p class="admin-intro">Proteja dados, identifique a instalação e prepare a migração segura para a nuvem.</p>
  <div class="sys-kpis"><div class="sys-kpi"><strong>${diag.totalCore}</strong><span>registros operacionais principais</span></div><div class="sys-kpi"><strong>${diag.files}</strong><span>arquivos de evidência locais</span></div><div class="sys-kpi"><strong>${fmtBytes(diag.storage.usage||diag.storage.localBytes)}</strong><span>armazenamento utilizado</span></div><div class="sys-kpi"><strong>${cloud?'Configurada':'Local'}</strong><span>camada de nuvem</span></div></div>
  <div class="sys-tabs"><button class="sys-tab ${tab==='identidade'?'active':''}" data-systab="identidade">🏛️ Identidade</button><button class="sys-tab ${tab==='backup'?'active':''}" data-systab="backup">💾 Backup</button><button class="sys-tab ${tab==='restaurar'?'active':''}" data-systab="restaurar">↩️ Restaurar</button><button class="sys-tab ${tab==='armazenamento'?'active':''}" data-systab="armazenamento">🗄️ Armazenamento</button><button class="sys-tab ${tab==='nuvem'?'active':''}" data-systab="nuvem">☁️ Nuvem</button></div><div id="sysBody"></div></section>`;
  host.querySelectorAll('[data-systab]').forEach(b=>b.onclick=()=>{tab=b.dataset.systab;restoreParsed=null;restoreInfo=null;shell();});
  const body=host.querySelector('#sysBody');if(tab==='identidade')identityView(body);else if(tab==='backup')backupView(body,bs,diag);else if(tab==='restaurar')restoreView(body);else if(tab==='armazenamento')await storageView(body,diag);else cloudView(body,cloud,manager);
 };
 function identityView(body){
  const s=settings(),u=currentUser();
  body.innerHTML=`<div class="sys-panel"><div class="sys-note"><strong>Identidade institucional.</strong> Estes dados serão reutilizados em relatórios, certificados e documentos conforme os módulos forem consolidados.</div><form id="identityForm"><div class="sys-grid"><label>Órgão / Prefeitura<input name="org" value="${esc(s.org)}"></label><label>Secretaria<input name="secretaria" value="${esc(s.secretaria)}"></label><label>Departamento / Coordenação<input name="departamento" value="${esc(s.departamento)}"></label><label>Cidade / UF<input name="cidade" value="${esc(s.cidade)}"></label><label>Responsável institucional<input name="responsavel" value="${esc(s.responsavel||u?.name||'')}"></label><label>E-mail institucional<input name="email" type="email" value="${esc(s.email)}"></label><label>Telefone<input name="telefone" value="${esc(s.telefone)}"></label><label class="sys-span2">Rodapé institucional<input name="rodape" value="${esc(s.rodape)}"></label></div><div class="sys-actions"><button class="btn primary">Salvar identidade</button></div></form><div class="sys-note"><strong>Prévia:</strong> ${esc(identitySummary(s))}</div></div>`;
  body.querySelector('#identityForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target).entries());localStorage.setItem(SETTINGS,JSON.stringify(v));recordAudit('CONFIG_IDENTIDADE','sistema','',identitySummary(v));alert('Identidade institucional salva.');shell();};
 }
 function backupView(body,bs,diag){
  const est=backupEstimateFromMeta();
  body.innerHTML=`<div class="backup-cards"><article class="backup-card"><h3>📄 Backup Operacional</h3><p>JSON legível com dados e configurações operacionais. <strong>Não inclui usuários, hashes de senha ou auditoria de segurança</strong>. Ideal para cópia frequente e migração de dados.</p><div class="backup-meta"><span>Último: <strong>${stateText(bs.lastOperationalAt)}</strong></span><span>Evidências binárias: <strong>não incluídas</strong></span></div><button class="btn primary" id="backupOperational">Baixar backup operacional</button></article>
  <article class="backup-card"><h3>🔐 Backup Completo Protegido</h3><p>Inclui todos os dados locais, usuários, perfis, auditoria e, opcionalmente, arquivos de evidência. O conteúdo é criptografado com uma senha exclusiva do backup.</p><div class="sys-grid"><label class="sys-span2">Senha do backup<input id="backupPass" type="password" minlength="10" placeholder="Mínimo 10 caracteres"></label><label class="sys-span2"><span><input id="backupEvidence" type="checkbox"> Incluir arquivos de evidência (${fmtBytes(est)} estimados)</span></label></div><div class="backup-meta"><span>Último: <strong>${stateText(bs.lastProtectedAt)}</strong></span><span>Criptografia: <strong>AES-GCM / PBKDF2-SHA256</strong></span></div><button class="btn primary" id="backupProtected">Gerar backup protegido</button></article></div>
  <div class="sys-note sys-warn"><strong>Regra de segurança:</strong> a senha do backup protegido não é salva pelo Mobiliza Educa. Sem ela, o arquivo não poderá ser restaurado.</div>`;
  body.querySelector('#backupOperational').onclick=async()=>{const btn=body.querySelector('#backupOperational');btn.disabled=true;btn.textContent='Gerando...';try{const json=await exportOperationalBackup();download(backupFilename('operacional'),json);setBackupState({lastOperationalAt:new Date().toISOString()});recordAudit('BACKUP_OPERACIONAL','backup','',`${json.length} bytes exportados`);alert('Backup operacional gerado.');shell();}catch(e){alert(e.message);}finally{btn.disabled=false;}};
  body.querySelector('#backupProtected').onclick=async()=>{const pass=body.querySelector('#backupPass').value,include=body.querySelector('#backupEvidence').checked,btn=body.querySelector('#backupProtected');if(pass.length<10){alert('Use uma senha de backup com pelo menos 10 caracteres.');return;}if(include&&est>50*1024*1024&&!confirm('As evidências somam aproximadamente '+fmtBytes(est)+'. O backup poderá consumir bastante memória. Continuar?'))return;btn.disabled=true;btn.textContent='Criptografando...';try{const out=await exportProtectedBackup(pass,{includeEvidenceFiles:include});download(backupFilename('completo-protegido'),out.json);setBackupState({lastProtectedAt:new Date().toISOString()});recordAudit('BACKUP_PROTEGIDO','backup','',`Chaves: ${out.stats.keys} • evidências: ${out.stats.evidenceFiles}`);alert('Backup completo protegido gerado com sucesso. Guarde a senha em local seguro.');shell();}catch(e){alert(e.message);}finally{btn.disabled=false;}};
 }
 function restoreView(body){
  body.innerHTML=`<div class="sys-panel"><div class="sys-note sys-danger"><strong>Restauração altera dados deste navegador.</strong> Faça um backup atual antes de substituir informações. A pré-visualização abaixo não modifica nada.</div><div class="sys-grid"><label class="sys-span2">Arquivo de backup<input id="restoreFile" type="file" accept=".json,application/json"></label><label id="restorePassLabel" hidden>Senha do backup protegido<input id="restorePass" type="password"></label><label>Modo de restauração<select id="restoreMode"><option value="merge">Mesclar com os dados atuais</option><option value="replace">Substituir dados do mesmo escopo</option></select></label><label><span><input id="restoreEvidence" type="checkbox" checked> Restaurar arquivos de evidência, quando existirem</span></label></div><div class="sys-actions" style="justify-content:flex-start"><button class="btn ghost" id="previewRestore" disabled>Verificar e pré-visualizar</button></div><div id="restorePreview"></div></div>`;
  const fileInput=body.querySelector('#restoreFile'),preview=body.querySelector('#restorePreview'),passLabel=body.querySelector('#restorePassLabel'),btn=body.querySelector('#previewRestore');
  fileInput.onchange=async()=>{restoreFile=fileInput.files?.[0]||null;restoreParsed=null;restoreInfo=null;preview.innerHTML='';btn.disabled=!restoreFile;if(!restoreFile)return;try{const text=await restoreFile.text();restoreInfo=inspectBackupContainer(text);passLabel.hidden=!restoreInfo.encrypted;preview.innerHTML='<div class="sys-note"><strong>Arquivo reconhecido.</strong> '+(restoreInfo.encrypted?'Backup protegido • informe a senha para verificar.':'Backup operacional • pronto para verificação.')+'</div>';}catch(e){preview.innerHTML='<div class="sys-note sys-danger">'+esc(e.message)+'</div>';btn.disabled=true;}};
  btn.onclick=async()=>{if(!restoreFile)return;btn.disabled=true;btn.textContent='Verificando...';try{restoreParsed=await parseBackup(await restoreFile.text(),body.querySelector('#restorePass').value);const p=restoreParsed.payload,s=restoreParsed.stats;if(p.scope==='full'){body.querySelector('#restoreMode').value='replace';body.querySelector('#restoreMode').disabled=true;}else body.querySelector('#restoreMode').disabled=false;preview.innerHTML=`<div class="restore-preview"><strong>✓ Integridade verificada</strong><p>Backup criado em ${new Date(p.createdAt).toLocaleString('pt-BR')} • versão ${esc(p.appVersion)} • escopo ${esc(p.scope)}</p>${p.scope==='full'?'<div class="sys-note sys-warn"><strong>Restauração completa:</strong> usuários, perfis e configurações de segurança serão substituídos pelos dados deste backup. A mesclagem fica desativada.</div>':''}<div class="restore-grid"><div><strong>${s.keys}</strong><span>chaves</span></div><div><strong>${s.records}</strong><span>registros em coleções</span></div><div><strong>${fmtBytes(s.bytes)}</strong><span>dados JSON</span></div><div><strong>${s.evidenceFiles}</strong><span>arquivos de evidência</span></div></div><div class="sys-actions"><button class="btn danger" id="applyRestore">Aplicar restauração</button></div></div>`;preview.querySelector('#applyRestore').onclick=async()=>{const mode=body.querySelector('#restoreMode').value,withFiles=body.querySelector('#restoreEvidence').checked;if(!confirm((mode==='replace'?'SUBSTITUIR':'MESCLAR')+' os dados deste navegador com o backup verificado?'))return;const b=preview.querySelector('#applyRestore');b.disabled=true;b.textContent='Restaurando...';try{recordAudit('RESTAURACAO_INICIADA','backup','',`Modo ${mode} • escopo ${p.scope}`);const r=await restoreBackup(restoreParsed,{mode,restoreEvidenceFiles:withFiles});setBackupState({lastRestoreAt:new Date().toISOString()});recordAudit('RESTAURACAO_CONCLUIDA','backup','',`${r.keys} chaves • ${r.evidenceFiles} evidências • ${mode}`);alert('Restauração concluída. O Mobiliza Educa será recarregado para aplicar todos os dados e permissões.');location.reload();}catch(e){alert('Falha na restauração: '+e.message);b.disabled=false;b.textContent='Aplicar restauração';}};}catch(e){restoreParsed=null;preview.innerHTML='<div class="sys-note sys-danger"><strong>Backup não validado.</strong> '+esc(e.message)+'</div>';}finally{btn.disabled=false;btn.textContent='Verificar e pré-visualizar';}};
 }
 async function storageView(body,diag){
  const q=diag.storage.quota||0,u=diag.storage.usage||0,pc=q?Math.min(100,Math.round(u/q*100)):0,bs=backupState();
  body.innerHTML=`<div class="sys-panel"><h3>Diagnóstico do armazenamento</h3><div class="sys-note"><strong>Dados locais:</strong> ${fmtBytes(diag.storage.localBytes)} em ${diag.storage.localKeys} chave(s) de localStorage. Uso total estimado pelo navegador: ${fmtBytes(u)}${q?' de '+fmtBytes(q):''}.</div><div class="storage-bar"><span style="width:${pc}%"></span></div><div class="health-list"><div class="health-row"><div><strong>Persistência do armazenamento</strong><small>Ajuda a reduzir a chance de remoção automática pelo navegador.</small></div><span class="health-badge ${diag.persisted?'':'warn'}">${diag.persisted?'Concedida':'Não garantida'}</span></div><div class="health-row"><div><strong>Metadados × arquivos de evidência</strong><small>${diag.meta} registro(s) de evidência e ${diag.files} arquivo(s) reais no IndexedDB.</small></div><span class="health-badge ${diag.missingFiles||diag.orphanFiles?'warn':''}">${diag.missingFiles||diag.orphanFiles?'Revisar':'Consistente'}</span></div><div class="health-row"><div><strong>Último backup operacional</strong><small>${stateText(bs.lastOperationalAt)}</small></div><span class="health-badge ${bs.lastOperationalAt?'':'warn'}">${bs.lastOperationalAt?'Registrado':'Pendente'}</span></div><div class="health-row"><div><strong>Último backup protegido</strong><small>${stateText(bs.lastProtectedAt)}</small></div><span class="health-badge ${bs.lastProtectedAt?'':'warn'}">${bs.lastProtectedAt?'Registrado':'Recomendado'}</span></div></div><div class="sys-actions" style="justify-content:flex-start"><button class="btn primary" id="requestPersist" ${diag.persisted?'disabled':''}>Solicitar armazenamento persistente</button><button class="btn ghost" id="clearCaches">Limpar cache do aplicativo</button></div><div class="sys-note sys-warn"><strong>Importante:</strong> limpar o cache do aplicativo não apaga os registros administrativos. Não use “Limpar dados do site” do navegador sem possuir backup.</div></div>`;
  body.querySelector('#requestPersist').onclick=async()=>{if(!navigator.storage?.persist){alert('Este navegador não oferece solicitação de persistência.');return;}const ok=await navigator.storage.persist();recordAudit('STORAGE_PERSIST','sistema','',ok?'Persistência concedida':'Persistência não concedida');alert(ok?'Armazenamento persistente concedido.':'O navegador não concedeu persistência automática. Mantenha backups regulares.');shell();};
  body.querySelector('#clearCaches').onclick=async()=>{if(!('caches'in window)){alert('API de cache indisponível.');return;}if(!confirm('Limpar os arquivos em cache do PWA? Os dados administrativos serão preservados.'))return;const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('mobiliza-educa-')).map(k=>caches.delete(k)));recordAudit('CACHE_LIMPO','sistema','',keys.join(', '));alert('Cache do aplicativo limpo. A página será recarregada.');location.reload();};
 }
 function cloudView(body,cloud,manager){
  body.innerHTML=`<div class="sys-panel"><div class="sys-note"><strong>Preparação para nuvem.</strong> O Mobiliza Educa continua funcional localmente. A sincronização real entre celulares/computadores e push para o gestor depende do backend Firebase configurado e publicado.</div><div class="cloud-steps"><div class="cloud-step"><span class="n">1</span><div><strong>Configuração web Firebase</strong><small>Projeto, apiKey, projectId e endpoints.</small></div><span class="state ${cloud?'ok':''}">${cloud?'Configurada':'Pendente'}</span></div><div class="cloud-step"><span class="n">2</span><div><strong>Chave de operação do gestor</strong><small>Autoriza ações administrativas nos endpoints protegidos.</small></div><span class="state ${manager?'ok':''}">${manager?'Disponível':'Pendente'}</span></div><div class="cloud-step"><span class="n">3</span><div><strong>Dados compartilhados</strong><small>Solicitações, inscrições, check-in, certificados e demais coleções passam a sincronizar entre dispositivos.</small></div><span class="state">Preparado</span></div><div class="cloud-step"><span class="n">4</span><div><strong>Identidade centralizada</strong><small>Os usuários locais da 0.44.0 deverão migrar para autenticação/autorizações de servidor.</small></div><span class="state">Futuro</span></div></div><div class="sys-note sys-warn"><strong>Sem falsa sincronização:</strong> enquanto Firebase não estiver ativo, o sistema continuará indicando armazenamento local e não afirmará que dados de outro aparelho foram recebidos.</div></div>`;
 }
 shell();
}
