import {loadWindowsStudentCatalog,importWindowsStudent} from '../core/windowsStudentRepository.js?v=1';
import {checkWindowsStudents,studentNameMatches,studentOriginMatch} from '../core/windowsStudentPolicy.js?v=1';
import {matchingWindowsSchools,matchingWindowsClasses,windowsClassData} from '../core/windowsClassPolicy.js?v=1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function parseWindowsStudents(text){text=text.replace(/^\uFEFF/,'').trim();if(!text.startsWith('<'))return checkWindowsStudents(JSON.parse(text));const xml=new DOMParser().parseFromString(text,'application/xml');if(xml.querySelector('parsererror')||xml.documentElement.tagName!=='mobilizaWindowsAlunos')throw new Error('XML de alunos inválido.');const root=xml.documentElement,read=name=>[...root.querySelectorAll(name+' > registro')].map(r=>Object.fromEntries([...r.children].map(c=>[c.tagName,c.getAttributeNS('http://www.w3.org/2001/XMLSchema-instance','nil')==='true'?null:c.textContent])));return checkWindowsStudents({formato:'mobiliza-windows-alunos',versao:root.querySelector('versao')?.textContent,banco:root.querySelector('banco')?.textContent,escolas:read('escolas'),turmas:read('turmas'),alunos:read('alunos')});}
export async function renderWindowsStudentImport(host,onDone){
 host.hidden=false;host.innerHTML='<p>Carregando escolas, turmas e alunos…</p>';const anchor=host.firstChild;let ctx;try{ctx=await loadWindowsStudentCatalog();}catch(e){if(host.firstChild===anchor)host.textContent=e.message;return;}if(host.firstChild!==anchor)return;
 host.innerHTML=`<h3>Importar alunos do Windows</h3><p>Cliente: <strong>${esc(ctx.tenantId)}</strong>. Carregue o arquivo específico de alunos (JSON ou XML), confira as turmas e selecione os registros. Nomes iguais exigem conferência: escolha preservar o cadastro ou criar um aluno distinto.</p><label id="wsDrop" class="btn ghost">Arraste o arquivo ou selecione<input id="wsFile" type="file" accept=".json,.xml"></label><div id="wsPreview"></div><p id="wsMessage" role="status" aria-live="polite"></p><button id="wsClose" type="button" class="btn ghost">Fechar importação</button>`;
 const marker=host.firstChild,alive=()=>host.isConnected&&host.firstChild===marker,qs=s=>host.querySelector(s);let pack,schools={},classes={},choices={},selected=new Set(),busy=false,sequence=0;
 const message=t=>{if(alive())qs('#wsMessage').textContent=t;};
 function suggest(){classes={};for(const t of pack.turmas){const sid=schools[String(t.idEscola)];if(!sid)continue;const origin=ctx.classes.filter(c=>c.idEscola===sid&&c.windowsOrigin?.banco===pack.banco&&Number(c.windowsOrigin?.idTurma)===Number(t.idTurma));const found=origin.length?origin:matchingWindowsClasses(windowsClassData(t,pack.banco,sid),ctx.classes);if(found.length===1)classes[String(t.idTurma)]=found[0].id;}choices={};selected.clear();}
 function state(a){const cid=classes[String(a.idTurma)],cl=ctx.classes.find(c=>c.id===cid);if(!cl||cl.idEscola!==schools[String(a.idEscola)])return {valid:false,text:'Associe a turma à escola correspondente'};const origin=studentOriginMatch(a,pack.banco,ctx.students);if(origin)return {valid:false,existing:origin.idTurma===cid,text:origin.idTurma===cid?'Já importado — preservar':'Já importado em outra turma — conferir'};const matches=studentNameMatches(a,cid,ctx.students),sameSource=pack.alunos.filter(x=>String(x.idTurma)===String(a.idTurma)&&String(x.nome).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')===String(a.nome).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')).length>1;
 const choice=choices[String(a.idParticipante)];if((matches.length||sameSource)&&!choice)return {valid:false,text:'Confira nome igual / homônimo',matches};if(choice&&choice!=='__new__'&&!matches.some(m=>m.id===choice))return {valid:false,text:'Correspondência alterada — conferir',matches};return {valid:true,text:choice&&choice!=='__new__'?'Preservar cadastro escolhido':'Pronto para criar',matches,needsChoice:matches.length||sameSource,choice:choice||'__new__'};}
 function draw(){if(!alive()||!pack)return;const used=pack.turmas.filter(t=>pack.alunos.some(a=>String(a.idTurma)===String(t.idTurma)));qs('#wsPreview').innerHTML=`<h4>1. Escolas e turmas</h4>${pack.escolas.filter(s=>used.some(t=>String(t.idEscola)===String(s.idEscola))).map(s=>`<label style="display:block;margin:8px 0">${esc(s.nome)} <select data-school="${esc(s.idEscola)}"><option value="">Selecione a escola</option>${ctx.schools.map(c=>`<option value="${esc(c.id)}" ${schools[String(s.idEscola)]===c.id?'selected':''}>${esc(c.nome)}</option>`).join('')}</select></label>`).join('')}<div style="overflow:auto"><table><thead><tr><th>Turma Windows</th><th>Turma no site</th><th>Alunos no arquivo</th></tr></thead><tbody>${used.map(t=>`<tr><td>${esc(t.descricao||t.nome)} • ${esc(t.turno)} • ${esc(t.anoLetivo)}<small style="display:block">${esc(pack.escolas.find(s=>String(s.idEscola)===String(t.idEscola))?.nome)}</small></td><td><select data-class="${esc(t.idTurma)}"><option value="">Selecione a turma</option>${ctx.classes.filter(c=>c.idEscola===schools[String(t.idEscola)]).map(c=>`<option value="${esc(c.id)}" ${classes[String(t.idTurma)]===c.id?'selected':''}>${esc(c.nome)} • ${esc(c.turno)} • ${esc(c.anoLetivo)}</option>`).join('')}</select></td><td>${pack.alunos.filter(a=>String(a.idTurma)===String(t.idTurma)).length}</td></tr>`).join('')}</tbody></table></div><h4>2. Alunos (${pack.alunos.length})</h4><p>Cadastros existentes não são sobrescritos. Data de nascimento e responsável permanecem em branco quando ausentes na origem.</p><button id="wsAll" type="button" class="btn ghost">Selecionar alunos válidos e ativos</button> <button id="wsNone" type="button" class="btn ghost">Desmarcar todos</button><div style="overflow:auto;max-height:480px"><table><thead><tr><th>Importar</th><th>Aluno</th><th>Turma de origem</th><th>Conferência</th></tr></thead><tbody>${pack.alunos.map((a,i)=>{const st=state(a);if(!st.valid)selected.delete(i);return `<tr><td><input type="checkbox" data-select="${i}" ${selected.has(i)?'checked':''} ${!st.valid?'disabled':''} aria-label="Importar aluno ${esc(a.idParticipante)}"></td><td>${esc(a.nome)}${Number(a.ativo)===0?' (inativo)':''}</td><td>${esc(pack.turmas.find(t=>String(t.idTurma)===String(a.idTurma))?.descricao)}</td><td>${esc(st.text)}${st.matches&&(st.needsChoice||st.matches.length||st.text.includes('homônimo'))?`<select data-choice="${esc(a.idParticipante)}"><option value="">Conferir correspondência</option><option value="__new__" ${choices[String(a.idParticipante)]==='__new__'?'selected':''}>Criar aluno distinto</option>${st.matches.map(m=>`<option value="${esc(m.id)}" ${choices[String(a.idParticipante)]===m.id?'selected':''}>Preservar existente: ${esc(m.nome)}</option>`).join('')}</select>`:''}</td></tr>`;}).join('')}</tbody></table></div><button id="wsSave" type="button" class="btn primary">Importar alunos selecionados</button>`;
 host.querySelectorAll('[data-school]').forEach(el=>el.onchange=()=>{schools[el.dataset.school]=el.value;suggest();draw();});host.querySelectorAll('[data-class]').forEach(el=>el.onchange=()=>{classes[el.dataset.class]=el.value;choices={};selected.clear();draw();});host.querySelectorAll('[data-choice]').forEach(el=>el.onchange=()=>{choices[el.dataset.choice]=el.value;draw();});host.querySelectorAll('[data-select]').forEach(el=>el.onchange=()=>el.checked?selected.add(Number(el.dataset.select)):selected.delete(Number(el.dataset.select)));
 qs('#wsAll').onclick=()=>{pack.alunos.forEach((a,i)=>{if(state(a).valid&&Number(a.ativo??1)!==0)selected.add(i);});draw();};qs('#wsNone').onclick=()=>{selected.clear();draw();};qs('#wsSave').onclick=save;
 }
 async function read(file){if(busy||!file)return;const request=++sequence;pack=null;selected.clear();qs('#wsPreview').innerHTML='';message('Lendo arquivo de alunos…');try{if(file.size>10*1024*1024)throw new Error('Limite de 10 MB.');const p=parseWindowsStudents(await file.text());if(!alive()||request!==sequence)return;pack=p;schools={};for(const s of pack.escolas){const found=matchingWindowsSchools(s,pack.banco,ctx.schools);if(found.length===1)schools[String(s.idEscola)]=found[0].id;}suggest();draw();message('Confira os vínculos e selecione os alunos.');}catch(e){message(e.message);}}
 async function save(){if(busy||!selected.size){message('Selecione pelo menos um aluno.');return;}busy=true;const items=[...selected];host.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);let created=0,reused=0,failure='';try{const fresh=await loadWindowsStudentCatalog();if(fresh.tenantId!==ctx.tenantId)throw new Error('Cliente alterado. Reabra a importação.');ctx=fresh;for(const i of items){if(!alive())throw new Error('Importação interrompida.');const a=pack.alunos[i],st=state(a);if(st.existing){reused++;selected.delete(i);continue;}if(!st.valid)throw new Error(a.nome+': '+st.text);message(`Importando ${created+reused+1} de ${items.length}: ${a.nome}`);const r=await importWindowsStudent(a,pack.banco,classes[String(a.idTurma)],ctx,st.choice==='__new__'?'':st.choice);if(r.created){created++;ctx.students.push({id:r.id,nome:a.nome,idTurma:classes[String(a.idTurma)],windowsOrigin:{banco:pack.banco,idParticipante:Number(a.idParticipante)}});}else reused++;selected.delete(i);}}catch(e){failure=e.message;}finally{try{const fresh=await loadWindowsStudentCatalog();if(fresh.tenantId===ctx.tenantId)ctx=fresh;}catch(e){failure=failure||e.message;}busy=false;if(alive()){host.querySelectorAll('input,select,button').forEach(el=>el.disabled=false);draw();message(`${created} alunos importados; ${reused} existentes preservados. ${failure?'Interrompido: '+failure+' Os registros salvos foram preservados.':'Feche a importação para atualizar a lista de alunos e os certificados.'}`);}}}
 qs('#wsFile').onchange=e=>read(e.target.files[0]);qs('#wsDrop').ondragover=e=>e.preventDefault();qs('#wsDrop').ondrop=e=>{e.preventDefault();if(e.dataTransfer.files.length!==1){message('Selecione um arquivo por vez.');return;}read(e.dataTransfer.files[0]);};qs('#wsClose').onclick=()=>{if(!busy){sequence++;host.hidden=true;host.innerHTML='';onDone?.();}};
}
