import {listWindowsArchives,loadWindowsArchive} from '../core/windowsArchiveRepository.js?v=1';
import {normalizeIntegral,programClasses,agendaHistory} from '../core/windowsIntegralPolicy.js?v=1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const when=v=>v?String(v).slice(0,19).replace('T',' '):'—';
export async function renderWindowsHistory(host,tenant,source=null){
 const token=Symbol();host._windowsHistoryToken=token;host.hidden=false;host.innerHTML='<p role="status">Carregando histórico do Windows...</p>';
 const live=()=>host.isConnected&&host._windowsHistoryToken===token;
 try{
  const archives=await listWindowsArchives(tenant);if(!live())return;
  host.innerHTML=`<h3>Histórico integral do Windows</h3><p>Dados originais da importação. Agendamentos e turmas do programa mantêm suas situações separadas. Este histórico não altera os cadastros atuais.</p><label>Arquivo importado<select id="whArchive"><option value="">Selecione</option>${archives.map(a=>`<option value="${esc(a.id)}">${esc(a.banco)} • ${a.agendamentos} agendamentos • ${when(a.createdAt?.toDate?.().toISOString())}</option>`).join('')}</select></label><p id="whMessage" role="status"></p><div id="whBody"></div><button type="button" class="btn ghost" id="whClose">Fechar histórico</button>`;
  const qs=s=>host.querySelector(s);let request=0,value=null;
  qs('#whClose').onclick=()=>{host._windowsHistoryToken=null;host.hidden=true;};
  async function load(){const seq=++request,hash=qs('#whArchive').value;qs('#whBody').innerHTML='';if(!hash)return;qs('#whMessage').textContent='Carregando arquivo completo...';try{const read=await loadWindowsArchive(hash,tenant);normalizeIntegral(read.pack);if(!live()||seq!==request)return;value=read;draw();qs('#whMessage').textContent='Histórico carregado e integridade conferida.';}catch(e){if(live()&&seq===request)qs('#whMessage').textContent=e.message;}}
  function draw(school=''){
   const {pack,mappings}=value,tab=pack.tabelas;
   const agendas=tab.tblAgendaEvento.filter(a=>!school||String(a.idEscola)===school);
   const events=tab.tblEvento.filter(e=>programClasses(pack,e.idEvento,school).length);
   qs('#whBody').innerHTML=`<label>Escola de origem<select id="whSchool"><option value="">Todas as escolas e demandas</option>${tab.tblEscola.map(s=>`<option value="${s.idEscola}" ${String(s.idEscola)===school?'selected':''}>${esc(s.nome)}${mappings[String(s.idEscola)]?' • associada no site':''}</option>`).join('')}</select></label><button type="button" class="btn ghost" id="whExport">Baixar cópia integral em JSON</button><h4>Agendamentos originais (${agendas.length})</h4>${agendas.map(a=>{const h=agendaHistory(pack,a.idAgenda);return `<details ${source?.agendaId===Number(a.idAgenda)?'open':''}><summary>#${a.idAgenda} ${esc(a.unidadeEscolar)} • ${when(a.dataInicio)} • ${esc(a.status)}</summary><p>${esc(a.programa)} • ${esc(a.turno)} • ${a.quantidadeTurmas} turma(s)<br>Início: ${when(a.dataInicio)} • Fim: ${when(a.dataFim)}<br>Responsável: ${esc(a.responsavel)} • Contato: ${esc(a.contatoEscola)} ${esc(a.telefone)}<br>Prioridade: ${esc(a.prioridade)} • Evento na origem: ${esc(a.idEvento??'sem vínculo registrado')}</p><p style="white-space:pre-wrap">${esc(a.observacoes)}</p><h5>Checklist (${h.checklist.length})</h5><ul>${h.checklist.map(c=>`<li>${Number(c.concluido)?'✓':'○'} ${esc(c.item)}${Number(c.obrigatorio)?' • obrigatório':''} ${esc(c.observacao||'')} ${c.dataConclusao?' • '+when(c.dataConclusao):''}</li>`).join('')}</ul><h5>Alarmes preservados (${h.alarmes.length})</h5><ul>${h.alarmes.map(c=>`<li>${c.minutosAntes} min antes • ${Number(c.ativo)?'ativo':'inativo'} • avisado: ${when(c.avisadoEm)} • adiado: ${when(c.adiadoAte)}</li>`).join('')}</ul><p>Os alarmes históricos são consultivos; não disparam notificações no site.</p></details>`;}).join('')}<h4>Programas e turmas vinculadas</h4>${events.map(e=>`<details open><summary>${esc(e.nome)} • status do evento: ${esc(e.status)}</summary><div style="overflow:auto"><table><thead><tr><th>Escola / turma</th><th>Situação da turma</th><th>Início / fim reais</th><th>Fila</th></tr></thead><tbody>${programClasses(pack,e.idEvento,school).map(r=>`<tr><td>${esc(r.escola.nome)}<br>${esc(r.turma.descricao)} • ${esc(r.turma.turno||r.turma.periodo)} • ${esc(r.turma.anoLetivo)}</td><td>${esc(r.situacao)}<small style="display:block">Salvo na origem: ${esc(r.operacao.status||'não informado')}${r.calculado?' • painel calculado pela fila':''}</small></td><td>Previsto: ${when(r.operacao.horarioPrevisto)}<br>${when(r.inicio)}<br>${when(r.fim)}</td><td>${r.calculado?`${r.counts.total} participantes • ${r.counts.finalizados} finalizados • ${r.counts.ausentes} ausentes • ${r.counts.aguardando} aguardando`:'Fila não incluída nesta versão do arquivo'}</td></tr>`).join('')}</tbody></table></div></details>`).join('')||'<p>Não há vínculos de programa para esta escola no arquivo.</p>'}`;
   qs('#whSchool').onchange=e=>draw(e.target.value);
   qs('#whExport').onclick=()=>{const blob=new Blob([JSON.stringify(value.pack,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Agenda_Integral_'+value.pack.banco+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  }
  qs('#whArchive').onchange=load;if(source?.archiveId){qs('#whArchive').value=source.archiveId;await load();}
 }catch(e){if(live())host.innerHTML='<p role="alert">'+esc(e.message)+'. Confira a publicação das regras atualizadas do Firestore.</p>';}
}
