import {parseWindowsFile} from './windowsAgendaImport.js?v=4';
import {loadWindowsClassCatalog,importWindowsClass} from '../core/windowsClassRepository.js?v=1';
import {windowsClassData,matchingWindowsClasses,matchingWindowsSchools} from '../core/windowsClassPolicy.js?v=1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function renderWindowsClassImport(host,onDone){
 host.hidden=false;host.innerHTML='<p>Carregando escolas e turmas…</p>';const anchor=host.firstChild;let ctx;try{ctx=await loadWindowsClassCatalog();}catch(e){if(host.firstChild===anchor)host.textContent=e.message;return;}if(host.firstChild!==anchor)return;
 host.innerHTML=`<h3>Importar turmas do Windows</h3><p>Cliente: <strong>${esc(ctx.tenantId)}</strong>. Use o mesmo JSON ou XML da importação das escolas. Confira os vínculos antes de gravar. Os alunos não são importados nesta etapa.</p><label id="wcDrop" class="btn ghost">Arraste o arquivo ou selecione<input id="wcFile" type="file" accept=".json,.xml"></label><div id="wcPreview"></div><p id="wcMessage" role="status" aria-live="polite"></p><button id="wcClose" type="button" class="btn ghost">Fechar importação</button>`;
 const marker=host.firstChild,alive=()=>host.isConnected&&host.firstChild===marker,qs=s=>host.querySelector(s);let pack,mappings={},selected=new Set(),busy=false,sequence=0;
 const message=t=>{if(alive())qs('#wcMessage').textContent=t;};
 function state(t){try{const school=mappings[String(t.idEscola)];if(!ctx.schools.some(s=>s.id===school))throw new Error('Associe a escola');const row=windowsClassData(t,pack.banco,school,pack),matches=matchingWindowsClasses(row,ctx.classes),original=ctx.classes.find(c=>c.id===row.id);if(original&&original.idEscola!==school)throw new Error('Já importada em outra escola');if(matches.length>1)throw new Error('Correspondência ambígua');return {valid:true,existing:!!original||matches.length===1,text:original||matches.length===1?'Já cadastrada — preservar':'Pronta para importar'};}catch(e){return {valid:false,text:e.message};}}
 function draw(){if(!alive()||!pack)return;qs('#wcPreview').innerHTML=`<h4>Escolas correspondentes</h4>${pack.escolas.filter(s=>pack.turmas.some(t=>String(t.idEscola)===String(s.idEscola))).map(s=>`<label style="display:block;margin:8px 0">${esc(s.nome)} <select data-school="${esc(s.idEscola)}"><option value="">Selecione a escola do site</option>${ctx.schools.map(c=>`<option value="${esc(c.id)}" ${mappings[String(s.idEscola)]===c.id?'selected':''}>${esc(c.nome)}</option>`).join('')}</select></label>`).join('')}<h4>Turmas (${pack.turmas.length})</h4><p>Nome, turno, ano letivo e dados originais serão preservados. Turmas inativas podem ser selecionadas. Cadastros existentes permanecem como estão.</p><button id="wcAll" type="button" class="btn ghost">Selecionar turmas pendentes e ativas</button> <button id="wcNone" type="button" class="btn ghost">Desmarcar todas</button><div style="overflow:auto"><table><thead><tr><th>Importar</th><th>Turma</th><th>Escola de origem</th><th>Turno / ano</th><th>Conferência</th></tr></thead><tbody>${pack.turmas.map((t,i)=>{const st=state(t);if(!st.valid||st.existing)selected.delete(i);return `<tr><td><input type="checkbox" data-select="${i}" ${selected.has(i)?'checked':''} ${!st.valid||st.existing?'disabled':''}></td><td>${esc(t.descricao||t.nome)}${Number(t.ativo)===0?' (inativa)':''}</td><td>${esc(pack.escolas.find(s=>String(s.idEscola)===String(t.idEscola))?.nome)}</td><td>${esc(t.turno)} / ${esc(t.anoLetivo)}</td><td>${esc(st.text)}</td></tr>`;}).join('')}</tbody></table></div><button id="wcSave" type="button" class="btn primary">Importar turmas selecionadas</button>`;
 host.querySelectorAll('[data-school]').forEach(el=>el.onchange=()=>{mappings[el.dataset.school]=el.value;selected.clear();draw();});host.querySelectorAll('[data-select]').forEach(el=>el.onchange=()=>el.checked?selected.add(Number(el.dataset.select)):selected.delete(Number(el.dataset.select)));
 qs('#wcAll').onclick=()=>{pack.turmas.forEach((t,i)=>{const s=state(t);if(s.valid&&!s.existing&&Number(t.ativo??1)!==0)selected.add(i);});draw();};qs('#wcNone').onclick=()=>{selected.clear();draw();};qs('#wcSave').onclick=save;
 }
 async function read(file){if(busy||!file)return;const request=++sequence;try{if(file.size>10*1024*1024)throw new Error('Limite de 10 MB.');const parsed=parseWindowsFile(await file.text());if(!alive()||request!==sequence)return;if(!parsed.turmas.length)throw new Error('Arquivo sem turmas.');pack=parsed;mappings={};selected.clear();for(const s of pack.escolas){const found=matchingWindowsSchools(s,pack.banco,ctx.schools);if(found.length===1)mappings[String(s.idEscola)]=found[0].id;}draw();message('Confira as escolas, selecione as turmas e importe.');}catch(e){message(e.message);}}
 async function save(){if(busy||!selected.size){message('Selecione pelo menos uma turma.');return;}busy=true;const items=[...selected];host.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);let created=0,reused=0,failure='';try{const fresh=await loadWindowsClassCatalog();if(fresh.tenantId!==ctx.tenantId)throw new Error('Cliente alterado. Reabra a importação.');ctx=fresh;for(const i of items){if(!alive())throw new Error('Importação interrompida.');const t=pack.turmas[i];message(`Importando ${created+reused+1} de ${items.length}: ${t.descricao||t.nome}`);const r=await importWindowsClass(t,pack,mappings[String(t.idEscola)],ctx);if(r.created)created++;else reused++;selected.delete(i);} }catch(e){failure=e.message;}finally{try{const fresh=await loadWindowsClassCatalog();if(fresh.tenantId===ctx.tenantId)ctx=fresh;}catch(e){failure=failure||e.message;}busy=false;if(alive()){host.querySelectorAll('input,select,button').forEach(el=>el.disabled=false);draw();message(`${created} turmas importadas; ${reused} já existentes preservadas. ${failure?'Interrompido: '+failure+' Os registros salvos foram preservados.':'Feche a importação para atualizar a lista de turmas.'}`);}}}
 qs('#wcFile').onchange=e=>read(e.target.files[0]);qs('#wcDrop').ondragover=e=>e.preventDefault();qs('#wcDrop').ondrop=e=>{e.preventDefault();if(e.dataTransfer.files.length!==1){message('Selecione um arquivo por vez.');return;}read(e.dataTransfer.files[0]);};qs('#wcClose').onclick=()=>{if(!busy){sequence++;host.hidden=true;host.innerHTML='';onDone?.();}};
}
